/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../types/enums.js";
import { HTTPClient } from "./http.js";
import { Logger } from "./logger.js";
import { RetryConfig } from "./retries.js";
import { Params, pathToFunc } from "./url.js";

/**
 * Contains the list of servers available to the SDK
 */
export const ServerList = [
  /**
   * Servers
   */
  "https://{server}",
] as const;

/**
 * Server option
 */
export const ServerServer = {
  SandboxapiCrmCom: "sandboxapi.crm.com",
  StagingapiCrmCom: "stagingapi.crm.com",
  SandboxssapiCrmCom: "sandboxssapi.crm.com",
  SandboxCrmCom: "sandbox.crm.com",
} as const;
/**
 * Server option
 */
export type ServerServer = ClosedEnum<typeof ServerServer>;

export type SDKOptions = {
  authorizationSelfService?: string | (() => Promise<string>) | undefined;

  httpClient?: HTTPClient;
  /**
   * Allows overriding the default server used by the SDK
   */
  serverIdx?: number | undefined;
  /**
   * Sets the server variable for url substitution
   */
  server?: ServerServer | undefined;
  /**
   * Allows overriding the default server URL used by the SDK
   */
  serverURL?: string | undefined;
  /**
   * Allows overriding the default user agent used by the SDK
   */
  userAgent?: string | undefined;
  /**
   * Allows overriding the default retry config used by the SDK
   */
  retryConfig?: RetryConfig;
  timeoutMs?: number;
  debugLogger?: Logger;
};

export function serverURLFromOptions(options: SDKOptions): URL | null {
  let serverURL = options.serverURL;

  const serverParams: Params[] = [
    {
      "server": options.server ?? "sandboxapi.crm.com",
    },
  ];
  let params: Params = {};

  if (!serverURL) {
    const serverIdx = options.serverIdx ?? 0;
    if (serverIdx < 0 || serverIdx >= ServerList.length) {
      throw new Error(`Invalid server index ${serverIdx}`);
    }
    serverURL = ServerList[serverIdx] || "";
    params = serverParams[serverIdx] || {};
  }

  const u = pathToFunc(serverURL)(params);
  return new URL(u);
}

export const SDK_METADATA = {
  language: "typescript",
  openapiDocVersion: "v2",
  sdkVersion: "0.0.5",
  genVersion: "2.835.2",
  userAgent: "speakeasy-sdk/typescript 0.0.5 2.835.2 v2 crm",
} as const;
