/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6cfbf0e0ee94
 */

import * as z from "zod/v4-mini";
import { CrmcomCore } from "../core.js";
import { encodeFormQuery, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { CrmError } from "../models/errors/crm-error.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/http-client-errors.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * List Account Journals
 *
 * @remarks
 * Retrieve a list of account journals. Only journals with Posted transactions are returned. By default, accounts journals of the last 12 months are retrieved.
 */
export function contactAccountsComCrmAccountSelfServiceResourceListAccountJournals(
  client: CrmcomCore,
  request:
    operations.ComCrmAccountSelfServiceResourceListAccountJournalsRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    operations.ComCrmAccountSelfServiceResourceListAccountJournalsResponse,
    | CrmError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: CrmcomCore,
  request:
    operations.ComCrmAccountSelfServiceResourceListAccountJournalsRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      operations.ComCrmAccountSelfServiceResourceListAccountJournalsResponse,
      | CrmError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) =>
      z.parse(
        operations
          .ComCrmAccountSelfServiceResourceListAccountJournalsRequest$outboundSchema,
        value,
      ),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = null;

  const pathParams = {
    id: encodeSimple("id", payload.id, {
      explode: false,
      charEncoding: "percent",
    }),
  };

  const path = pathToFunc("/self-service/v2/accounts/{id}/journals")(
    pathParams,
  );

  const query = encodeFormQuery({
    "include_total": payload.include_total,
    "order": payload.order,
    "page": payload.page,
    "posted_on": payload.posted_on,
    "size": payload.size,
    "sort": payload.sort,
    "transaction_type": payload.transaction_type,
    "type": payload.type,
  });

  const headers = new Headers(compactMap({
    Accept: "application/json",
  }));

  const secConfig = await extractSecurity(
    client._options.authorizationSelfService,
  );
  const securityInput = secConfig == null
    ? {}
    : { authorizationSelfService: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "com.crm.AccountSelfServiceResource_listAccountJournals",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.authorizationSelfService,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    query: query,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: [
      "400",
      "401",
      "403",
      "404",
      "4XX",
      "500",
      "502",
      "503",
      "504",
      "5XX",
    ],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const [result] = await M.match<
    operations.ComCrmAccountSelfServiceResourceListAccountJournalsResponse,
    | CrmError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(
      200,
      operations
        .ComCrmAccountSelfServiceResourceListAccountJournalsResponse$inboundSchema,
    ),
    M.fail([400, 401, 403, 404, "4XX"]),
    M.fail([500, 502, 503, 504, "5XX"]),
  )(response, req);
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
