/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { addressLookupComCrmAddressRegistrySelfServiceResourceGetAddress } from "../funcs/address-lookup-com-crm-address-registry-self-service-resource-get-address.js";
import { addressLookupComCrmAddressRegistrySelfServiceResourceList } from "../funcs/address-lookup-com-crm-address-registry-self-service-resource-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class AddressLookup extends ClientSDK {
  /**
   * Search Addresses
   *
   * @remarks
   * Returns a list of addresses based on the Google Place Autocomplete API. A retrieved google place id can then be used for the Get Address API. A version 4 UUID should be used as the session_id for a given session. A session starts with one or more Search Addresses API calls, and ends with one Get Address API call. Make sure to generate a new session_id for each new session. When a session_id is reused after the session has concluded, Per Request billing applies instead of Per Session billing.
   */
  async comCrmAddressRegistrySelfServiceResourceList(
    request: operations.ComCrmAddressRegistrySelfServiceResourceListRequest,
    options?: RequestOptions,
  ): Promise<operations.ComCrmAddressRegistrySelfServiceResourceListResponse> {
    return unwrapAsync(
      addressLookupComCrmAddressRegistrySelfServiceResourceList(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Get Address
   *
   * @remarks
   * Returns address details based on the Google Place Details API. The google place id used for this API could be retrieved with the Search Addresses API. A version 4 UUID should be used as the session_id for a given session. A session starts with one or more Search Addresses API calls, and ends with one Get Address API call. Make sure to generate a new session_id for each new session. When a session_id is reused after the session has concluded, Per Request billing applies instead of Per Session billing.
   */
  async comCrmAddressRegistrySelfServiceResourceGetAddress(
    security:
      operations.ComCrmAddressRegistrySelfServiceResourceGetAddressSecurity,
    request:
      operations.ComCrmAddressRegistrySelfServiceResourceGetAddressRequest,
    options?: RequestOptions,
  ): Promise<
    operations.ComCrmAddressRegistrySelfServiceResourceGetAddressResponse
  > {
    return unwrapAsync(
      addressLookupComCrmAddressRegistrySelfServiceResourceGetAddress(
        this,
        security,
        request,
        options,
      ),
    );
  }
}
