/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ffd9f84167ea
 */

import { commercePoolsComCrmCommercePoolSelfServiceResourceActions } from "../funcs/commerce-pools-com-crm-commerce-pool-self-service-resource-actions.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class CommercePools extends ClientSDK {
  /**
   * Commerce Pool Actions
   *
   * @remarks
   * Perform actions on existing commerce pool (e.g. activate commerce pool)
   */
  async comCrmCommercePoolSelfServiceResourceActions(
    request: operations.ComCrmCommercePoolSelfServiceResourceActionsRequest,
    options?: RequestOptions,
  ): Promise<operations.ComCrmCommercePoolSelfServiceResourceActionsResponse> {
    return unwrapAsync(
      commercePoolsComCrmCommercePoolSelfServiceResourceActions(
        this,
        request,
        options,
      ),
    );
  }
}
