/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  contactDonationsComCrmContactDonationSelfServiceResourceListContactDonationsHistory,
} from "../funcs/contact-donations-com-crm-contact-donation-self-service-resource-list-contact-donations-history.js";
import { contactDonationsComCrmContactSelfServiceResourceListContactDonations } from "../funcs/contact-donations-com-crm-contact-self-service-resource-list-contact-donations.js";
import { contactDonationsComCrmContactSelfServiceResourceOptInDonations } from "../funcs/contact-donations-com-crm-contact-self-service-resource-opt-in-donations.js";
import { contactDonationsComCrmContactSelfServiceResourceOptOutDonations } from "../funcs/contact-donations-com-crm-contact-self-service-resource-opt-out-donations.js";
import { contactDonationsComCrmContactSelfServiceResourceUpdateDonations } from "../funcs/contact-donations-com-crm-contact-self-service-resource-update-donations.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ContactDonations extends ClientSDK {
  /**
   * List Contact Donation Offers
   *
   * @remarks
   * By default returns a list of donations to which the contact is currenlty opt-in. Optionally, the Web API can be used to additionally retrieve any donation offers to which the contact has opted-out from.
   */
  async comCrmContactSelfServiceResourceListContactDonations(
    request:
      operations.ComCrmContactSelfServiceResourceListContactDonationsRequest,
    options?: RequestOptions,
  ): Promise<
    operations.ComCrmContactSelfServiceResourceListContactDonationsResponse
  > {
    return unwrapAsync(
      contactDonationsComCrmContactSelfServiceResourceListContactDonations(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Contact Donation Actions
   *
   * @remarks
   * Use Web API whenever a contact wants to opt-in to a Donation offer. Once opt-in, a new Donation is made automatically either on each contact purchase or on a termed basis, depending on the donation offer to which the contact opted-in. Contact might opt-in to various Donation offers and can opt-out at any point of time.
   */
  async comCrmContactSelfServiceResourceOptInDonations(
    request: operations.ComCrmContactSelfServiceResourceOptInDonationsRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      contactDonationsComCrmContactSelfServiceResourceOptInDonations(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * List Contact Donation Offers History
   *
   * @remarks
   * Returns a list of donations made by the contact so far.
   */
  async comCrmContactDonationSelfServiceResourceListContactDonationsHistory(
    request:
      operations.ComCrmContactDonationSelfServiceResourceListContactDonationsHistoryRequest,
    options?: RequestOptions,
  ): Promise<
    operations.ComCrmContactDonationSelfServiceResourceListContactDonationsHistoryResponse
  > {
    return unwrapAsync(
      contactDonationsComCrmContactDonationSelfServiceResourceListContactDonationsHistory(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Update donation offer preferences
   *
   * @remarks
   * Update a contact's preferences for the donations to which they opted-in. Only one of the request parameters can be updated in each Web API call. Only donation offers to which the contact is currently opted-in can be updated.
   */
  async comCrmContactSelfServiceResourceUpdateDonations(
    request: operations.ComCrmContactSelfServiceResourceUpdateDonationsRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      contactDonationsComCrmContactSelfServiceResourceUpdateDonations(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Opt out from Donation offer
   *
   * @remarks
   * Opts-out a contact from a donation offer. Only donation offers to which the contact is currenlty opted-in can be removed.
   */
  async comCrmContactSelfServiceResourceOptOutDonations(
    request: operations.ComCrmContactSelfServiceResourceOptOutDonationsRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      contactDonationsComCrmContactSelfServiceResourceOptOutDonations(
        this,
        request,
        options,
      ),
    );
  }
}
