/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { contactFinancialsComCrmContactSelfServiceResourceGetClientToken } from "../funcs/contact-financials-com-crm-contact-self-service-resource-get-client-token.js";
import { contactFinancialsComCrmPaymentIntentSelfServiceResourceSetUpIntents } from "../funcs/contact-financials-com-crm-payment-intent-self-service-resource-set-up-intents.js";
import { contactFinancialsComCrmPaymentSelfServiceResourceCreate } from "../funcs/contact-financials-com-crm-payment-self-service-resource-create.js";
import { contactFinancialsComCrmPayoutSelfServiceResourceCreate } from "../funcs/contact-financials-com-crm-payout-self-service-resource-create.js";
import { contactFinancialsComCrmSettlementTransactionSelfServiceResourceGetMetrics } from "../funcs/contact-financials-com-crm-settlement-transaction-self-service-resource-get-metrics.js";
import { contactFinancialsComCrmSettlementTransactionSelfServiceResourceList } from "../funcs/contact-financials-com-crm-settlement-transaction-self-service-resource-list.js";
import { contactFinancialsComCrmTopUpSelfServiceResourceCreate } from "../funcs/contact-financials-com-crm-top-up-self-service-resource-create.js";
import { contactFinancialsComCrmTransferSelfServiceResourceCreateTransferBulk } from "../funcs/contact-financials-com-crm-transfer-self-service-resource-create-transfer-bulk.js";
import { contactFinancialsComCrmTransferSelfServiceResourceCreate } from "../funcs/contact-financials-com-crm-transfer-self-service-resource-create.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ContactFinancials extends ClientSDK {
  /**
   * Get a Contact Client Token
   */
  async comCrmContactSelfServiceResourceGetClientToken(
    request: operations.ComCrmContactSelfServiceResourceGetClientTokenRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      contactFinancialsComCrmContactSelfServiceResourceGetClientToken(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Create Intent
   *
   * @remarks
   * Set up a new payment intent for a specific contact. A Payment intent represents the contact's intention to make a payment using one of the registered online payment methods. The response varies depending on the Payment Gateway service that processes the intent.
   */
  async comCrmPaymentIntentSelfServiceResourceSetUpIntents(
    request:
      operations.ComCrmPaymentIntentSelfServiceResourceSetUpIntentsRequest,
    options?: RequestOptions,
  ): Promise<
    operations.ComCrmPaymentIntentSelfServiceResourceSetUpIntentsResponse
  > {
    return unwrapAsync(
      contactFinancialsComCrmPaymentIntentSelfServiceResourceSetUpIntents(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Create Payment
   *
   * @remarks
   * Create a new Payment transaction for a Contact. The Payment will be issued as Posted.
   */
  async comCrmPaymentSelfServiceResourceCreate(
    security: operations.ComCrmPaymentSelfServiceResourceCreateSecurity,
    request?:
      | operations.ComCrmPaymentSelfServiceResourceCreateRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<operations.ComCrmPaymentSelfServiceResourceCreateResponse> {
    return unwrapAsync(contactFinancialsComCrmPaymentSelfServiceResourceCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create Payout
   *
   * @remarks
   * Create a new payout financial transaction against a wallet
   */
  async comCrmPayoutSelfServiceResourceCreate(
    security: operations.ComCrmPayoutSelfServiceResourceCreateSecurity,
    request?:
      | operations.ComCrmPayoutSelfServiceResourceCreateRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<operations.ComCrmPayoutSelfServiceResourceCreateResponse> {
    return unwrapAsync(contactFinancialsComCrmPayoutSelfServiceResourceCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get Settlement Transactions
   *
   * @remarks
   * Retrieve the settlement transactions related to B2B Settlement
   */
  async comCrmSettlementTransactionSelfServiceResourceList(
    request?:
      | operations.ComCrmSettlementTransactionSelfServiceResourceListRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<
    operations.ComCrmSettlementTransactionSelfServiceResourceListResponse
  > {
    return unwrapAsync(
      contactFinancialsComCrmSettlementTransactionSelfServiceResourceList(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Get Settlement Transactions Metrics
   *
   * @remarks
   * Retrieve some metrics related to the settlement transactions
   */
  async comCrmSettlementTransactionSelfServiceResourceGetMetrics(
    request?:
      | operations.ComCrmSettlementTransactionSelfServiceResourceGetMetricsRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<
    operations.ComCrmSettlementTransactionSelfServiceResourceGetMetricsResponse
  > {
    return unwrapAsync(
      contactFinancialsComCrmSettlementTransactionSelfServiceResourceGetMetrics(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Create Top-up
   *
   * @remarks
   * Create a new Topup for a Wallet
   */
  async comCrmTopUpSelfServiceResourceCreate(
    security: operations.ComCrmTopUpSelfServiceResourceCreateSecurity,
    request?:
      | operations.ComCrmTopUpSelfServiceResourceCreateRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<operations.ComCrmTopUpSelfServiceResourceCreateResponse> {
    return unwrapAsync(contactFinancialsComCrmTopUpSelfServiceResourceCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Transfer Money
   *
   * @remarks
   * Transfers an amount of money from one account or wallet to another account or wallet. A single transfer can be created per Web API call. An amount of money can be transferred to another account/wallet of the same contact who owns the origin account/wallet or transferred to another contact's account/wallet.
   */
  async comCrmTransferSelfServiceResourceCreate(
    security: operations.ComCrmTransferSelfServiceResourceCreateSecurity,
    request?:
      | operations.ComCrmTransferSelfServiceResourceCreateRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<operations.ComCrmTransferSelfServiceResourceCreateResponse> {
    return unwrapAsync(contactFinancialsComCrmTransferSelfServiceResourceCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Transfer Money in Bulk
   *
   * @remarks
   * Transfers an amount of money from one account or wallet to another account or wallet in bulk. A single transaction will be created for each transfer request. An amount of money can be transferred to another account/wallet of the same contact who owns the origin account/wallet or transferred to another contact's account/wallet.
   */
  async comCrmTransferSelfServiceResourceCreateTransferBulk(
    security:
      operations.ComCrmTransferSelfServiceResourceCreateTransferBulkSecurity,
    request?: Array<operations.RequestBody> | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      contactFinancialsComCrmTransferSelfServiceResourceCreateTransferBulk(
        this,
        security,
        request,
        options,
      ),
    );
  }
}
