/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3cd23dfad8c9
 */

import { estimatesComCrmEstimateOrderSelfServiceResourceEstimateOrder } from "../funcs/estimates-com-crm-estimate-order-self-service-resource-estimate-order.js";
import { estimatesComCrmEstimateSelfServiceResourceEstimateInvoicing } from "../funcs/estimates-com-crm-estimate-self-service-resource-estimate-invoicing.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Estimates extends ClientSDK {
  /**
   * Invoicing
   *
   * @remarks
   * Returns an estimation of how much a customer will pay when purchasing a product. The estimation includes not just the product’s final price, but also various detailed amounts on how the estimated cost is calculated
   */
  async comCrmEstimateSelfServiceResourceEstimateInvoicing(
    security:
      operations.ComCrmEstimateSelfServiceResourceEstimateInvoicingSecurity,
    request?:
      | operations.ComCrmEstimateSelfServiceResourceEstimateInvoicingRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<
    operations.ComCrmEstimateSelfServiceResourceEstimateInvoicingResponse
  > {
    return unwrapAsync(
      estimatesComCrmEstimateSelfServiceResourceEstimateInvoicing(
        this,
        security,
        request,
        options,
      ),
    );
  }

  /**
   * Order Preview
   *
   * @remarks
   * Preview order information before making an order including fulfillment and invoice estimations
   *                                     <h4>Notes</h4>
   *                                     <div><div><div><strong>ORDER FLOW</strong></div><p>Integrating an order flow the following APIs should be called
   * The following APIs should be called in order to make an order</p>
   * <ol>
   * <li>Order Fulfillment</li>
   * <li>Orders Preview</li>
   * <li>Submit Order</li>
   * </ol>
   * </div>
   * </div>
   */
  async comCrmEstimateOrderSelfServiceResourceEstimateOrder(
    security:
      operations.ComCrmEstimateOrderSelfServiceResourceEstimateOrderSecurity,
    request?:
      | operations.ComCrmEstimateOrderSelfServiceResourceEstimateOrderRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<
    operations.ComCrmEstimateOrderSelfServiceResourceEstimateOrderResponse
  > {
    return unwrapAsync(
      estimatesComCrmEstimateOrderSelfServiceResourceEstimateOrder(
        this,
        security,
        request,
        options,
      ),
    );
  }
}
