/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9883d096f4c8
 */

import { organisationsComCrmBusinessActivitySelfServiceResourceListBusinessActivities } from "../funcs/organisations-com-crm-business-activity-self-service-resource-list-business-activities.js";
import { organisationsComCrmLocationSelfServiceResourceListTowns } from "../funcs/organisations-com-crm-location-self-service-resource-list-towns.js";
import { organisationsComCrmLocationSelfServiceResourceList } from "../funcs/organisations-com-crm-location-self-service-resource-list.js";
import { organisationsComCrmMerchantSelfServiceResourceList } from "../funcs/organisations-com-crm-merchant-self-service-resource-list.js";
import { organisationsComCrmOrganisationSelfServiceResourceGetSingle } from "../funcs/organisations-com-crm-organisation-self-service-resource-get-single.js";
import { organisationsComCrmOrganisationSelfServiceResourceList } from "../funcs/organisations-com-crm-organisation-self-service-resource-list.js";
import { organisationsComCrmOrganisationSelfServiceResourceSwitchOrganisation } from "../funcs/organisations-com-crm-organisation-self-service-resource-switch-organisation.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Organisations extends ClientSDK {
  /**
   * List Business Activities
   *
   * @remarks
   * Returns a list of business activities
   */
  async comCrmBusinessActivitySelfServiceResourceListBusinessActivities(
    request?:
      | operations.ComCrmBusinessActivitySelfServiceResourceListBusinessActivitiesRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<
    operations.ComCrmBusinessActivitySelfServiceResourceListBusinessActivitiesResponse
  > {
    return unwrapAsync(
      organisationsComCrmBusinessActivitySelfServiceResourceListBusinessActivities(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Locations
   *
   * @remarks
   * Get a list of organisations (merchants, venues) ordered by nearest first
   */
  async comCrmLocationSelfServiceResourceList(
    request: operations.ComCrmLocationSelfServiceResourceListRequest,
    options?: RequestOptions,
  ): Promise<operations.ComCrmLocationSelfServiceResourceListResponse> {
    return unwrapAsync(organisationsComCrmLocationSelfServiceResourceList(
      this,
      request,
      options,
    ));
  }

  /**
   * Locations
   *
   * @remarks
   * Get a list of organisations (merchants, venues) ordered by nearest first
   */
  async comCrmLocationSelfServiceResourceListTowns(
    options?: RequestOptions,
  ): Promise<operations.ComCrmLocationSelfServiceResourceListTownsResponse> {
    return unwrapAsync(organisationsComCrmLocationSelfServiceResourceListTowns(
      this,
      options,
    ));
  }

  /**
   * Get Organisation
   *
   * @remarks
   * Retrieve all details for a specific organisation
   */
  async comCrmOrganisationSelfServiceResourceGetSingle(
    request: operations.ComCrmOrganisationSelfServiceResourceGetSingleRequest,
    options?: RequestOptions,
  ): Promise<
    operations.ComCrmOrganisationSelfServiceResourceGetSingleResponse
  > {
    return unwrapAsync(
      organisationsComCrmOrganisationSelfServiceResourceGetSingle(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Search Organisations
   *
   * @remarks
   * Retrieve a list of organisations that comprise the business network
   */
  async comCrmOrganisationSelfServiceResourceList(
    request: operations.ComCrmOrganisationSelfServiceResourceListRequest,
    options?: RequestOptions,
  ): Promise<operations.ComCrmOrganisationSelfServiceResourceListResponse> {
    return unwrapAsync(organisationsComCrmOrganisationSelfServiceResourceList(
      this,
      request,
      options,
    ));
  }

  /**
   * Switch Organisations
   *
   * @remarks
   * Switch a contact’s access to another organisation that he/she is a member of
   */
  async comCrmOrganisationSelfServiceResourceSwitchOrganisation(
    request:
      operations.ComCrmOrganisationSelfServiceResourceSwitchOrganisationRequest,
    options?: RequestOptions,
  ): Promise<
    operations.ComCrmOrganisationSelfServiceResourceSwitchOrganisationResponse
  > {
    return unwrapAsync(
      organisationsComCrmOrganisationSelfServiceResourceSwitchOrganisation(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Participating Merchants
   *
   * @remarks
   * Search for organisations with active reward commercial terms that participate in one of the customer’s reward schemes
   */
  async comCrmMerchantSelfServiceResourceList(
    request?:
      | operations.ComCrmMerchantSelfServiceResourceListRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<operations.ComCrmMerchantSelfServiceResourceListResponse> {
    return unwrapAsync(organisationsComCrmMerchantSelfServiceResourceList(
      this,
      request,
      options,
    ));
  }
}
