/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 21852111e1bc
 */

import { paymentFormsComCrmPaymentFormSelfServiceResourceGenerateAddCardForm } from "../funcs/payment-forms-com-crm-payment-form-self-service-resource-generate-add-card-form.js";
import { paymentFormsComCrmPaymentFormSelfServiceResourceGeneratePassPaymentForm } from "../funcs/payment-forms-com-crm-payment-form-self-service-resource-generate-pass-payment-form.js";
import { paymentFormsComCrmPaymentFormSelfServiceResourceGeneratePaymentForm } from "../funcs/payment-forms-com-crm-payment-form-self-service-resource-generate-payment-form.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class PaymentForms extends ClientSDK {
  /**
   * Add Card
   *
   * @remarks
   * Web API used when consumers add a Card from a Landing page. The Web API forwards information of the card, along with the buyer details. In addition, the Web API integrates with the Payment Gateway service and request to load their payment form for an easy payment processing. To avoid any issues, it's vital to check the Payment Gateway service's mandatory information requirements, such as the buyer's email, phone, and address information, before triggering the Web API.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async comCrmPaymentFormSelfServiceResourceGenerateAddCardForm(
    security:
      operations.ComCrmPaymentFormSelfServiceResourceGenerateAddCardFormSecurity,
    request:
      operations.ComCrmPaymentFormSelfServiceResourceGenerateAddCardFormRequest,
    options?: RequestOptions,
  ): Promise<
    operations.ComCrmPaymentFormSelfServiceResourceGenerateAddCardFormResponse
  > {
    return unwrapAsync(
      paymentFormsComCrmPaymentFormSelfServiceResourceGenerateAddCardForm(
        this,
        security,
        request,
        options,
      ),
    );
  }

  /**
   * Get Gift Pass Payment Form
   *
   * @remarks
   * Web API used when consumers purchase Gift Passes from a Landing page. The Web API forwards information of the purchased pass, along with the buyer and receiver's details. In addition, the Web aPI integrates with the Payment Gateway service and request to load their payment form for an easy payment processing. To avoid any issues, it's vital to check the Payment Gateway service's mandatory information requirements, such as the buyer's email, phone, and address information, before triggering the Web API.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async comCrmPaymentFormSelfServiceResourceGeneratePassPaymentForm(
    security:
      operations.ComCrmPaymentFormSelfServiceResourceGeneratePassPaymentFormSecurity,
    request?:
      | operations.ComCrmPaymentFormSelfServiceResourceGeneratePassPaymentFormRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<
    operations.ComCrmPaymentFormSelfServiceResourceGeneratePassPaymentFormResponse
  > {
    return unwrapAsync(
      paymentFormsComCrmPaymentFormSelfServiceResourceGeneratePassPaymentForm(
        this,
        security,
        request,
        options,
      ),
    );
  }

  /**
   * Payment Form
   *
   * @remarks
   * Web API used when consumers want to perform a payment using a card on file. It's vital to study the Payment Gateway's required contact information. Make sure that this required information is already specified for contacts that use this form to make payments/top-ups since this Web API does not forward/includes such info in the request!
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async comCrmPaymentFormSelfServiceResourceGeneratePaymentForm(
    security:
      operations.ComCrmPaymentFormSelfServiceResourceGeneratePaymentFormSecurity,
    request:
      operations.ComCrmPaymentFormSelfServiceResourceGeneratePaymentFormRequest,
    options?: RequestOptions,
  ): Promise<
    operations.ComCrmPaymentFormSelfServiceResourceGeneratePaymentFormResponse
  > {
    return unwrapAsync(
      paymentFormsComCrmPaymentFormSelfServiceResourceGeneratePaymentForm(
        this,
        security,
        request,
        options,
      ),
    );
  }
}
