/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9a4fc96b490e
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the crmcom SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx contactAccountsComCrmAccountSelfServiceResourceGetSingle.example.ts
 */

import { Crmcom } from "crmcom";

const crmcom = new Crmcom({
  authorizationSelfService: process.env["CRM_AUTHORIZATION_SELF_SERVICE"] ?? "",
});

async function main() {
  const result = await crmcom.contactAccounts
    .comCrmAccountSelfServiceResourceGetSingle({
      id: "CAD1E31269B76D7A65ACCE45B2E68DFD",
    });

  console.log(result);
}

main().catch(console.error);
