/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * How to send the validation code
 */
export const ComCrmContactSelfServiceResourceRequestOTPMethod = {
  Sms: "SMS",
  Email: "EMAIL",
} as const;
/**
 * How to send the validation code
 */
export type ComCrmContactSelfServiceResourceRequestOTPMethod = ClosedEnum<
  typeof ComCrmContactSelfServiceResourceRequestOTPMethod
>;

/**
 * The predetermined information that will be used to identify the contact
 */
export const Name = {
  AuthOtp: "AUTH_OTP",
  Birthdate: "BIRTHDATE",
  Passport: "PASSPORT",
  Card: "CARD",
  Phone: "PHONE",
  Email: "EMAIL",
  IdNumber: "ID_NUMBER",
  LoyaltyIdentifier: "LOYALTY_IDENTIFIER",
  GiftPass: "GIFT_PASS",
  StatutoryId: "STATUTORY_ID",
} as const;
/**
 * The predetermined information that will be used to identify the contact
 */
export type Name = ClosedEnum<typeof Name>;

/**
 * The contact’s phone country code
 */
export const ComCrmContactSelfServiceResourceRequestOTPCountryCode = {
  Abw: "ABW",
  Afg: "AFG",
  Ago: "AGO",
  Aia: "AIA",
  Ala: "ALA",
  Alb: "ALB",
  And: "AND",
  Ant: "ANT",
  Are: "ARE",
  Arg: "ARG",
  Arm: "ARM",
  Asm: "ASM",
  Ata: "ATA",
  Atf: "ATF",
  Atg: "ATG",
  Aus: "AUS",
  Aut: "AUT",
  Aze: "AZE",
  Bdi: "BDI",
  Bel: "BEL",
  Ben: "BEN",
  Bes: "BES",
  Bfa: "BFA",
  Bgd: "BGD",
  Bgr: "BGR",
  Bhr: "BHR",
  Bhs: "BHS",
  Bih: "BIH",
  Blm: "BLM",
  Blr: "BLR",
  Blz: "BLZ",
  Bmu: "BMU",
  Bol: "BOL",
  Bra: "BRA",
  Brb: "BRB",
  Brn: "BRN",
  Btn: "BTN",
  Bvt: "BVT",
  Bwa: "BWA",
  Caf: "CAF",
  Can: "CAN",
  Cck: "CCK",
  Che: "CHE",
  Chl: "CHL",
  Chn: "CHN",
  Civ: "CIV",
  Cmr: "CMR",
  Cod: "COD",
  Cog: "COG",
  Cok: "COK",
  Col: "COL",
  Com: "COM",
  Cpv: "CPV",
  Cri: "CRI",
  Cub: "CUB",
  Cuw: "CUW",
  Cxr: "CXR",
  Cym: "CYM",
  Cyp: "CYP",
  Cze: "CZE",
  Deu: "DEU",
  Dji: "DJI",
  Dma: "DMA",
  Dnk: "DNK",
  Dom: "DOM",
  Dza: "DZA",
  Ecu: "ECU",
  Egy: "EGY",
  Eri: "ERI",
  Esh: "ESH",
  Esp: "ESP",
  Est: "EST",
  Eth: "ETH",
  Fin: "FIN",
  Fji: "FJI",
  Flk: "FLK",
  Fra: "FRA",
  Fro: "FRO",
  Fsm: "FSM",
  Gab: "GAB",
  Gbr: "GBR",
  Geo: "GEO",
  Ggy: "GGY",
  Gha: "GHA",
  Gib: "GIB",
  Gin: "GIN",
  Glp: "GLP",
  Gmb: "GMB",
  Gnb: "GNB",
  Gnq: "GNQ",
  Grc: "GRC",
  Grd: "GRD",
  Grl: "GRL",
  Gtm: "GTM",
  Guf: "GUF",
  Gum: "GUM",
  Guy: "GUY",
  Hkg: "HKG",
  Hmd: "HMD",
  Hnd: "HND",
  Hrv: "HRV",
  Hti: "HTI",
  Hun: "HUN",
  Idn: "IDN",
  Imn: "IMN",
  Ind: "IND",
  Iot: "IOT",
  Irl: "IRL",
  Irn: "IRN",
  Irq: "IRQ",
  Isl: "ISL",
  Isr: "ISR",
  Ita: "ITA",
  Jam: "JAM",
  Jey: "JEY",
  Jor: "JOR",
  Jpn: "JPN",
  Kaz: "KAZ",
  Ken: "KEN",
  Kgz: "KGZ",
  Khm: "KHM",
  Kir: "KIR",
  Kna: "KNA",
  Kor: "KOR",
  Kwt: "KWT",
  Lao: "LAO",
  Lbn: "LBN",
  Lbr: "LBR",
  Lby: "LBY",
  Lca: "LCA",
  Lie: "LIE",
  Lka: "LKA",
  Lso: "LSO",
  Ltu: "LTU",
  Lux: "LUX",
  Lva: "LVA",
  Mac: "MAC",
  Maf: "MAF",
  Mar: "MAR",
  Mco: "MCO",
  Mda: "MDA",
  Mdg: "MDG",
  Mdv: "MDV",
  Mex: "MEX",
  Mhl: "MHL",
  Mkd: "MKD",
  Mli: "MLI",
  Mlt: "MLT",
  Mmr: "MMR",
  Mne: "MNE",
  Mng: "MNG",
  Mnp: "MNP",
  Moz: "MOZ",
  Mrt: "MRT",
  Msr: "MSR",
  Mtq: "MTQ",
  Mus: "MUS",
  Mwi: "MWI",
  Mys: "MYS",
  Myt: "MYT",
  Nam: "NAM",
  Ncl: "NCL",
  Ner: "NER",
  Nfk: "NFK",
  Nga: "NGA",
  Nic: "NIC",
  Niu: "NIU",
  Nld: "NLD",
  Nor: "NOR",
  Npl: "NPL",
  Nru: "NRU",
  Nzl: "NZL",
  Omn: "OMN",
  Pak: "PAK",
  Pan: "PAN",
  Pcn: "PCN",
  Per: "PER",
  Phl: "PHL",
  Plw: "PLW",
  Png: "PNG",
  Pol: "POL",
  Pri: "PRI",
  Prk: "PRK",
  Prt: "PRT",
  Pry: "PRY",
  Pse: "PSE",
  Pyf: "PYF",
  Qat: "QAT",
  Reu: "REU",
  Rks: "RKS",
  Rou: "ROU",
  Rus: "RUS",
  Rwa: "RWA",
  Sau: "SAU",
  Sdn: "SDN",
  Sen: "SEN",
  Sgp: "SGP",
  Sgs: "SGS",
  Shn: "SHN",
  Sjm: "SJM",
  Slb: "SLB",
  Sle: "SLE",
  Slv: "SLV",
  Smr: "SMR",
  Som: "SOM",
  Spm: "SPM",
  Srb: "SRB",
  Ssd: "SSD",
  Stp: "STP",
  Sur: "SUR",
  Svk: "SVK",
  Svn: "SVN",
  Swe: "SWE",
  Swz: "SWZ",
  Sxm: "SXM",
  Syc: "SYC",
  Syr: "SYR",
  Tca: "TCA",
  Tcd: "TCD",
  Tgo: "TGO",
  Tha: "THA",
  Tjk: "TJK",
  Tkl: "TKL",
  Tkm: "TKM",
  Tls: "TLS",
  Ton: "TON",
  Tto: "TTO",
  Tun: "TUN",
  Tur: "TUR",
  Tuv: "TUV",
  Twn: "TWN",
  Tza: "TZA",
  Uga: "UGA",
  Ukr: "UKR",
  Umi: "UMI",
  Ury: "URY",
  Usa: "USA",
  Uzb: "UZB",
  Vat: "VAT",
  Vct: "VCT",
  Ven: "VEN",
  Vgb: "VGB",
  Vir: "VIR",
  Vnm: "VNM",
  Vut: "VUT",
  Wlf: "WLF",
  Wsm: "WSM",
  Yem: "YEM",
  Zaf: "ZAF",
  Zmb: "ZMB",
  Zwe: "ZWE",
} as const;
/**
 * The contact’s phone country code
 */
export type ComCrmContactSelfServiceResourceRequestOTPCountryCode = ClosedEnum<
  typeof ComCrmContactSelfServiceResourceRequestOTPCountryCode
>;

/**
 * The contact’s phone
 */
export type ComCrmContactSelfServiceResourceRequestOTPPhone = {
  /**
   * The contact’s phone number
   */
  number: string;
  /**
   * The contact’s phone country code
   */
  countryCode: ComCrmContactSelfServiceResourceRequestOTPCountryCode;
};

/**
 * The gift pass information to check (applicable only if type is “GIFT_PASS”)
 */
export type GiftPass = {
  /**
   * The email address that will receive the one-time-password (email or phone must be provided)
   */
  email?: string | null | undefined;
  /**
   * The contact’s phone
   */
  phone?: ComCrmContactSelfServiceResourceRequestOTPPhone | null | undefined;
  /**
   * The gift pass pin (pin or last_spend_amount must be provided)
   */
  pin?: string | null | undefined;
  /**
   * The last spend amount performed, semi-optional - either pin or last_spend_amount must be provided
   */
  lastSpendAmount?: number | null | undefined;
};

export type Credential = {
  /**
   * The predetermined information that will be used to identify the contact
   */
  name: Name;
  /**
   * The value of the credential to check
   */
  value: string;
  /**
   * The gift pass information to check (applicable only if type is “GIFT_PASS”)
   */
  giftPass?: GiftPass | undefined;
};

export type ComCrmContactSelfServiceResourceRequestOTPRequestBody = {
  /**
   * How to send the validation code
   */
  method: ComCrmContactSelfServiceResourceRequestOTPMethod;
  /**
   * Defines how a contact will be identified
   */
  credentials: Array<Credential>;
};

export type ComCrmContactSelfServiceResourceRequestOTPRequest = {
  apiKey?: string | undefined;
  body?: ComCrmContactSelfServiceResourceRequestOTPRequestBody | undefined;
};

/**
 * OK
 */
export type ComCrmContactSelfServiceResourceRequestOTPResponse = {
  /**
   * The obfuscated value of the email or sms used to send the otp
   */
  obfuscatedValue?: string | undefined;
  /**
   * The one time password authentication identifier
   */
  authOtp?: string | undefined;
};

/** @internal */
export const ComCrmContactSelfServiceResourceRequestOTPMethod$outboundSchema:
  z.ZodMiniEnum<typeof ComCrmContactSelfServiceResourceRequestOTPMethod> = z
    .enum(ComCrmContactSelfServiceResourceRequestOTPMethod);

/** @internal */
export const Name$outboundSchema: z.ZodMiniEnum<typeof Name> = z.enum(Name);

/** @internal */
export const ComCrmContactSelfServiceResourceRequestOTPCountryCode$outboundSchema:
  z.ZodMiniEnum<typeof ComCrmContactSelfServiceResourceRequestOTPCountryCode> =
    z.enum(ComCrmContactSelfServiceResourceRequestOTPCountryCode);

/** @internal */
export type ComCrmContactSelfServiceResourceRequestOTPPhone$Outbound = {
  number: string;
  country_code: string;
};

/** @internal */
export const ComCrmContactSelfServiceResourceRequestOTPPhone$outboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceRequestOTPPhone$Outbound,
    ComCrmContactSelfServiceResourceRequestOTPPhone
  > = z.pipe(
    z.object({
      number: z.string(),
      countryCode:
        ComCrmContactSelfServiceResourceRequestOTPCountryCode$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        countryCode: "country_code",
      });
    }),
  );

export function comCrmContactSelfServiceResourceRequestOTPPhoneToJSON(
  comCrmContactSelfServiceResourceRequestOTPPhone:
    ComCrmContactSelfServiceResourceRequestOTPPhone,
): string {
  return JSON.stringify(
    ComCrmContactSelfServiceResourceRequestOTPPhone$outboundSchema.parse(
      comCrmContactSelfServiceResourceRequestOTPPhone,
    ),
  );
}

/** @internal */
export type GiftPass$Outbound = {
  email?: string | null | undefined;
  phone?:
    | ComCrmContactSelfServiceResourceRequestOTPPhone$Outbound
    | null
    | undefined;
  pin?: string | null | undefined;
  last_spend_amount?: number | null | undefined;
};

/** @internal */
export const GiftPass$outboundSchema: z.ZodMiniType<
  GiftPass$Outbound,
  GiftPass
> = z.pipe(
  z.object({
    email: z.optional(z.nullable(z.string())),
    phone: z.optional(z.nullable(z.lazy(() =>
      ComCrmContactSelfServiceResourceRequestOTPPhone$outboundSchema
    ))),
    pin: z.optional(z.nullable(z.string())),
    lastSpendAmount: z.optional(z.nullable(z.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      lastSpendAmount: "last_spend_amount",
    });
  }),
);

export function giftPassToJSON(giftPass: GiftPass): string {
  return JSON.stringify(GiftPass$outboundSchema.parse(giftPass));
}

/** @internal */
export type Credential$Outbound = {
  name: string;
  value: string;
  gift_pass?: GiftPass$Outbound | undefined;
};

/** @internal */
export const Credential$outboundSchema: z.ZodMiniType<
  Credential$Outbound,
  Credential
> = z.pipe(
  z.object({
    name: Name$outboundSchema,
    value: z.string(),
    giftPass: z.optional(z.lazy(() => GiftPass$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      giftPass: "gift_pass",
    });
  }),
);

export function credentialToJSON(credential: Credential): string {
  return JSON.stringify(Credential$outboundSchema.parse(credential));
}

/** @internal */
export type ComCrmContactSelfServiceResourceRequestOTPRequestBody$Outbound = {
  method: string;
  credentials: Array<Credential$Outbound>;
};

/** @internal */
export const ComCrmContactSelfServiceResourceRequestOTPRequestBody$outboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceRequestOTPRequestBody$Outbound,
    ComCrmContactSelfServiceResourceRequestOTPRequestBody
  > = z.object({
    method: ComCrmContactSelfServiceResourceRequestOTPMethod$outboundSchema,
    credentials: z.array(z.lazy(() => Credential$outboundSchema)),
  });

export function comCrmContactSelfServiceResourceRequestOTPRequestBodyToJSON(
  comCrmContactSelfServiceResourceRequestOTPRequestBody:
    ComCrmContactSelfServiceResourceRequestOTPRequestBody,
): string {
  return JSON.stringify(
    ComCrmContactSelfServiceResourceRequestOTPRequestBody$outboundSchema.parse(
      comCrmContactSelfServiceResourceRequestOTPRequestBody,
    ),
  );
}

/** @internal */
export type ComCrmContactSelfServiceResourceRequestOTPRequest$Outbound = {
  api_key?: string | undefined;
  body?:
    | ComCrmContactSelfServiceResourceRequestOTPRequestBody$Outbound
    | undefined;
};

/** @internal */
export const ComCrmContactSelfServiceResourceRequestOTPRequest$outboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceRequestOTPRequest$Outbound,
    ComCrmContactSelfServiceResourceRequestOTPRequest
  > = z.pipe(
    z.object({
      apiKey: z.optional(z.string()),
      body: z.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceRequestOTPRequestBody$outboundSchema
      )),
    }),
    z.transform((v) => {
      return remap$(v, {
        apiKey: "api_key",
      });
    }),
  );

export function comCrmContactSelfServiceResourceRequestOTPRequestToJSON(
  comCrmContactSelfServiceResourceRequestOTPRequest:
    ComCrmContactSelfServiceResourceRequestOTPRequest,
): string {
  return JSON.stringify(
    ComCrmContactSelfServiceResourceRequestOTPRequest$outboundSchema.parse(
      comCrmContactSelfServiceResourceRequestOTPRequest,
    ),
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceRequestOTPResponse$inboundSchema:
  z.ZodMiniType<ComCrmContactSelfServiceResourceRequestOTPResponse, unknown> = z
    .pipe(
      z.object({
        obfuscated_value: types.optional(types.string()),
        auth_otp: types.optional(types.string()),
      }),
      z.transform((v) => {
        return remap$(v, {
          "obfuscated_value": "obfuscatedValue",
          "auth_otp": "authOtp",
        });
      }),
    );

export function comCrmContactSelfServiceResourceRequestOTPResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceRequestOTPResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceRequestOTPResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmContactSelfServiceResourceRequestOTPResponse' from JSON`,
  );
}
