/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3d149cde9bc8
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ComCrmContactSelfServiceResourceGetContactRelationshipRequest = {
  /**
   * The contact (identifier) whose community will be retrieved
   */
  id: string;
  /**
   * The community person (identifier) that will be retrieved
   */
  relationshipId: string;
  /**
   * Defaults to false. If set to true, the member’s remaining accumulated amounts are included in the response.
   */
  includeRemainingAllowance?: boolean | undefined;
};

/**
 * The community relation that the contact has
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipRelation = {
  /**
   * The community relation identifier
   */
  id?: string | undefined;
  /**
   * The community relation name
   */
  name?: string | undefined;
};

export const ComCrmContactSelfServiceResourceGetContactRelationshipPermission =
  {
    ContactManagement: "CONTACT_MANAGEMENT",
    ServiceRequestsManagement: "SERVICE_REQUESTS_MANAGEMENT",
    OrdersManagement: "ORDERS_MANAGEMENT",
    FullAccess: "FULL_ACCESS",
  } as const;
export type ComCrmContactSelfServiceResourceGetContactRelationshipPermission =
  OpenEnum<
    typeof ComCrmContactSelfServiceResourceGetContactRelationshipPermission
  >;

/**
 * A list of custom fields whose values can be set when creating or updating entities
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipCustomField =
  {
    /**
     * The custom field’s unique key
     */
    key?: string | undefined;
    /**
     * The custom field’s value
     */
    value?: string | undefined;
  };

export type ComCrmContactSelfServiceResourceGetContactRelationshipDevice = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
  /**
   * The device serial number
   */
  serialNumber?: string | undefined;
  /**
   * The device custom fields
   */
  customFields?:
    | Array<ComCrmContactSelfServiceResourceGetContactRelationshipCustomField>
    | undefined;
};

/**
 * The phone country code
 */
export const ComCrmContactSelfServiceResourceGetContactRelationshipCountryCode =
  {
    Abw: "ABW",
    Afg: "AFG",
    Ago: "AGO",
    Aia: "AIA",
    Ala: "ALA",
    Alb: "ALB",
    And: "AND",
    Ant: "ANT",
    Are: "ARE",
    Arg: "ARG",
    Arm: "ARM",
    Asm: "ASM",
    Ata: "ATA",
    Atf: "ATF",
    Atg: "ATG",
    Aus: "AUS",
    Aut: "AUT",
    Aze: "AZE",
    Bdi: "BDI",
    Bel: "BEL",
    Ben: "BEN",
    Bes: "BES",
    Bfa: "BFA",
    Bgd: "BGD",
    Bgr: "BGR",
    Bhr: "BHR",
    Bhs: "BHS",
    Bih: "BIH",
    Blm: "BLM",
    Blr: "BLR",
    Blz: "BLZ",
    Bmu: "BMU",
    Bol: "BOL",
    Bra: "BRA",
    Brb: "BRB",
    Brn: "BRN",
    Btn: "BTN",
    Bvt: "BVT",
    Bwa: "BWA",
    Caf: "CAF",
    Can: "CAN",
    Cck: "CCK",
    Che: "CHE",
    Chl: "CHL",
    Chn: "CHN",
    Civ: "CIV",
    Cmr: "CMR",
    Cod: "COD",
    Cog: "COG",
    Cok: "COK",
    Col: "COL",
    Com: "COM",
    Cpv: "CPV",
    Cri: "CRI",
    Cub: "CUB",
    Cuw: "CUW",
    Cxr: "CXR",
    Cym: "CYM",
    Cyp: "CYP",
    Cze: "CZE",
    Deu: "DEU",
    Dji: "DJI",
    Dma: "DMA",
    Dnk: "DNK",
    Dom: "DOM",
    Dza: "DZA",
    Ecu: "ECU",
    Egy: "EGY",
    Eri: "ERI",
    Esh: "ESH",
    Esp: "ESP",
    Est: "EST",
    Eth: "ETH",
    Fin: "FIN",
    Fji: "FJI",
    Flk: "FLK",
    Fra: "FRA",
    Fro: "FRO",
    Fsm: "FSM",
    Gab: "GAB",
    Gbr: "GBR",
    Geo: "GEO",
    Ggy: "GGY",
    Gha: "GHA",
    Gib: "GIB",
    Gin: "GIN",
    Glp: "GLP",
    Gmb: "GMB",
    Gnb: "GNB",
    Gnq: "GNQ",
    Grc: "GRC",
    Grd: "GRD",
    Grl: "GRL",
    Gtm: "GTM",
    Guf: "GUF",
    Gum: "GUM",
    Guy: "GUY",
    Hkg: "HKG",
    Hmd: "HMD",
    Hnd: "HND",
    Hrv: "HRV",
    Hti: "HTI",
    Hun: "HUN",
    Idn: "IDN",
    Imn: "IMN",
    Ind: "IND",
    Iot: "IOT",
    Irl: "IRL",
    Irn: "IRN",
    Irq: "IRQ",
    Isl: "ISL",
    Isr: "ISR",
    Ita: "ITA",
    Jam: "JAM",
    Jey: "JEY",
    Jor: "JOR",
    Jpn: "JPN",
    Kaz: "KAZ",
    Ken: "KEN",
    Kgz: "KGZ",
    Khm: "KHM",
    Kir: "KIR",
    Kna: "KNA",
    Kor: "KOR",
    Kwt: "KWT",
    Lao: "LAO",
    Lbn: "LBN",
    Lbr: "LBR",
    Lby: "LBY",
    Lca: "LCA",
    Lie: "LIE",
    Lka: "LKA",
    Lso: "LSO",
    Ltu: "LTU",
    Lux: "LUX",
    Lva: "LVA",
    Mac: "MAC",
    Maf: "MAF",
    Mar: "MAR",
    Mco: "MCO",
    Mda: "MDA",
    Mdg: "MDG",
    Mdv: "MDV",
    Mex: "MEX",
    Mhl: "MHL",
    Mkd: "MKD",
    Mli: "MLI",
    Mlt: "MLT",
    Mmr: "MMR",
    Mne: "MNE",
    Mng: "MNG",
    Mnp: "MNP",
    Moz: "MOZ",
    Mrt: "MRT",
    Msr: "MSR",
    Mtq: "MTQ",
    Mus: "MUS",
    Mwi: "MWI",
    Mys: "MYS",
    Myt: "MYT",
    Nam: "NAM",
    Ncl: "NCL",
    Ner: "NER",
    Nfk: "NFK",
    Nga: "NGA",
    Nic: "NIC",
    Niu: "NIU",
    Nld: "NLD",
    Nor: "NOR",
    Npl: "NPL",
    Nru: "NRU",
    Nzl: "NZL",
    Omn: "OMN",
    Pak: "PAK",
    Pan: "PAN",
    Pcn: "PCN",
    Per: "PER",
    Phl: "PHL",
    Plw: "PLW",
    Png: "PNG",
    Pol: "POL",
    Pri: "PRI",
    Prk: "PRK",
    Prt: "PRT",
    Pry: "PRY",
    Pse: "PSE",
    Pyf: "PYF",
    Qat: "QAT",
    Reu: "REU",
    Rks: "RKS",
    Rou: "ROU",
    Rus: "RUS",
    Rwa: "RWA",
    Sau: "SAU",
    Sdn: "SDN",
    Sen: "SEN",
    Sgp: "SGP",
    Sgs: "SGS",
    Shn: "SHN",
    Sjm: "SJM",
    Slb: "SLB",
    Sle: "SLE",
    Slv: "SLV",
    Smr: "SMR",
    Som: "SOM",
    Spm: "SPM",
    Srb: "SRB",
    Ssd: "SSD",
    Stp: "STP",
    Sur: "SUR",
    Svk: "SVK",
    Svn: "SVN",
    Swe: "SWE",
    Swz: "SWZ",
    Sxm: "SXM",
    Syc: "SYC",
    Syr: "SYR",
    Tca: "TCA",
    Tcd: "TCD",
    Tgo: "TGO",
    Tha: "THA",
    Tjk: "TJK",
    Tkl: "TKL",
    Tkm: "TKM",
    Tls: "TLS",
    Ton: "TON",
    Tto: "TTO",
    Tun: "TUN",
    Tur: "TUR",
    Tuv: "TUV",
    Twn: "TWN",
    Tza: "TZA",
    Uga: "UGA",
    Ukr: "UKR",
    Umi: "UMI",
    Ury: "URY",
    Usa: "USA",
    Uzb: "UZB",
    Vat: "VAT",
    Vct: "VCT",
    Ven: "VEN",
    Vgb: "VGB",
    Vir: "VIR",
    Vnm: "VNM",
    Vut: "VUT",
    Wlf: "WLF",
    Wsm: "WSM",
    Yem: "YEM",
    Zaf: "ZAF",
    Zmb: "ZMB",
    Zwe: "ZWE",
  } as const;
/**
 * The phone country code
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipCountryCode =
  OpenEnum<
    typeof ComCrmContactSelfServiceResourceGetContactRelationshipCountryCode
  >;

/**
 * The contact phone number
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipPhone = {
  /**
   * The phone country code
   */
  countryCode?:
    | ComCrmContactSelfServiceResourceGetContactRelationshipCountryCode
    | undefined;
  /**
   * The phone number.
   */
  number?: string | undefined;
};

/**
 * The contact's wallet details
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipWallet = {
  /**
   * The wallet identifier
   */
  id?: string | undefined;
};

/**
 * The contact (parent or member in the respective community)
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipContact = {
  /**
   * The contact identifier
   */
  id?: string | undefined;
  /**
   * The contact first name
   */
  firstName?: string | undefined;
  /**
   * The contact last name
   */
  lastName?: string | undefined;
  /**
   * The contact phone number
   */
  phone?:
    | ComCrmContactSelfServiceResourceGetContactRelationshipPhone
    | undefined;
  /**
   * The contact email address
   */
  email?: string | undefined;
  /**
   * The contact's wallet details
   */
  wallet?:
    | ComCrmContactSelfServiceResourceGetContactRelationshipWallet
    | undefined;
};

export type ComCrmContactSelfServiceResourceGetContactRelationshipWalletSharingCommercePool =
  {
    /**
     * The commerce pool identifier
     */
    id?: string | undefined;
    /**
     * The commerce pool name
     */
    name?: string | undefined;
    /**
     * The commerce pool description
     */
    description?: string | undefined;
  };

/**
 * Defines whether money requests will require an acceptance from the community owner or will be automatically applied
 */
export const ComCrmContactSelfServiceResourceGetContactRelationshipMethod = {
  Auto: "AUTO",
  Manual: "MANUAL",
} as const;
/**
 * Defines whether money requests will require an acceptance from the community owner or will be automatically applied
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipMethod =
  OpenEnum<typeof ComCrmContactSelfServiceResourceGetContactRelationshipMethod>;

/**
 * Defines whether the community person will be able to use/request money from community owner wallet
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipWalletSharing =
  {
    /**
     * Defines if wallet sharing is enabled
     */
    isEnabled?: boolean | undefined;
    /**
     * Defines the commerce pools that the community person is allowed to use/transfer wallet money
     */
    commercePools?:
      | Array<
        ComCrmContactSelfServiceResourceGetContactRelationshipWalletSharingCommercePool
      >
      | undefined;
    /**
     * Defines whether money requests will require an acceptance from the community owner or will be automatically applied
     */
    method?:
      | ComCrmContactSelfServiceResourceGetContactRelationshipMethod
      | undefined;
    /**
     * Defines the maximum amount that can be transferred per calendar month
     */
    maxAmount?: number | undefined;
    /**
     * Defines the remaining amount that can be transferred per calendar month
     */
    remainingAmount?: number | undefined;
  };

/**
 * How much can be consumed
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipAccumulatedAllowanceCashLimits =
  {
    /**
     * Allowance per transaction
     */
    perTransaction?: number | undefined;
    /**
     * Allowance per day
     */
    perDay?: number | undefined;
    /**
     * Allowance per billing cycle
     */
    perBillingCycle?: number | undefined;
  };

/**
 * Remaining allowance in amount of money
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipRemainingCash =
  {
    /**
     * Allowance per transaction
     */
    perTransaction?: number | undefined;
    /**
     * Allowance per day
     */
    perDay?: number | undefined;
    /**
     * Allowance per billing cycle
     */
    perBillingCycle?: number | undefined;
  };

/**
 * The community's accumulated cash allowance, i.e. how much can be consumed among all products which are consumed through the community. This allowance is defined only in amount of money and it's evaluated based on the usage's rating (how much it costs)
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipAccumulatedAllowance =
  {
    /**
     * Currency code based on ISO 4217 standard
     */
    currency?: string | undefined;
    /**
     * How much can be consumed
     */
    cashLimits?:
      | ComCrmContactSelfServiceResourceGetContactRelationshipAccumulatedAllowanceCashLimits
      | undefined;
    /**
     * Remaining allowance in amount of money
     */
    remainingCash?:
      | ComCrmContactSelfServiceResourceGetContactRelationshipRemainingCash
      | undefined;
  };

/**
 * Product setting. Allow usage to either a specific product or to products of a specific type or to products of a specific family or to products of a specific category
 */
export const ComCrmContactSelfServiceResourceGetContactRelationshipItemType = {
  Product: "PRODUCT",
  Type: "TYPE",
  Family: "FAMILY",
  Category: "CATEGORY",
} as const;
/**
 * Product setting. Allow usage to either a specific product or to products of a specific type or to products of a specific family or to products of a specific category
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipItemType =
  OpenEnum<
    typeof ComCrmContactSelfServiceResourceGetContactRelationshipItemType
  >;

/**
 * Measurement unit. Applicable only when a specific usage product is included in the allowance
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipMeasurementUnit =
  {
    /**
     * Measurement unit name
     */
    name?: string | undefined;
    /**
     * Measurement unit display name
     */
    displayName?: string | undefined;
  };

/**
 * How much rated usage can be consumed
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipProductsAllowanceCashLimits =
  {
    /**
     * Allowance per transaction
     */
    perTransaction?: number | undefined;
    /**
     * Allowance per day
     */
    perDay?: number | undefined;
    /**
     * Allowance per billing cycle
     */
    perBillingCycle?: number | undefined;
  };

/**
 * Actual allowed and remaining usage (based on measurement units)
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipUsageLimits =
  {
    /**
     * Allowance per transaction
     */
    perTransaction?: number | undefined;
    /**
     * Allowance per day
     */
    perDay?: number | undefined;
    /**
     * Allowance per billing cycle
     */
    perBillingCycle?: number | undefined;
  };

export type ComCrmContactSelfServiceResourceGetContactRelationshipProductsAllowance =
  {
    /**
     * The entity identifier
     */
    id?: string | undefined;
    groupId?: string | undefined;
    /**
     * Currency code based on ISO 4217 standard
     */
    currency?: string | undefined;
    /**
     * Product setting. Allow usage to either a specific product or to products of a specific type or to products of a specific family or to products of a specific category
     */
    itemType?:
      | ComCrmContactSelfServiceResourceGetContactRelationshipItemType
      | undefined;
    /**
     * The identifier of the item (the product or the product type or the product family or the product category)
     */
    itemId?: string | undefined;
    /**
     * The product name or product type name or product family name or product category name depending on item_type
     */
    name?: string | undefined;
    sku?: string | undefined;
    /**
     * Measurement unit. Applicable only when a specific usage product is included in the allowance
     */
    measurementUnit?:
      | ComCrmContactSelfServiceResourceGetContactRelationshipMeasurementUnit
      | undefined;
    /**
     * How much rated usage can be consumed
     */
    cashLimits?:
      | ComCrmContactSelfServiceResourceGetContactRelationshipProductsAllowanceCashLimits
      | undefined;
    /**
     * Actual allowed and remaining usage (based on measurement units)
     */
    usageLimits?:
      | ComCrmContactSelfServiceResourceGetContactRelationshipUsageLimits
      | undefined;
  };

export type ComCrmContactSelfServiceResourceGetContactRelationshipOrganisation =
  {
    /**
     * The entity identifier
     */
    id?: string | undefined;
    /**
     * The entity name
     */
    name?: string | undefined;
  };

/**
 * Defines the usage allowance
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipUsageAllowance =
  {
    /**
     * The community's accumulated cash allowance, i.e. how much can be consumed among all products which are consumed through the community. This allowance is defined only in amount of money and it's evaluated based on the usage's rating (how much it costs)
     */
    accumulatedAllowance?:
      | ComCrmContactSelfServiceResourceGetContactRelationshipAccumulatedAllowance
      | undefined;
    /**
     * If set to true, the member has the same usage allowance per product as the owner’s termed/one-time service.
     */
    sameAsOwner?: boolean | undefined;
    /**
     * If set to true, the member has usage allowance per item
     */
    hasProductsAllowance?: boolean | undefined;
    /**
     * List of items which can be consumed through the community. This set of items includes usage and non-traceable physical goods. If nothing is specified, then usage is allowed among all usage services/non-traceable physical goods that the business is selling
     */
    productsAllowance?:
      | Array<
        ComCrmContactSelfServiceResourceGetContactRelationshipProductsAllowance
      >
      | undefined;
    /**
     * The allowed organisations to consume allowance
     */
    organisations?:
      | Array<
        ComCrmContactSelfServiceResourceGetContactRelationshipOrganisation
      >
      | undefined;
  };

/**
 * The community member’s relation state. A person is considered as a valid community person only after they accept the invitation to join the community.
 */
export const ComCrmContactSelfServiceResourceGetContactRelationshipState = {
  Pending: "PENDING",
  Accepted: "ACCEPTED",
  Rejected: "REJECTED",
} as const;
/**
 * The community member’s relation state. A person is considered as a valid community person only after they accept the invitation to join the community.
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipState =
  OpenEnum<typeof ComCrmContactSelfServiceResourceGetContactRelationshipState>;

/**
 * The currency code used for the transfer
 */
export const ComCrmContactSelfServiceResourceGetContactRelationshipCurrencyCode =
  {
    Aed: "AED",
    Afn: "AFN",
    All: "ALL",
    Amd: "AMD",
    Ang: "ANG",
    Aoa: "AOA",
    Ars: "ARS",
    Aud: "AUD",
    Awg: "AWG",
    Azn: "AZN",
    Bam: "BAM",
    Bbd: "BBD",
    Bdt: "BDT",
    Bgn: "BGN",
    Bhd: "BHD",
    Bif: "BIF",
    Bmd: "BMD",
    Bnd: "BND",
    Bob: "BOB",
    Brl: "BRL",
    Bsd: "BSD",
    Btn: "BTN",
    Bwp: "BWP",
    Byr: "BYR",
    Bzd: "BZD",
    Cad: "CAD",
    Cdf: "CDF",
    Chf: "CHF",
    Clp: "CLP",
    Cny: "CNY",
    Cop: "COP",
    Crc: "CRC",
    Cuc: "CUC",
    Cup: "CUP",
    Cve: "CVE",
    Czk: "CZK",
    Djf: "DJF",
    Dkk: "DKK",
    Dop: "DOP",
    Dzd: "DZD",
    Egp: "EGP",
    Ern: "ERN",
    Etb: "ETB",
    Eur: "EUR",
    Fjd: "FJD",
    Fkp: "FKP",
    Gbp: "GBP",
    Gel: "GEL",
    Ggp: "GGP",
    Ghs: "GHS",
    Gip: "GIP",
    Gmd: "GMD",
    Gnf: "GNF",
    Gtq: "GTQ",
    Gyd: "GYD",
    Hkd: "HKD",
    Hnl: "HNL",
    Hrk: "HRK",
    Htg: "HTG",
    Huf: "HUF",
    Idr: "IDR",
    Ils: "ILS",
    Imp: "IMP",
    Inr: "INR",
    Iqd: "IQD",
    Irr: "IRR",
    Isk: "ISK",
    Jep: "JEP",
    Jmd: "JMD",
    Jod: "JOD",
    Jpy: "JPY",
    Kes: "KES",
    Kgs: "KGS",
    Khr: "KHR",
    Kmf: "KMF",
    Kpw: "KPW",
    Krw: "KRW",
    Kwd: "KWD",
    Kyd: "KYD",
    Kzt: "KZT",
    Lak: "LAK",
    Lbp: "LBP",
    Lkr: "LKR",
    Lrd: "LRD",
    Lsl: "LSL",
    Lyd: "LYD",
    Mad: "MAD",
    Mdl: "MDL",
    Mga: "MGA",
    Mkd: "MKD",
    Mmk: "MMK",
    Mnt: "MNT",
    Mop: "MOP",
    Mro: "MRO",
    Mur: "MUR",
    Mvr: "MVR",
    Mwk: "MWK",
    Mxn: "MXN",
    Myr: "MYR",
    Mzn: "MZN",
    Nad: "NAD",
    Ngn: "NGN",
    Nio: "NIO",
    Nok: "NOK",
    Npr: "NPR",
    Nzd: "NZD",
    Omr: "OMR",
    Pab: "PAB",
    Pen: "PEN",
    Pgk: "PGK",
    Php: "PHP",
    Pkr: "PKR",
    Pln: "PLN",
    Pyg: "PYG",
    Qar: "QAR",
    Ron: "RON",
    Rsd: "RSD",
    Rub: "RUB",
    Rwf: "RWF",
    Sar: "SAR",
    Sbd: "SBD",
    Scr: "SCR",
    Sdg: "SDG",
    Sek: "SEK",
    Sgd: "SGD",
    Shp: "SHP",
    Sll: "SLL",
    Sos: "SOS",
    Spl: "SPL",
    Srd: "SRD",
    Std: "STD",
    Svc: "SVC",
    Syp: "SYP",
    Szl: "SZL",
    Thb: "THB",
    Tjs: "TJS",
    Tmt: "TMT",
    Tnd: "TND",
    Top: "TOP",
    Try: "TRY",
    Ttd: "TTD",
    Tvd: "TVD",
    Twd: "TWD",
    Tzs: "TZS",
    Uah: "UAH",
    Ugx: "UGX",
    Usd: "USD",
    Uyu: "UYU",
    Uzs: "UZS",
    Vef: "VEF",
    Vnd: "VND",
    Vuv: "VUV",
    Wst: "WST",
    Xaf: "XAF",
    Xcd: "XCD",
    Xdr: "XDR",
    Xof: "XOF",
    Xpf: "XPF",
    Yer: "YER",
    Zar: "ZAR",
    Zmw: "ZMW",
    Zwd: "ZWD",
    Pts: "PTS",
  } as const;
/**
 * The currency code used for the transfer
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipCurrencyCode =
  OpenEnum<
    typeof ComCrmContactSelfServiceResourceGetContactRelationshipCurrencyCode
  >;

export type ComCrmContactSelfServiceResourceGetContactRelationshipTermedTransferCommercePool =
  {
    /**
     * Unique identifier of the commerce pool associated with the transfer (optional). If specified, the transferred funds are credited to the community member’s Commerce Pocket, if not, they are credited to the Business Pocket.
     */
    id?: string | undefined;
    /**
     * The commerce pool name
     */
    name?: string | undefined;
  };

/**
 * Transfers can be scheduled either weekly or monthly
 */
export const ComCrmContactSelfServiceResourceGetContactRelationshipFrequency = {
  Weekly: "WEEKLY",
  Monthly: "MONTHLY",
} as const;
/**
 * Transfers can be scheduled either weekly or monthly
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipFrequency =
  OpenEnum<
    typeof ComCrmContactSelfServiceResourceGetContactRelationshipFrequency
  >;

/**
 * Day of the week when the transfer will occur
 */
export const ComCrmContactSelfServiceResourceGetContactRelationshipDayOfWeek = {
  Monday: "MONDAY",
  Tuesday: "TUESDAY",
  Wednesday: "WEDNESDAY",
  Thursday: "THURSDAY",
  Friday: "FRIDAY",
  Saturday: "SATURDAY",
  Sunday: "SUNDAY",
} as const;
/**
 * Day of the week when the transfer will occur
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipDayOfWeek =
  ClosedEnum<
    typeof ComCrmContactSelfServiceResourceGetContactRelationshipDayOfWeek
  >;

/**
 * How often the transfer will occur
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipSchedule = {
  /**
   * Transfers can be scheduled either weekly or monthly
   */
  frequency?:
    | ComCrmContactSelfServiceResourceGetContactRelationshipFrequency
    | undefined;
  /**
   * Day of the week when the transfer will occur
   */
  dayOfWeek?:
    | ComCrmContactSelfServiceResourceGetContactRelationshipDayOfWeek
    | undefined;
  /**
   * The day of the month when the transfer occurs, if the specified day doesn’t exist in a month, the transfer occurs on the last day of the month
   */
  dayOfMonth?: number | undefined;
};

/**
 * The termed transfers set up by the community owner for the community member
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipTermedTransfer =
  {
    /**
     * Indicates whether the recurring transfer is enabled, if disabled, the transfer will not be performed
     */
    isEnabled?: boolean | undefined;
    /**
     * The amount to be transferred
     */
    amount?: number | undefined;
    /**
     * The currency code used for the transfer
     */
    currencyCode?:
      | ComCrmContactSelfServiceResourceGetContactRelationshipCurrencyCode
      | undefined;
    commercePool?:
      | ComCrmContactSelfServiceResourceGetContactRelationshipTermedTransferCommercePool
      | undefined;
    /**
     * How often the transfer will occur
     */
    schedule?:
      | ComCrmContactSelfServiceResourceGetContactRelationshipSchedule
      | undefined;
  };

/**
 * OK
 */
export type ComCrmContactSelfServiceResourceGetContactRelationshipResponse = {
  /**
   * The contact relationship identifier
   */
  id?: string | undefined;
  /**
   * The community relation that the contact has
   */
  relation?:
    | ComCrmContactSelfServiceResourceGetContactRelationshipRelation
    | undefined;
  /**
   * A name that groups together community members
   */
  group?: string | undefined;
  /**
   * Defines whether the contact member has full permissions. Applicable only for communities of a Contact Company.
   */
  isAdmin?: boolean | undefined;
  /**
   * Defines the (explicit) allowed permissions that the new contact member will have
   */
  permissions?:
    | Array<ComCrmContactSelfServiceResourceGetContactRelationshipPermission>
    | undefined;
  /**
   * Defines the devices that have been assigned to the community member
   */
  devices?:
    | Array<ComCrmContactSelfServiceResourceGetContactRelationshipDevice>
    | undefined;
  /**
   * The contact (parent or member in the respective community)
   */
  contact?:
    | ComCrmContactSelfServiceResourceGetContactRelationshipContact
    | undefined;
  /**
   * Defines whether the community person will be able to use/request money from community owner wallet
   */
  walletSharing?:
    | ComCrmContactSelfServiceResourceGetContactRelationshipWalletSharing
    | undefined;
  /**
   * Defines the usage allowance
   */
  usageAllowance?:
    | ComCrmContactSelfServiceResourceGetContactRelationshipUsageAllowance
    | undefined;
  /**
   * The community member’s relation state. A person is considered as a valid community person only after they accept the invitation to join the community.
   */
  state?:
    | ComCrmContactSelfServiceResourceGetContactRelationshipState
    | undefined;
  /**
   * The termed transfers set up by the community owner for the community member
   */
  termedTransfer?:
    | ComCrmContactSelfServiceResourceGetContactRelationshipTermedTransfer
    | undefined;
};

/** @internal */
export type ComCrmContactSelfServiceResourceGetContactRelationshipRequest$Outbound =
  {
    id: string;
    relationship_id: string;
    include_remaining_allowance?: boolean | undefined;
  };

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipRequest$outboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipRequest$Outbound,
    ComCrmContactSelfServiceResourceGetContactRelationshipRequest
  > = z.pipe(
    z.object({
      id: z.string(),
      relationshipId: z.string(),
      includeRemainingAllowance: z.optional(z.boolean()),
    }),
    z.transform((v) => {
      return remap$(v, {
        relationshipId: "relationship_id",
        includeRemainingAllowance: "include_remaining_allowance",
      });
    }),
  );

export function comCrmContactSelfServiceResourceGetContactRelationshipRequestToJSON(
  comCrmContactSelfServiceResourceGetContactRelationshipRequest:
    ComCrmContactSelfServiceResourceGetContactRelationshipRequest,
): string {
  return JSON.stringify(
    ComCrmContactSelfServiceResourceGetContactRelationshipRequest$outboundSchema
      .parse(comCrmContactSelfServiceResourceGetContactRelationshipRequest),
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipRelation$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipRelation,
    unknown
  > = z.object({
    id: types.optional(types.string()),
    name: types.optional(types.string()),
  });

export function comCrmContactSelfServiceResourceGetContactRelationshipRelationFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipRelation,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipRelation$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipRelation' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipPermission$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipPermission,
    unknown
  > = openEnums.inboundSchema(
    ComCrmContactSelfServiceResourceGetContactRelationshipPermission,
  );

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipCustomField$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipCustomField,
    unknown
  > = z.object({
    key: types.optional(types.string()),
    value: types.optional(types.string()),
  });

export function comCrmContactSelfServiceResourceGetContactRelationshipCustomFieldFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipCustomField,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipCustomField$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipCustomField' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipDevice$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipDevice,
    unknown
  > = z.pipe(
    z.object({
      id: types.optional(types.string()),
      serial_number: types.optional(types.string()),
      custom_fields: types.optional(z.array(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipCustomField$inboundSchema
      ))),
    }),
    z.transform((v) => {
      return remap$(v, {
        "serial_number": "serialNumber",
        "custom_fields": "customFields",
      });
    }),
  );

export function comCrmContactSelfServiceResourceGetContactRelationshipDeviceFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipDevice,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipDevice$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipDevice' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipCountryCode$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipCountryCode,
    unknown
  > = openEnums.inboundSchema(
    ComCrmContactSelfServiceResourceGetContactRelationshipCountryCode,
  );

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipPhone$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipPhone,
    unknown
  > = z.pipe(
    z.object({
      country_code: types.optional(
        ComCrmContactSelfServiceResourceGetContactRelationshipCountryCode$inboundSchema,
      ),
      number: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "country_code": "countryCode",
      });
    }),
  );

export function comCrmContactSelfServiceResourceGetContactRelationshipPhoneFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipPhone,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipPhone$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipPhone' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipWallet$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipWallet,
    unknown
  > = z.object({
    id: types.optional(types.string()),
  });

export function comCrmContactSelfServiceResourceGetContactRelationshipWalletFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipWallet,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipWallet$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipWallet' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipContact$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipContact,
    unknown
  > = z.pipe(
    z.object({
      id: types.optional(types.string()),
      first_name: types.optional(types.string()),
      last_name: types.optional(types.string()),
      phone: types.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipPhone$inboundSchema
      )),
      email: types.optional(types.string()),
      wallet: types.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipWallet$inboundSchema
      )),
    }),
    z.transform((v) => {
      return remap$(v, {
        "first_name": "firstName",
        "last_name": "lastName",
      });
    }),
  );

export function comCrmContactSelfServiceResourceGetContactRelationshipContactFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipContact,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipContact$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipContact' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipWalletSharingCommercePool$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipWalletSharingCommercePool,
    unknown
  > = z.object({
    id: types.optional(types.string()),
    name: types.optional(types.string()),
    description: types.optional(types.string()),
  });

export function comCrmContactSelfServiceResourceGetContactRelationshipWalletSharingCommercePoolFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipWalletSharingCommercePool,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipWalletSharingCommercePool$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipWalletSharingCommercePool' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipMethod$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipMethod,
    unknown
  > = openEnums.inboundSchema(
    ComCrmContactSelfServiceResourceGetContactRelationshipMethod,
  );

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipWalletSharing$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipWalletSharing,
    unknown
  > = z.pipe(
    z.object({
      is_enabled: types.optional(types.boolean()),
      commerce_pools: types.optional(z.array(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipWalletSharingCommercePool$inboundSchema
      ))),
      method: types.optional(
        ComCrmContactSelfServiceResourceGetContactRelationshipMethod$inboundSchema,
      ),
      max_amount: types.optional(types.number()),
      remaining_amount: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "is_enabled": "isEnabled",
        "commerce_pools": "commercePools",
        "max_amount": "maxAmount",
        "remaining_amount": "remainingAmount",
      });
    }),
  );

export function comCrmContactSelfServiceResourceGetContactRelationshipWalletSharingFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipWalletSharing,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipWalletSharing$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipWalletSharing' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipAccumulatedAllowanceCashLimits$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipAccumulatedAllowanceCashLimits,
    unknown
  > = z.pipe(
    z.object({
      per_transaction: types.optional(types.number()),
      per_day: types.optional(types.number()),
      per_billing_cycle: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "per_transaction": "perTransaction",
        "per_day": "perDay",
        "per_billing_cycle": "perBillingCycle",
      });
    }),
  );

export function comCrmContactSelfServiceResourceGetContactRelationshipAccumulatedAllowanceCashLimitsFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipAccumulatedAllowanceCashLimits,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipAccumulatedAllowanceCashLimits$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipAccumulatedAllowanceCashLimits' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipRemainingCash$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipRemainingCash,
    unknown
  > = z.pipe(
    z.object({
      per_transaction: types.optional(types.number()),
      per_day: types.optional(types.number()),
      per_billing_cycle: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "per_transaction": "perTransaction",
        "per_day": "perDay",
        "per_billing_cycle": "perBillingCycle",
      });
    }),
  );

export function comCrmContactSelfServiceResourceGetContactRelationshipRemainingCashFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipRemainingCash,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipRemainingCash$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipRemainingCash' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipAccumulatedAllowance$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipAccumulatedAllowance,
    unknown
  > = z.pipe(
    z.object({
      currency: types.optional(types.string()),
      cash_limits: types.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipAccumulatedAllowanceCashLimits$inboundSchema
      )),
      remaining_cash: types.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipRemainingCash$inboundSchema
      )),
    }),
    z.transform((v) => {
      return remap$(v, {
        "cash_limits": "cashLimits",
        "remaining_cash": "remainingCash",
      });
    }),
  );

export function comCrmContactSelfServiceResourceGetContactRelationshipAccumulatedAllowanceFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipAccumulatedAllowance,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipAccumulatedAllowance$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipAccumulatedAllowance' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipItemType$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipItemType,
    unknown
  > = openEnums.inboundSchema(
    ComCrmContactSelfServiceResourceGetContactRelationshipItemType,
  );

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipMeasurementUnit$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipMeasurementUnit,
    unknown
  > = z.pipe(
    z.object({
      name: types.optional(types.string()),
      display_name: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "display_name": "displayName",
      });
    }),
  );

export function comCrmContactSelfServiceResourceGetContactRelationshipMeasurementUnitFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipMeasurementUnit,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipMeasurementUnit$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipMeasurementUnit' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipProductsAllowanceCashLimits$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipProductsAllowanceCashLimits,
    unknown
  > = z.pipe(
    z.object({
      per_transaction: types.optional(types.number()),
      per_day: types.optional(types.number()),
      per_billing_cycle: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "per_transaction": "perTransaction",
        "per_day": "perDay",
        "per_billing_cycle": "perBillingCycle",
      });
    }),
  );

export function comCrmContactSelfServiceResourceGetContactRelationshipProductsAllowanceCashLimitsFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipProductsAllowanceCashLimits,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipProductsAllowanceCashLimits$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipProductsAllowanceCashLimits' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipUsageLimits$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipUsageLimits,
    unknown
  > = z.pipe(
    z.object({
      per_transaction: types.optional(types.number()),
      per_day: types.optional(types.number()),
      per_billing_cycle: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "per_transaction": "perTransaction",
        "per_day": "perDay",
        "per_billing_cycle": "perBillingCycle",
      });
    }),
  );

export function comCrmContactSelfServiceResourceGetContactRelationshipUsageLimitsFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipUsageLimits,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipUsageLimits$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipUsageLimits' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipProductsAllowance$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipProductsAllowance,
    unknown
  > = z.pipe(
    z.object({
      id: types.optional(types.string()),
      group_id: types.optional(types.string()),
      currency: types.optional(types.string()),
      item_type: types.optional(
        ComCrmContactSelfServiceResourceGetContactRelationshipItemType$inboundSchema,
      ),
      item_id: types.optional(types.string()),
      name: types.optional(types.string()),
      sku: types.optional(types.string()),
      measurement_unit: types.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipMeasurementUnit$inboundSchema
      )),
      cash_limits: types.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipProductsAllowanceCashLimits$inboundSchema
      )),
      usage_limits: types.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipUsageLimits$inboundSchema
      )),
    }),
    z.transform((v) => {
      return remap$(v, {
        "group_id": "groupId",
        "item_type": "itemType",
        "item_id": "itemId",
        "measurement_unit": "measurementUnit",
        "cash_limits": "cashLimits",
        "usage_limits": "usageLimits",
      });
    }),
  );

export function comCrmContactSelfServiceResourceGetContactRelationshipProductsAllowanceFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipProductsAllowance,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipProductsAllowance$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipProductsAllowance' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipOrganisation$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipOrganisation,
    unknown
  > = z.object({
    id: types.optional(types.string()),
    name: types.optional(types.string()),
  });

export function comCrmContactSelfServiceResourceGetContactRelationshipOrganisationFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipOrganisation,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipOrganisation$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipOrganisation' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipUsageAllowance$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipUsageAllowance,
    unknown
  > = z.pipe(
    z.object({
      accumulated_allowance: types.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipAccumulatedAllowance$inboundSchema
      )),
      same_as_owner: types.optional(types.boolean()),
      has_products_allowance: types.optional(types.boolean()),
      products_allowance: types.optional(z.array(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipProductsAllowance$inboundSchema
      ))),
      organisations: types.optional(z.array(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipOrganisation$inboundSchema
      ))),
    }),
    z.transform((v) => {
      return remap$(v, {
        "accumulated_allowance": "accumulatedAllowance",
        "same_as_owner": "sameAsOwner",
        "has_products_allowance": "hasProductsAllowance",
        "products_allowance": "productsAllowance",
      });
    }),
  );

export function comCrmContactSelfServiceResourceGetContactRelationshipUsageAllowanceFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipUsageAllowance,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipUsageAllowance$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipUsageAllowance' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipState$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipState,
    unknown
  > = openEnums.inboundSchema(
    ComCrmContactSelfServiceResourceGetContactRelationshipState,
  );

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipCurrencyCode$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipCurrencyCode,
    unknown
  > = openEnums.inboundSchema(
    ComCrmContactSelfServiceResourceGetContactRelationshipCurrencyCode,
  );

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipTermedTransferCommercePool$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipTermedTransferCommercePool,
    unknown
  > = z.object({
    id: types.optional(types.string()),
    name: types.optional(types.string()),
  });

export function comCrmContactSelfServiceResourceGetContactRelationshipTermedTransferCommercePoolFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipTermedTransferCommercePool,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipTermedTransferCommercePool$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipTermedTransferCommercePool' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipFrequency$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipFrequency,
    unknown
  > = openEnums.inboundSchema(
    ComCrmContactSelfServiceResourceGetContactRelationshipFrequency,
  );

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipDayOfWeek$inboundSchema:
  z.ZodMiniEnum<
    typeof ComCrmContactSelfServiceResourceGetContactRelationshipDayOfWeek
  > = z.enum(ComCrmContactSelfServiceResourceGetContactRelationshipDayOfWeek);

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipSchedule$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipSchedule,
    unknown
  > = z.pipe(
    z.object({
      frequency: types.optional(
        ComCrmContactSelfServiceResourceGetContactRelationshipFrequency$inboundSchema,
      ),
      day_of_week: types.optional(
        ComCrmContactSelfServiceResourceGetContactRelationshipDayOfWeek$inboundSchema,
      ),
      day_of_month: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "day_of_week": "dayOfWeek",
        "day_of_month": "dayOfMonth",
      });
    }),
  );

export function comCrmContactSelfServiceResourceGetContactRelationshipScheduleFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipSchedule,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipSchedule$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipSchedule' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipTermedTransfer$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipTermedTransfer,
    unknown
  > = z.pipe(
    z.object({
      is_enabled: types.optional(types.boolean()),
      amount: types.optional(types.number()),
      currency_code: types.optional(
        ComCrmContactSelfServiceResourceGetContactRelationshipCurrencyCode$inboundSchema,
      ),
      commerce_pool: types.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipTermedTransferCommercePool$inboundSchema
      )),
      schedule: types.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipSchedule$inboundSchema
      )),
    }),
    z.transform((v) => {
      return remap$(v, {
        "is_enabled": "isEnabled",
        "currency_code": "currencyCode",
        "commerce_pool": "commercePool",
      });
    }),
  );

export function comCrmContactSelfServiceResourceGetContactRelationshipTermedTransferFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipTermedTransfer,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipTermedTransfer$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipTermedTransfer' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetContactRelationshipResponse$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetContactRelationshipResponse,
    unknown
  > = z.pipe(
    z.object({
      id: types.optional(types.string()),
      relation: types.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipRelation$inboundSchema
      )),
      group: types.optional(types.string()),
      is_admin: types.optional(types.boolean()),
      permissions: types.optional(
        z.array(
          ComCrmContactSelfServiceResourceGetContactRelationshipPermission$inboundSchema,
        ),
      ),
      devices: types.optional(z.array(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipDevice$inboundSchema
      ))),
      contact: types.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipContact$inboundSchema
      )),
      wallet_sharing: types.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipWalletSharing$inboundSchema
      )),
      usage_allowance: types.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipUsageAllowance$inboundSchema
      )),
      state: types.optional(
        ComCrmContactSelfServiceResourceGetContactRelationshipState$inboundSchema,
      ),
      termed_transfer: types.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceGetContactRelationshipTermedTransfer$inboundSchema
      )),
    }),
    z.transform((v) => {
      return remap$(v, {
        "is_admin": "isAdmin",
        "wallet_sharing": "walletSharing",
        "usage_allowance": "usageAllowance",
        "termed_transfer": "termedTransfer",
      });
    }),
  );

export function comCrmContactSelfServiceResourceGetContactRelationshipResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetContactRelationshipResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetContactRelationshipResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetContactRelationshipResponse' from JSON`,
  );
}
