/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1d38bbda4140
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ComCrmContactSelfServiceAnalyticsResourceGetAnalyticsRequest = {
  /**
   * The contact identifier that analytics will be retrieved
   */
  id: string;
  /**
   * Frequency denotes which metric will be applied for example get the metrics of this month
   */
  frequency: string;
  /**
   * Which metrics are required. A list of metrics can be included in the request, comma separated. At least one must be specified.
   */
  metrics: any;
};

/**
 * The total amounts for wallet transactions performed by the contact
 */
export type WalletTotals = {
  /**
   * The total top-up amount
   */
  totalTopUps?: number | undefined;
  /**
   * The total spent amount
   */
  totalSpent?: number | undefined;
  /**
   * The total amount that sent from this contact (result of a transfer transaction)
   */
  totalSent?: number | undefined;
  /**
   * The total amount that received from this contact (result of a transfer transaction)
   */
  totalReceived?: number | undefined;
};

export type AwardsPerMonth = {
  /**
   * The monthly amount
   */
  amount?: number | undefined;
  /**
   * The month's timestamp
   */
  timestamp?: number | undefined;
};

export type RedeemsPerMonth = {
  /**
   * The monthly amount
   */
  amount?: number | undefined;
  /**
   * The month's timestamp
   */
  timestamp?: number | undefined;
};

/**
 * OK
 */
export type ComCrmContactSelfServiceAnalyticsResourceGetAnalyticsResponse = {
  /**
   * The total orders performed by the contact
   */
  totalOrders?: number | undefined;
  /**
   * The total amounts for wallet transactions performed by the contact
   */
  walletTotals?: WalletTotals | undefined;
  /**
   * The contact's award amount per month
   */
  awardsPerMonth?: Array<AwardsPerMonth> | undefined;
  /**
   * The contact's redeem amount per month
   */
  redeemsPerMonth?: Array<RedeemsPerMonth> | undefined;
};

/** @internal */
export type ComCrmContactSelfServiceAnalyticsResourceGetAnalyticsRequest$Outbound =
  {
    id: string;
    frequency: string;
    metrics: any;
  };

/** @internal */
export const ComCrmContactSelfServiceAnalyticsResourceGetAnalyticsRequest$outboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceAnalyticsResourceGetAnalyticsRequest$Outbound,
    ComCrmContactSelfServiceAnalyticsResourceGetAnalyticsRequest
  > = z.object({
    id: z.string(),
    frequency: z.string(),
    metrics: z.any(),
  });

export function comCrmContactSelfServiceAnalyticsResourceGetAnalyticsRequestToJSON(
  comCrmContactSelfServiceAnalyticsResourceGetAnalyticsRequest:
    ComCrmContactSelfServiceAnalyticsResourceGetAnalyticsRequest,
): string {
  return JSON.stringify(
    ComCrmContactSelfServiceAnalyticsResourceGetAnalyticsRequest$outboundSchema
      .parse(comCrmContactSelfServiceAnalyticsResourceGetAnalyticsRequest),
  );
}

/** @internal */
export const WalletTotals$inboundSchema: z.ZodMiniType<WalletTotals, unknown> =
  z.pipe(
    z.object({
      total_top_ups: types.optional(types.number()),
      total_spent: types.optional(types.number()),
      total_sent: types.optional(types.number()),
      total_received: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "total_top_ups": "totalTopUps",
        "total_spent": "totalSpent",
        "total_sent": "totalSent",
        "total_received": "totalReceived",
      });
    }),
  );

export function walletTotalsFromJSON(
  jsonString: string,
): SafeParseResult<WalletTotals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletTotals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletTotals' from JSON`,
  );
}

/** @internal */
export const AwardsPerMonth$inboundSchema: z.ZodMiniType<
  AwardsPerMonth,
  unknown
> = z.object({
  amount: types.optional(types.number()),
  timestamp: types.optional(types.number()),
});

export function awardsPerMonthFromJSON(
  jsonString: string,
): SafeParseResult<AwardsPerMonth, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AwardsPerMonth$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AwardsPerMonth' from JSON`,
  );
}

/** @internal */
export const RedeemsPerMonth$inboundSchema: z.ZodMiniType<
  RedeemsPerMonth,
  unknown
> = z.object({
  amount: types.optional(types.number()),
  timestamp: types.optional(types.number()),
});

export function redeemsPerMonthFromJSON(
  jsonString: string,
): SafeParseResult<RedeemsPerMonth, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedeemsPerMonth$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedeemsPerMonth' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceAnalyticsResourceGetAnalyticsResponse$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceAnalyticsResourceGetAnalyticsResponse,
    unknown
  > = z.pipe(
    z.object({
      total_orders: types.optional(types.number()),
      wallet_totals: types.optional(z.lazy(() => WalletTotals$inboundSchema)),
      awards_per_month: types.optional(
        z.array(z.lazy(() => AwardsPerMonth$inboundSchema)),
      ),
      redeems_per_month: types.optional(
        z.array(z.lazy(() => RedeemsPerMonth$inboundSchema)),
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "total_orders": "totalOrders",
        "wallet_totals": "walletTotals",
        "awards_per_month": "awardsPerMonth",
        "redeems_per_month": "redeemsPerMonth",
      });
    }),
  );

export function comCrmContactSelfServiceAnalyticsResourceGetAnalyticsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceAnalyticsResourceGetAnalyticsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceAnalyticsResourceGetAnalyticsResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceAnalyticsResourceGetAnalyticsResponse' from JSON`,
  );
}
