/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Defines how the results will be ordered</br>Default:DESC
 */
export const ComCrmContactSelfServiceResourceListContactDonationsOrder = {
  Asc: "ASC",
  Desc: "DESC",
} as const;
/**
 * Defines how the results will be ordered</br>Default:DESC
 */
export type ComCrmContactSelfServiceResourceListContactDonationsOrder =
  ClosedEnum<typeof ComCrmContactSelfServiceResourceListContactDonationsOrder>;

export type ComCrmContactSelfServiceResourceListContactDonationsRequest = {
  /**
   * The contact identifier whose relationships will be retrieved
   */
  id: string;
  /**
   * The donation offer id
   */
  donationOfferId?: string | undefined;
  /**
   * Defaults to False. If selected, then opted-out donation offers are also returned.
   */
  includeOptOut?: boolean | undefined;
  /**
   *  Determine if a "total" will be returned in paging reference. If set to True, then "total" is also returned but it will return up to 10K value. If set to False, then the "total" in paging is null.
   */
  includeTotal?: boolean | undefined;
  /**
   * Defines how the results will be ordered</br>Default:DESC
   */
  order?: ComCrmContactSelfServiceResourceListContactDonationsOrder | undefined;
  /**
   * The page number that should be retrieved</br>Default:1
   */
  page?: number | undefined;
  /**
   * The size (total records) of each page</br>Default:10
   */
  size?: number | undefined;
  /**
   * Defines on which attribute the results should be sorted</br>Default:CREATED_DATE
   */
  sort?: string | undefined;
};

export type ComCrmContactSelfServiceResourceListContactDonationsPaging = {
  /**
   * The page number
   */
  page?: number | undefined;
  /**
   * The number of records per page
   */
  size?: number | undefined;
  /**
   * The total number of records. If "include_total" is not specified, then this total is null. If "include_total" is specified, total has a value but it is accurate up to 10K records.
   */
  total?: number | undefined;
  /**
   * Shows if there are more records available to fetch
   */
  hasMore?: boolean | undefined;
};

/**
 * The currency
 */
export const ComCrmContactSelfServiceResourceListContactDonationsCurrencyCode =
  {
    Aed: "AED",
    Afn: "AFN",
    All: "ALL",
    Amd: "AMD",
    Ang: "ANG",
    Aoa: "AOA",
    Ars: "ARS",
    Aud: "AUD",
    Awg: "AWG",
    Azn: "AZN",
    Bam: "BAM",
    Bbd: "BBD",
    Bdt: "BDT",
    Bgn: "BGN",
    Bhd: "BHD",
    Bif: "BIF",
    Bmd: "BMD",
    Bnd: "BND",
    Bob: "BOB",
    Brl: "BRL",
    Bsd: "BSD",
    Btn: "BTN",
    Bwp: "BWP",
    Byr: "BYR",
    Bzd: "BZD",
    Cad: "CAD",
    Cdf: "CDF",
    Chf: "CHF",
    Clp: "CLP",
    Cny: "CNY",
    Cop: "COP",
    Crc: "CRC",
    Cuc: "CUC",
    Cup: "CUP",
    Cve: "CVE",
    Czk: "CZK",
    Djf: "DJF",
    Dkk: "DKK",
    Dop: "DOP",
    Dzd: "DZD",
    Egp: "EGP",
    Ern: "ERN",
    Etb: "ETB",
    Eur: "EUR",
    Fjd: "FJD",
    Fkp: "FKP",
    Gbp: "GBP",
    Gel: "GEL",
    Ggp: "GGP",
    Ghs: "GHS",
    Gip: "GIP",
    Gmd: "GMD",
    Gnf: "GNF",
    Gtq: "GTQ",
    Gyd: "GYD",
    Hkd: "HKD",
    Hnl: "HNL",
    Hrk: "HRK",
    Htg: "HTG",
    Huf: "HUF",
    Idr: "IDR",
    Ils: "ILS",
    Imp: "IMP",
    Inr: "INR",
    Iqd: "IQD",
    Irr: "IRR",
    Isk: "ISK",
    Jep: "JEP",
    Jmd: "JMD",
    Jod: "JOD",
    Jpy: "JPY",
    Kes: "KES",
    Kgs: "KGS",
    Khr: "KHR",
    Kmf: "KMF",
    Kpw: "KPW",
    Krw: "KRW",
    Kwd: "KWD",
    Kyd: "KYD",
    Kzt: "KZT",
    Lak: "LAK",
    Lbp: "LBP",
    Lkr: "LKR",
    Lrd: "LRD",
    Lsl: "LSL",
    Lyd: "LYD",
    Mad: "MAD",
    Mdl: "MDL",
    Mga: "MGA",
    Mkd: "MKD",
    Mmk: "MMK",
    Mnt: "MNT",
    Mop: "MOP",
    Mro: "MRO",
    Mur: "MUR",
    Mvr: "MVR",
    Mwk: "MWK",
    Mxn: "MXN",
    Myr: "MYR",
    Mzn: "MZN",
    Nad: "NAD",
    Ngn: "NGN",
    Nio: "NIO",
    Nok: "NOK",
    Npr: "NPR",
    Nzd: "NZD",
    Omr: "OMR",
    Pab: "PAB",
    Pen: "PEN",
    Pgk: "PGK",
    Php: "PHP",
    Pkr: "PKR",
    Pln: "PLN",
    Pyg: "PYG",
    Qar: "QAR",
    Ron: "RON",
    Rsd: "RSD",
    Rub: "RUB",
    Rwf: "RWF",
    Sar: "SAR",
    Sbd: "SBD",
    Scr: "SCR",
    Sdg: "SDG",
    Sek: "SEK",
    Sgd: "SGD",
    Shp: "SHP",
    Sll: "SLL",
    Sos: "SOS",
    Spl: "SPL",
    Srd: "SRD",
    Std: "STD",
    Svc: "SVC",
    Syp: "SYP",
    Szl: "SZL",
    Thb: "THB",
    Tjs: "TJS",
    Tmt: "TMT",
    Tnd: "TND",
    Top: "TOP",
    Try: "TRY",
    Ttd: "TTD",
    Tvd: "TVD",
    Twd: "TWD",
    Tzs: "TZS",
    Uah: "UAH",
    Ugx: "UGX",
    Usd: "USD",
    Uyu: "UYU",
    Uzs: "UZS",
    Vef: "VEF",
    Vnd: "VND",
    Vuv: "VUV",
    Wst: "WST",
    Xaf: "XAF",
    Xcd: "XCD",
    Xdr: "XDR",
    Xof: "XOF",
    Xpf: "XPF",
    Yer: "YER",
    Zar: "ZAR",
    Zmw: "ZMW",
    Zwd: "ZWD",
    Pts: "PTS",
  } as const;
/**
 * The currency
 */
export type ComCrmContactSelfServiceResourceListContactDonationsCurrencyCode =
  OpenEnum<
    typeof ComCrmContactSelfServiceResourceListContactDonationsCurrencyCode
  >;

/**
 * Information about the creative type
 */
export const ComCrmContactSelfServiceResourceListContactDonationsUsageType = {
  Logo: "LOGO",
  Background: "BACKGROUND",
  Avatar: "AVATAR",
  Hero: "HERO",
  Marketing: "MARKETING",
  Attachment: "ATTACHMENT",
  Profileimage: "PROFILEIMAGE",
  AppleLockscreenIcon: "APPLE_LOCKSCREEN_ICON",
  AppleLogoImage: "APPLE_LOGO_IMAGE",
  AppleStripImage: "APPLE_STRIP_IMAGE",
  GoogleLogoImage: "GOOGLE_LOGO_IMAGE",
  GoogleStripImage: "GOOGLE_STRIP_IMAGE",
  LandingPageLogoImage: "LANDING_PAGE_LOGO_IMAGE",
  LandingPageHeaderImage: "LANDING_PAGE_HEADER_IMAGE",
  LandingPageBackgroundImage: "LANDING_PAGE_BACKGROUND_IMAGE",
  DeliveryImage: "DELIVERY_IMAGE",
  PickupImage: "PICKUP_IMAGE",
  DirectSaleImage: "DIRECT_SALE_IMAGE",
  WalletImage: "WALLET_IMAGE",
  LandingPageImage: "LANDING_PAGE_IMAGE",
  AppLogo: "APP_LOGO",
  PartnerLogo: "PARTNER_LOGO",
  Carousel: "CAROUSEL",
  Shortcut: "SHORTCUT",
  ShortcutImage: "SHORTCUT_IMAGE",
  EmbeddedLinkImage: "EMBEDDED_LINK_IMAGE",
  Image: "IMAGE",
  AppLoaderImage: "APP_LOADER_IMAGE",
  MobileBackgroundImage: "MOBILE_BACKGROUND_IMAGE",
} as const;
/**
 * Information about the creative type
 */
export type ComCrmContactSelfServiceResourceListContactDonationsUsageType =
  OpenEnum<
    typeof ComCrmContactSelfServiceResourceListContactDonationsUsageType
  >;

export type ComCrmContactSelfServiceResourceListContactDonationsMedia = {
  /**
   * The transformed creative width
   */
  width?: number | undefined;
  /**
   * The transformed creative height
   */
  height?: number | undefined;
  /**
   * The transformed creative URL
   */
  url?: string | undefined;
};

export type ComCrmContactSelfServiceResourceListContactDonationsCreative = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
  /**
   * the identifier of media
   */
  mediaGroupId?: string | undefined;
  /**
   * Information about the creative type
   */
  usageType?:
    | ComCrmContactSelfServiceResourceListContactDonationsUsageType
    | undefined;
  /**
   * The creative width
   */
  width?: number | undefined;
  /**
   * The creative height
   */
  height?: number | undefined;
  /**
   * The creative format
   */
  format?: string | undefined;
  /**
   * The creative content URL
   */
  url?: string | undefined;
  /**
   * The creative public identifier
   */
  publicId?: string | undefined;
  /**
   * The media identifier
   */
  mediaId?: string | undefined;
  /**
   * The creative caption used in cases where usage_type=CAROUSEL
   */
  caption?: string | undefined;
  /**
   * The creative sort order used in cases where usage_type=CAROUSEL
   */
  sortOrder?: number | undefined;
  /**
   * Information about the creative transformations
   */
  media?:
    | Array<ComCrmContactSelfServiceResourceListContactDonationsMedia>
    | undefined;
};

/**
 * The donation offer the contact is opt-in to.
 */
export type ComCrmContactSelfServiceResourceListContactDonationsDonationOffer =
  {
    /**
     * The reward offer identifier
     */
    id?: string | undefined;
    /**
     * The reward offer name
     */
    name?: string | undefined;
    /**
     * Details about creatives. A creative is an object that contains all the data required for visually rendering an image responsively, such as the initial image and a number of scale versions of it (srcset)
     */
    creatives?:
      | Array<ComCrmContactSelfServiceResourceListContactDonationsCreative>
      | undefined;
  };

/**
 * The organisation that receives the donation
 */
export type ComCrmContactSelfServiceResourceListContactDonationsOrganisation = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
  /**
   * The entity name
   */
  name?: string | undefined;
};

/**
 * The donation's details that show how/when donations are made by the contact
 */
export type ComCrmContactSelfServiceResourceListContactDonationsDetails = {
  /**
   * Applicable for donations per transaction. The donations amount is calculated based on the purchase's rounded up amount times this multipler.
   */
  multiplier: number;
  /**
   * Applicable for recurring donations wutg variable amount.
   */
  amount: number;
};

export type ComCrmContactSelfServiceResourceListContactDonationsContent = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
  /**
   * The date on which the contact opted-in to the donation offers
   */
  optedIn?: number | undefined;
  /**
   * The date on which the contact opted-out from the donation offer.
   */
  optedOut?: number | undefined;
  /**
   * Number of donations made
   */
  donations?: number | undefined;
  /**
   * Total donated amount
   */
  amount?: number | undefined;
  /**
   * The currency
   */
  currencyCode?:
    | ComCrmContactSelfServiceResourceListContactDonationsCurrencyCode
    | undefined;
  /**
   * The donation offer the contact is opt-in to.
   */
  donationOffer?:
    | ComCrmContactSelfServiceResourceListContactDonationsDonationOffer
    | undefined;
  /**
   * The organisation that receives the donation
   */
  organisation?:
    | ComCrmContactSelfServiceResourceListContactDonationsOrganisation
    | undefined;
  /**
   * The donation's details that show how/when donations are made by the contact
   */
  details?:
    | ComCrmContactSelfServiceResourceListContactDonationsDetails
    | undefined;
};

/**
 * OK
 */
export type ComCrmContactSelfServiceResourceListContactDonationsResponse = {
  paging?:
    | ComCrmContactSelfServiceResourceListContactDonationsPaging
    | undefined;
  content?:
    | Array<ComCrmContactSelfServiceResourceListContactDonationsContent>
    | undefined;
};

/** @internal */
export const ComCrmContactSelfServiceResourceListContactDonationsOrder$outboundSchema:
  z.ZodMiniEnum<
    typeof ComCrmContactSelfServiceResourceListContactDonationsOrder
  > = z.enum(ComCrmContactSelfServiceResourceListContactDonationsOrder);

/** @internal */
export type ComCrmContactSelfServiceResourceListContactDonationsRequest$Outbound =
  {
    id: string;
    donation_offer_id?: string | undefined;
    include_opt_out?: boolean | undefined;
    include_total?: boolean | undefined;
    order?: string | undefined;
    page?: number | undefined;
    size?: number | undefined;
    sort?: string | undefined;
  };

/** @internal */
export const ComCrmContactSelfServiceResourceListContactDonationsRequest$outboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceListContactDonationsRequest$Outbound,
    ComCrmContactSelfServiceResourceListContactDonationsRequest
  > = z.pipe(
    z.object({
      id: z.string(),
      donationOfferId: z.optional(z.string()),
      includeOptOut: z.optional(z.boolean()),
      includeTotal: z.optional(z.boolean()),
      order: z.optional(
        ComCrmContactSelfServiceResourceListContactDonationsOrder$outboundSchema,
      ),
      page: z.optional(z.int()),
      size: z.optional(z.int()),
      sort: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        donationOfferId: "donation_offer_id",
        includeOptOut: "include_opt_out",
        includeTotal: "include_total",
      });
    }),
  );

export function comCrmContactSelfServiceResourceListContactDonationsRequestToJSON(
  comCrmContactSelfServiceResourceListContactDonationsRequest:
    ComCrmContactSelfServiceResourceListContactDonationsRequest,
): string {
  return JSON.stringify(
    ComCrmContactSelfServiceResourceListContactDonationsRequest$outboundSchema
      .parse(comCrmContactSelfServiceResourceListContactDonationsRequest),
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceListContactDonationsPaging$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceListContactDonationsPaging,
    unknown
  > = z.pipe(
    z.object({
      page: types.optional(types.number()),
      size: types.optional(types.number()),
      total: types.optional(types.number()),
      has_more: types.optional(types.boolean()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "has_more": "hasMore",
      });
    }),
  );

export function comCrmContactSelfServiceResourceListContactDonationsPagingFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceListContactDonationsPaging,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceListContactDonationsPaging$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceListContactDonationsPaging' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceListContactDonationsCurrencyCode$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceListContactDonationsCurrencyCode,
    unknown
  > = openEnums.inboundSchema(
    ComCrmContactSelfServiceResourceListContactDonationsCurrencyCode,
  );

/** @internal */
export const ComCrmContactSelfServiceResourceListContactDonationsUsageType$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceListContactDonationsUsageType,
    unknown
  > = openEnums.inboundSchema(
    ComCrmContactSelfServiceResourceListContactDonationsUsageType,
  );

/** @internal */
export const ComCrmContactSelfServiceResourceListContactDonationsMedia$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceListContactDonationsMedia,
    unknown
  > = z.object({
    width: types.optional(types.number()),
    height: types.optional(types.number()),
    url: types.optional(types.string()),
  });

export function comCrmContactSelfServiceResourceListContactDonationsMediaFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceListContactDonationsMedia,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceListContactDonationsMedia$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceListContactDonationsMedia' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceListContactDonationsCreative$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceListContactDonationsCreative,
    unknown
  > = z.pipe(
    z.object({
      id: types.optional(types.string()),
      media_group_id: types.optional(types.string()),
      usage_type: types.optional(
        ComCrmContactSelfServiceResourceListContactDonationsUsageType$inboundSchema,
      ),
      width: types.optional(types.number()),
      height: types.optional(types.number()),
      format: types.optional(types.string()),
      url: types.optional(types.string()),
      public_id: types.optional(types.string()),
      media_id: types.optional(types.string()),
      caption: types.optional(types.string()),
      sort_order: types.optional(types.number()),
      media: types.optional(z.array(z.lazy(() =>
        ComCrmContactSelfServiceResourceListContactDonationsMedia$inboundSchema
      ))),
    }),
    z.transform((v) => {
      return remap$(v, {
        "media_group_id": "mediaGroupId",
        "usage_type": "usageType",
        "public_id": "publicId",
        "media_id": "mediaId",
        "sort_order": "sortOrder",
      });
    }),
  );

export function comCrmContactSelfServiceResourceListContactDonationsCreativeFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceListContactDonationsCreative,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceListContactDonationsCreative$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceListContactDonationsCreative' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceListContactDonationsDonationOffer$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceListContactDonationsDonationOffer,
    unknown
  > = z.object({
    id: types.optional(types.string()),
    name: types.optional(types.string()),
    creatives: types.optional(
      z.array(z.lazy(() =>
        ComCrmContactSelfServiceResourceListContactDonationsCreative$inboundSchema
      )),
    ),
  });

export function comCrmContactSelfServiceResourceListContactDonationsDonationOfferFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceListContactDonationsDonationOffer,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceListContactDonationsDonationOffer$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceListContactDonationsDonationOffer' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceListContactDonationsOrganisation$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceListContactDonationsOrganisation,
    unknown
  > = z.object({
    id: types.optional(types.string()),
    name: types.optional(types.string()),
  });

export function comCrmContactSelfServiceResourceListContactDonationsOrganisationFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceListContactDonationsOrganisation,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceListContactDonationsOrganisation$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceListContactDonationsOrganisation' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceListContactDonationsDetails$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceListContactDonationsDetails,
    unknown
  > = z.object({
    multiplier: z._default(types.number(), 1),
    amount: z._default(types.number(), 1),
  });

export function comCrmContactSelfServiceResourceListContactDonationsDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceListContactDonationsDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceListContactDonationsDetails$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceListContactDonationsDetails' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceListContactDonationsContent$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceListContactDonationsContent,
    unknown
  > = z.pipe(
    z.object({
      id: types.optional(types.string()),
      opted_in: types.optional(types.number()),
      opted_out: types.optional(types.number()),
      donations: types.optional(types.number()),
      amount: types.optional(types.number()),
      currency_code: types.optional(
        ComCrmContactSelfServiceResourceListContactDonationsCurrencyCode$inboundSchema,
      ),
      donation_offer: types.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceListContactDonationsDonationOffer$inboundSchema
      )),
      organisation: types.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceListContactDonationsOrganisation$inboundSchema
      )),
      details: types.optional(z.lazy(() =>
        ComCrmContactSelfServiceResourceListContactDonationsDetails$inboundSchema
      )),
    }),
    z.transform((v) => {
      return remap$(v, {
        "opted_in": "optedIn",
        "opted_out": "optedOut",
        "currency_code": "currencyCode",
        "donation_offer": "donationOffer",
      });
    }),
  );

export function comCrmContactSelfServiceResourceListContactDonationsContentFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceListContactDonationsContent,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceListContactDonationsContent$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceListContactDonationsContent' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceListContactDonationsResponse$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceListContactDonationsResponse,
    unknown
  > = z.object({
    paging: types.optional(
      z.lazy(() =>
        ComCrmContactSelfServiceResourceListContactDonationsPaging$inboundSchema
      ),
    ),
    content: types.optional(
      z.array(z.lazy(() =>
        ComCrmContactSelfServiceResourceListContactDonationsContent$inboundSchema
      )),
    ),
  });

export function comCrmContactSelfServiceResourceListContactDonationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceListContactDonationsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceListContactDonationsResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSelfServiceResourceListContactDonationsResponse' from JSON`,
  );
}
