/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ComCrmSubscriptionSelfServiceResourceChangeSecurity = {
  secretAPIKey: string;
};

/**
 * The change to be performed on the Subscription
 */
export const ComCrmSubscriptionSelfServiceResourceChangeAction = {
  ChangeBillingDay: "CHANGE_BILLING_DAY",
  ChangePaymentMethod: "CHANGE_PAYMENT_METHOD",
  Cancel: "CANCEL",
} as const;
/**
 * The change to be performed on the Subscription
 */
export type ComCrmSubscriptionSelfServiceResourceChangeAction = ClosedEnum<
  typeof ComCrmSubscriptionSelfServiceResourceChangeAction
>;

/**
 * Required when changing the billing day of the subscription's terms. A subscription's billing day can only be changed in Anniversary billing models
 */
export type ComCrmSubscriptionSelfServiceResourceChangeBillingDay = {
  /**
   * Day of week
   */
  dayOfWeek?: string | undefined;
  /**
   * Day of month
   */
  dayOfMonth?: number | undefined;
};

/**
 * Subscription Funding Source
 *
 * @deprecated enum: This will be removed in a future release, please migrate away from it as soon as possible.
 */
export const ComCrmSubscriptionSelfServiceResourceChangeFundingSource = {
  Account: "ACCOUNT",
  Wallet: "WALLET",
} as const;
/**
 * Subscription Funding Source
 *
 * @deprecated enum: This will be removed in a future release, please migrate away from it as soon as possible.
 */
export type ComCrmSubscriptionSelfServiceResourceChangeFundingSource =
  ClosedEnum<typeof ComCrmSubscriptionSelfServiceResourceChangeFundingSource>;

/**
 * The payment method’s type
 */
export const ComCrmSubscriptionSelfServiceResourceChangePaymentMethodType = {
  Card: "CARD",
  AccountDebit: "ACCOUNT_DEBIT",
  Wallet: "WALLET",
  CrmWallet: "CRM_WALLET",
  Cheque: "CHEQUE",
} as const;
/**
 * The payment method’s type
 */
export type ComCrmSubscriptionSelfServiceResourceChangePaymentMethodType =
  ClosedEnum<
    typeof ComCrmSubscriptionSelfServiceResourceChangePaymentMethodType
  >;

export type ComCrmSubscriptionSelfServiceResourceChangeRequestBody = {
  /**
   * The change to be performed on the Subscription
   */
  action: ComCrmSubscriptionSelfServiceResourceChangeAction;
  /**
   * One of the contact's/organisation's payment methods. Required when changing the payment preference of the subscription's terms
   */
  paymentMethodId?: string | undefined;
  /**
   * Required when changing the billing day of the subscription's terms. A subscription's billing day can only be changed in Anniversary billing models
   */
  billingDay?:
    | ComCrmSubscriptionSelfServiceResourceChangeBillingDay
    | undefined;
  /**
   * Subscription Funding Source
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  fundingSource?:
    | ComCrmSubscriptionSelfServiceResourceChangeFundingSource
    | undefined;
  /**
   * Schedule the update's execution on a future date. Applicable for Cancel action
   */
  scheduledDate?: number | undefined;
  /**
   * In case where business rules dectate an allowed date of execution for the update, set this fields to True so as the update will be automatically performed on the system's proposed scheduled date (instead of setting the scheduled_date manually). Applicable for Cancel action
   */
  useProposedDate?: boolean | undefined;
  /**
   * The payment method’s type
   */
  paymentMethodType?:
    | ComCrmSubscriptionSelfServiceResourceChangePaymentMethodType
    | undefined;
};

export type ComCrmSubscriptionSelfServiceResourceChangeRequest = {
  /**
   * The unique identifier of a subscription
   */
  id: string;
  body?: ComCrmSubscriptionSelfServiceResourceChangeRequestBody | undefined;
};

/**
 * OK
 */
export type ComCrmSubscriptionSelfServiceResourceChangeResponse = {
  /**
   * The entity identifier that will be created
   */
  id?: string | undefined;
  /**
   * A proposed date on which the requested changes can be scheduled to be executed. If a date is returned, then no action is logged yet and it has to be scheduled. A proposed scheduled date is returned when business rules do not allow the action's immediate execution
   */
  proposedDate?: number | undefined;
};

/** @internal */
export type ComCrmSubscriptionSelfServiceResourceChangeSecurity$Outbound = {
  Secret_API_key: string;
};

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceChangeSecurity$outboundSchema:
  z.ZodMiniType<
    ComCrmSubscriptionSelfServiceResourceChangeSecurity$Outbound,
    ComCrmSubscriptionSelfServiceResourceChangeSecurity
  > = z.pipe(
    z.object({
      secretAPIKey: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        secretAPIKey: "Secret_API_key",
      });
    }),
  );

export function comCrmSubscriptionSelfServiceResourceChangeSecurityToJSON(
  comCrmSubscriptionSelfServiceResourceChangeSecurity:
    ComCrmSubscriptionSelfServiceResourceChangeSecurity,
): string {
  return JSON.stringify(
    ComCrmSubscriptionSelfServiceResourceChangeSecurity$outboundSchema.parse(
      comCrmSubscriptionSelfServiceResourceChangeSecurity,
    ),
  );
}

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceChangeAction$outboundSchema:
  z.ZodMiniEnum<typeof ComCrmSubscriptionSelfServiceResourceChangeAction> = z
    .enum(ComCrmSubscriptionSelfServiceResourceChangeAction);

/** @internal */
export type ComCrmSubscriptionSelfServiceResourceChangeBillingDay$Outbound = {
  day_of_week?: string | undefined;
  day_of_month?: number | undefined;
};

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceChangeBillingDay$outboundSchema:
  z.ZodMiniType<
    ComCrmSubscriptionSelfServiceResourceChangeBillingDay$Outbound,
    ComCrmSubscriptionSelfServiceResourceChangeBillingDay
  > = z.pipe(
    z.object({
      dayOfWeek: z.optional(z.string()),
      dayOfMonth: z.optional(z.int()),
    }),
    z.transform((v) => {
      return remap$(v, {
        dayOfWeek: "day_of_week",
        dayOfMonth: "day_of_month",
      });
    }),
  );

export function comCrmSubscriptionSelfServiceResourceChangeBillingDayToJSON(
  comCrmSubscriptionSelfServiceResourceChangeBillingDay:
    ComCrmSubscriptionSelfServiceResourceChangeBillingDay,
): string {
  return JSON.stringify(
    ComCrmSubscriptionSelfServiceResourceChangeBillingDay$outboundSchema.parse(
      comCrmSubscriptionSelfServiceResourceChangeBillingDay,
    ),
  );
}

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceChangeFundingSource$outboundSchema:
  z.ZodMiniEnum<
    typeof ComCrmSubscriptionSelfServiceResourceChangeFundingSource
  > = z.enum(ComCrmSubscriptionSelfServiceResourceChangeFundingSource);

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceChangePaymentMethodType$outboundSchema:
  z.ZodMiniEnum<
    typeof ComCrmSubscriptionSelfServiceResourceChangePaymentMethodType
  > = z.enum(ComCrmSubscriptionSelfServiceResourceChangePaymentMethodType);

/** @internal */
export type ComCrmSubscriptionSelfServiceResourceChangeRequestBody$Outbound = {
  action: string;
  payment_method_id?: string | undefined;
  billing_day?:
    | ComCrmSubscriptionSelfServiceResourceChangeBillingDay$Outbound
    | undefined;
  funding_source: string;
  scheduled_date?: number | undefined;
  use_proposed_date: boolean;
  payment_method_type?: string | undefined;
};

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceChangeRequestBody$outboundSchema:
  z.ZodMiniType<
    ComCrmSubscriptionSelfServiceResourceChangeRequestBody$Outbound,
    ComCrmSubscriptionSelfServiceResourceChangeRequestBody
  > = z.pipe(
    z.object({
      action: ComCrmSubscriptionSelfServiceResourceChangeAction$outboundSchema,
      paymentMethodId: z.optional(z.string()),
      billingDay: z.optional(z.lazy(() =>
        ComCrmSubscriptionSelfServiceResourceChangeBillingDay$outboundSchema
      )),
      fundingSource: z._default(
        ComCrmSubscriptionSelfServiceResourceChangeFundingSource$outboundSchema,
        "ACCOUNT",
      ),
      scheduledDate: z.optional(z.int()),
      useProposedDate: z._default(z.boolean(), false),
      paymentMethodType: z.optional(
        ComCrmSubscriptionSelfServiceResourceChangePaymentMethodType$outboundSchema,
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        paymentMethodId: "payment_method_id",
        billingDay: "billing_day",
        fundingSource: "funding_source",
        scheduledDate: "scheduled_date",
        useProposedDate: "use_proposed_date",
        paymentMethodType: "payment_method_type",
      });
    }),
  );

export function comCrmSubscriptionSelfServiceResourceChangeRequestBodyToJSON(
  comCrmSubscriptionSelfServiceResourceChangeRequestBody:
    ComCrmSubscriptionSelfServiceResourceChangeRequestBody,
): string {
  return JSON.stringify(
    ComCrmSubscriptionSelfServiceResourceChangeRequestBody$outboundSchema.parse(
      comCrmSubscriptionSelfServiceResourceChangeRequestBody,
    ),
  );
}

/** @internal */
export type ComCrmSubscriptionSelfServiceResourceChangeRequest$Outbound = {
  id: string;
  body?:
    | ComCrmSubscriptionSelfServiceResourceChangeRequestBody$Outbound
    | undefined;
};

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceChangeRequest$outboundSchema:
  z.ZodMiniType<
    ComCrmSubscriptionSelfServiceResourceChangeRequest$Outbound,
    ComCrmSubscriptionSelfServiceResourceChangeRequest
  > = z.object({
    id: z.string(),
    body: z.optional(
      z.lazy(() =>
        ComCrmSubscriptionSelfServiceResourceChangeRequestBody$outboundSchema
      ),
    ),
  });

export function comCrmSubscriptionSelfServiceResourceChangeRequestToJSON(
  comCrmSubscriptionSelfServiceResourceChangeRequest:
    ComCrmSubscriptionSelfServiceResourceChangeRequest,
): string {
  return JSON.stringify(
    ComCrmSubscriptionSelfServiceResourceChangeRequest$outboundSchema.parse(
      comCrmSubscriptionSelfServiceResourceChangeRequest,
    ),
  );
}

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceChangeResponse$inboundSchema:
  z.ZodMiniType<ComCrmSubscriptionSelfServiceResourceChangeResponse, unknown> =
    z.pipe(
      z.object({
        id: types.optional(types.string()),
        proposed_date: types.optional(types.number()),
      }),
      z.transform((v) => {
        return remap$(v, {
          "proposed_date": "proposedDate",
        });
      }),
    );

export function comCrmSubscriptionSelfServiceResourceChangeResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmSubscriptionSelfServiceResourceChangeResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmSubscriptionSelfServiceResourceChangeResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmSubscriptionSelfServiceResourceChangeResponse' from JSON`,
  );
}
