/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cf4d9b9339c9
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ComCrmLanguageSelfServiceResourceGetSupportedLanguagesContent = {
  /**
   * The language (2-char code) that is supported
   */
  languageCode?: string | undefined;
};

/**
 * OK
 */
export type ComCrmLanguageSelfServiceResourceGetSupportedLanguagesResponse = {
  content?:
    | Array<ComCrmLanguageSelfServiceResourceGetSupportedLanguagesContent>
    | undefined;
};

/** @internal */
export const ComCrmLanguageSelfServiceResourceGetSupportedLanguagesContent$inboundSchema:
  z.ZodMiniType<
    ComCrmLanguageSelfServiceResourceGetSupportedLanguagesContent,
    unknown
  > = z.pipe(
    z.object({
      language_code: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "language_code": "languageCode",
      });
    }),
  );

export function comCrmLanguageSelfServiceResourceGetSupportedLanguagesContentFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmLanguageSelfServiceResourceGetSupportedLanguagesContent,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmLanguageSelfServiceResourceGetSupportedLanguagesContent$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmLanguageSelfServiceResourceGetSupportedLanguagesContent' from JSON`,
  );
}

/** @internal */
export const ComCrmLanguageSelfServiceResourceGetSupportedLanguagesResponse$inboundSchema:
  z.ZodMiniType<
    ComCrmLanguageSelfServiceResourceGetSupportedLanguagesResponse,
    unknown
  > = z.object({
    content: types.optional(
      z.array(z.lazy(() =>
        ComCrmLanguageSelfServiceResourceGetSupportedLanguagesContent$inboundSchema
      )),
    ),
  });

export function comCrmLanguageSelfServiceResourceGetSupportedLanguagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmLanguageSelfServiceResourceGetSupportedLanguagesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmLanguageSelfServiceResourceGetSupportedLanguagesResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmLanguageSelfServiceResourceGetSupportedLanguagesResponse' from JSON`,
  );
}
