/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ComCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequestBody =
  {
    comments?: string | undefined;
  };

export type ComCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequest =
  {
    /**
     * The token that will verify that the client is trusted and will reject the related request
     */
    token: string;
    body:
      ComCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequestBody;
  };

/** @internal */
export type ComCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequestBody$Outbound =
  {
    comments?: string | undefined;
  };

/** @internal */
export const ComCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequestBody$outboundSchema:
  z.ZodMiniType<
    ComCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequestBody$Outbound,
    ComCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequestBody
  > = z.object({
    comments: z.optional(z.string()),
  });

export function comCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequestBodyToJSON(
  comCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequestBody:
    ComCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequestBody,
): string {
  return JSON.stringify(
    ComCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequestBody$outboundSchema
      .parse(
        comCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequestBody,
      ),
  );
}

/** @internal */
export type ComCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequest$Outbound =
  {
    token: string;
    body:
      ComCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequestBody$Outbound;
  };

/** @internal */
export const ComCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequest$outboundSchema:
  z.ZodMiniType<
    ComCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequest$Outbound,
    ComCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequest
  > = z.object({
    token: z.string(),
    body: z.lazy(() =>
      ComCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequestBody$outboundSchema
    ),
  });

export function comCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequestToJSON(
  comCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequest:
    ComCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequest,
): string {
  return JSON.stringify(
    ComCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequest$outboundSchema
      .parse(
        comCrmApprovalRequestSelfServiceResourceRejectApprovalRequestActionRequest,
      ),
  );
}
