/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3f6075add73a
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Defines how the results will be ordered</br>Default:DESC
 */
export const ComCrmContactSettingSelfServiceResourceListCommunityRelationsOrder =
  {
    Asc: "ASC",
    Desc: "DESC",
  } as const;
/**
 * Defines how the results will be ordered</br>Default:DESC
 */
export type ComCrmContactSettingSelfServiceResourceListCommunityRelationsOrder =
  ClosedEnum<
    typeof ComCrmContactSettingSelfServiceResourceListCommunityRelationsOrder
  >;

export type ComCrmContactSettingSelfServiceResourceListCommunityRelationsRequest =
  {
    /**
     *  Determine if a "total" will be returned in paging reference. If set to True, then "total" is also returned but it will return up to 10K value. If set to False, then the "total" in paging is null.
     */
    includeTotal?: boolean | undefined;
    /**
     * Filter based on contact community relation name (behave as like)
     */
    name?: string | undefined;
    /**
     * Defines how the results will be ordered</br>Default:DESC
     */
    order?:
      | ComCrmContactSettingSelfServiceResourceListCommunityRelationsOrder
      | undefined;
    /**
     * The page number that should be retrieved</br>Default:1
     */
    page?: number | undefined;
    /**
     * The size (total records) of each page</br>Default:10
     */
    size?: number | undefined;
    /**
     * Defines on which attribute the results should be sorted</br>Default:CREATED_DATE
     */
    sort?: string | undefined;
  };

export type ComCrmContactSettingSelfServiceResourceListCommunityRelationsPaging =
  {
    /**
     * The page number
     */
    page?: number | undefined;
    /**
     * The number of records per page
     */
    size?: number | undefined;
    /**
     * The total number of records. If "include_total" is not specified, then this total is null. If "include_total" is specified, total has a value but it is accurate up to 10K records.
     */
    total?: number | undefined;
    /**
     * Shows if there are more records available to fetch
     */
    hasMore?: boolean | undefined;
  };

export type ComCrmContactSettingSelfServiceResourceListCommunityRelationsContent =
  {
    /**
     * The entity identifier
     */
    id?: string | undefined;
    /**
     * The contact community relation name
     */
    name?: string | undefined;
    /**
     * Determines whether this is the default community relation. A single Relation can be set as the default one.
     */
    isDefault?: boolean | undefined;
  };

/**
 * OK
 */
export type ComCrmContactSettingSelfServiceResourceListCommunityRelationsResponse =
  {
    paging?:
      | ComCrmContactSettingSelfServiceResourceListCommunityRelationsPaging
      | undefined;
    content?:
      | Array<
        ComCrmContactSettingSelfServiceResourceListCommunityRelationsContent
      >
      | undefined;
  };

/** @internal */
export const ComCrmContactSettingSelfServiceResourceListCommunityRelationsOrder$outboundSchema:
  z.ZodMiniEnum<
    typeof ComCrmContactSettingSelfServiceResourceListCommunityRelationsOrder
  > = z.enum(
    ComCrmContactSettingSelfServiceResourceListCommunityRelationsOrder,
  );

/** @internal */
export type ComCrmContactSettingSelfServiceResourceListCommunityRelationsRequest$Outbound =
  {
    include_total?: boolean | undefined;
    name?: string | undefined;
    order?: string | undefined;
    page?: number | undefined;
    size?: number | undefined;
    sort?: string | undefined;
  };

/** @internal */
export const ComCrmContactSettingSelfServiceResourceListCommunityRelationsRequest$outboundSchema:
  z.ZodMiniType<
    ComCrmContactSettingSelfServiceResourceListCommunityRelationsRequest$Outbound,
    ComCrmContactSettingSelfServiceResourceListCommunityRelationsRequest
  > = z.pipe(
    z.object({
      includeTotal: z.optional(z.boolean()),
      name: z.optional(z.string()),
      order: z.optional(
        ComCrmContactSettingSelfServiceResourceListCommunityRelationsOrder$outboundSchema,
      ),
      page: z.optional(z.int()),
      size: z.optional(z.int()),
      sort: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        includeTotal: "include_total",
      });
    }),
  );

export function comCrmContactSettingSelfServiceResourceListCommunityRelationsRequestToJSON(
  comCrmContactSettingSelfServiceResourceListCommunityRelationsRequest:
    ComCrmContactSettingSelfServiceResourceListCommunityRelationsRequest,
): string {
  return JSON.stringify(
    ComCrmContactSettingSelfServiceResourceListCommunityRelationsRequest$outboundSchema
      .parse(
        comCrmContactSettingSelfServiceResourceListCommunityRelationsRequest,
      ),
  );
}

/** @internal */
export const ComCrmContactSettingSelfServiceResourceListCommunityRelationsPaging$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSettingSelfServiceResourceListCommunityRelationsPaging,
    unknown
  > = z.pipe(
    z.object({
      page: types.optional(types.number()),
      size: types.optional(types.number()),
      total: types.optional(types.number()),
      has_more: types.optional(types.boolean()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "has_more": "hasMore",
      });
    }),
  );

export function comCrmContactSettingSelfServiceResourceListCommunityRelationsPagingFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSettingSelfServiceResourceListCommunityRelationsPaging,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSettingSelfServiceResourceListCommunityRelationsPaging$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSettingSelfServiceResourceListCommunityRelationsPaging' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSettingSelfServiceResourceListCommunityRelationsContent$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSettingSelfServiceResourceListCommunityRelationsContent,
    unknown
  > = z.pipe(
    z.object({
      id: types.optional(types.string()),
      name: types.optional(types.string()),
      is_default: types.optional(types.boolean()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "is_default": "isDefault",
      });
    }),
  );

export function comCrmContactSettingSelfServiceResourceListCommunityRelationsContentFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSettingSelfServiceResourceListCommunityRelationsContent,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSettingSelfServiceResourceListCommunityRelationsContent$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSettingSelfServiceResourceListCommunityRelationsContent' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSettingSelfServiceResourceListCommunityRelationsResponse$inboundSchema:
  z.ZodMiniType<
    ComCrmContactSettingSelfServiceResourceListCommunityRelationsResponse,
    unknown
  > = z.object({
    paging: types.optional(
      z.lazy(() =>
        ComCrmContactSettingSelfServiceResourceListCommunityRelationsPaging$inboundSchema
      ),
    ),
    content: types.optional(
      z.array(z.lazy(() =>
        ComCrmContactSettingSelfServiceResourceListCommunityRelationsContent$inboundSchema
      )),
    ),
  });

export function comCrmContactSettingSelfServiceResourceListCommunityRelationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSettingSelfServiceResourceListCommunityRelationsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSettingSelfServiceResourceListCommunityRelationsResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmContactSettingSelfServiceResourceListCommunityRelationsResponse' from JSON`,
  );
}
