/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ComCrmServiceRequestSelfServiceResourceCreateNoteRequestBody = {
  /**
   * The entity identifier that will be created
   */
  id?: string | undefined;
  /**
   * The actual note contents
   */
  note: string;
};

export type ComCrmServiceRequestSelfServiceResourceCreateNoteRequest = {
  /**
   * Service Request GUID for which the note is to be created
   */
  id: string;
  body?:
    | ComCrmServiceRequestSelfServiceResourceCreateNoteRequestBody
    | undefined;
};

/**
 * OK
 */
export type ComCrmServiceRequestSelfServiceResourceCreateNoteResponse = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
};

/** @internal */
export type ComCrmServiceRequestSelfServiceResourceCreateNoteRequestBody$Outbound =
  {
    id?: string | undefined;
    note: string;
  };

/** @internal */
export const ComCrmServiceRequestSelfServiceResourceCreateNoteRequestBody$outboundSchema:
  z.ZodMiniType<
    ComCrmServiceRequestSelfServiceResourceCreateNoteRequestBody$Outbound,
    ComCrmServiceRequestSelfServiceResourceCreateNoteRequestBody
  > = z.object({
    id: z.optional(z.string()),
    note: z.string(),
  });

export function comCrmServiceRequestSelfServiceResourceCreateNoteRequestBodyToJSON(
  comCrmServiceRequestSelfServiceResourceCreateNoteRequestBody:
    ComCrmServiceRequestSelfServiceResourceCreateNoteRequestBody,
): string {
  return JSON.stringify(
    ComCrmServiceRequestSelfServiceResourceCreateNoteRequestBody$outboundSchema
      .parse(comCrmServiceRequestSelfServiceResourceCreateNoteRequestBody),
  );
}

/** @internal */
export type ComCrmServiceRequestSelfServiceResourceCreateNoteRequest$Outbound =
  {
    id: string;
    body?:
      | ComCrmServiceRequestSelfServiceResourceCreateNoteRequestBody$Outbound
      | undefined;
  };

/** @internal */
export const ComCrmServiceRequestSelfServiceResourceCreateNoteRequest$outboundSchema:
  z.ZodMiniType<
    ComCrmServiceRequestSelfServiceResourceCreateNoteRequest$Outbound,
    ComCrmServiceRequestSelfServiceResourceCreateNoteRequest
  > = z.object({
    id: z.string(),
    body: z.optional(
      z.lazy(() =>
        ComCrmServiceRequestSelfServiceResourceCreateNoteRequestBody$outboundSchema
      ),
    ),
  });

export function comCrmServiceRequestSelfServiceResourceCreateNoteRequestToJSON(
  comCrmServiceRequestSelfServiceResourceCreateNoteRequest:
    ComCrmServiceRequestSelfServiceResourceCreateNoteRequest,
): string {
  return JSON.stringify(
    ComCrmServiceRequestSelfServiceResourceCreateNoteRequest$outboundSchema
      .parse(comCrmServiceRequestSelfServiceResourceCreateNoteRequest),
  );
}

/** @internal */
export const ComCrmServiceRequestSelfServiceResourceCreateNoteResponse$inboundSchema:
  z.ZodMiniType<
    ComCrmServiceRequestSelfServiceResourceCreateNoteResponse,
    unknown
  > = z.object({
    id: types.optional(types.string()),
  });

export function comCrmServiceRequestSelfServiceResourceCreateNoteResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmServiceRequestSelfServiceResourceCreateNoteResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmServiceRequestSelfServiceResourceCreateNoteResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmServiceRequestSelfServiceResourceCreateNoteResponse' from JSON`,
  );
}
