/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const ComCrmOrderSelfServiceResourceCreateOrderPaymentMethodType = {
  Cash: "CASH",
  Card: "CARD",
  Account: "ACCOUNT",
  AccountDebit: "ACCOUNT_DEBIT",
  A2A: "A2A",
  Phone: "PHONE",
  Token: "TOKEN",
  Wallet: "WALLET",
  Cheque: "CHEQUE",
  ElectronicTransfer: "ELECTRONIC_TRANSFER",
  CrmWallet: "CRM_WALLET",
  OneTimeCardPayment: "ONE_TIME_CARD_PAYMENT",
} as const;
export type ComCrmOrderSelfServiceResourceCreateOrderPaymentMethodType =
  ClosedEnum<typeof ComCrmOrderSelfServiceResourceCreateOrderPaymentMethodType>;

export type Payment = {
  paymentMethodType: ComCrmOrderSelfServiceResourceCreateOrderPaymentMethodType;
  /**
   * Defines how the order will be paid
   */
  paidOn?: string | undefined;
  /**
   * The payment method that was selected for this order
   */
  paymentMethodId?: string | null | undefined;
  /**
   * The payment amount
   */
  amount?: number | undefined;
  paymentToken?: string | null | undefined;
};

export type ComCrmOrderSelfServiceResourceCreateOrderDevice = {
  productId?: string | undefined;
  deviceIds?: Array<string> | undefined;
};

/**
 * A list of custom fields whose values can be set when creating or updating entities
 */
export type ComCrmOrderSelfServiceResourceCreateOrderCustomField = {
  /**
   * The custom field’s unique key
   */
  key?: string | undefined;
  /**
   * The custom field’s value
   */
  value?: string | undefined;
};

/**
 * The communication medium to be used to send the pass information to the recipient. Note: For electronic Gift passes - if the registered_contact information has been provided, then medium_type is not mandatory
 */
export const MediumType = {
  Email: "EMAIL",
  Sms: "SMS",
} as const;
/**
 * The communication medium to be used to send the pass information to the recipient. Note: For electronic Gift passes - if the registered_contact information has been provided, then medium_type is not mandatory
 */
export type MediumType = ClosedEnum<typeof MediumType>;

/**
 * 3-character country code based on ISO 3166
 */
export const ComCrmOrderSelfServiceResourceCreateOrderCountryCode = {
  Abw: "ABW",
  Afg: "AFG",
  Ago: "AGO",
  Aia: "AIA",
  Ala: "ALA",
  Alb: "ALB",
  And: "AND",
  Ant: "ANT",
  Are: "ARE",
  Arg: "ARG",
  Arm: "ARM",
  Asm: "ASM",
  Ata: "ATA",
  Atf: "ATF",
  Atg: "ATG",
  Aus: "AUS",
  Aut: "AUT",
  Aze: "AZE",
  Bdi: "BDI",
  Bel: "BEL",
  Ben: "BEN",
  Bes: "BES",
  Bfa: "BFA",
  Bgd: "BGD",
  Bgr: "BGR",
  Bhr: "BHR",
  Bhs: "BHS",
  Bih: "BIH",
  Blm: "BLM",
  Blr: "BLR",
  Blz: "BLZ",
  Bmu: "BMU",
  Bol: "BOL",
  Bra: "BRA",
  Brb: "BRB",
  Brn: "BRN",
  Btn: "BTN",
  Bvt: "BVT",
  Bwa: "BWA",
  Caf: "CAF",
  Can: "CAN",
  Cck: "CCK",
  Che: "CHE",
  Chl: "CHL",
  Chn: "CHN",
  Civ: "CIV",
  Cmr: "CMR",
  Cod: "COD",
  Cog: "COG",
  Cok: "COK",
  Col: "COL",
  Com: "COM",
  Cpv: "CPV",
  Cri: "CRI",
  Cub: "CUB",
  Cuw: "CUW",
  Cxr: "CXR",
  Cym: "CYM",
  Cyp: "CYP",
  Cze: "CZE",
  Deu: "DEU",
  Dji: "DJI",
  Dma: "DMA",
  Dnk: "DNK",
  Dom: "DOM",
  Dza: "DZA",
  Ecu: "ECU",
  Egy: "EGY",
  Eri: "ERI",
  Esh: "ESH",
  Esp: "ESP",
  Est: "EST",
  Eth: "ETH",
  Fin: "FIN",
  Fji: "FJI",
  Flk: "FLK",
  Fra: "FRA",
  Fro: "FRO",
  Fsm: "FSM",
  Gab: "GAB",
  Gbr: "GBR",
  Geo: "GEO",
  Ggy: "GGY",
  Gha: "GHA",
  Gib: "GIB",
  Gin: "GIN",
  Glp: "GLP",
  Gmb: "GMB",
  Gnb: "GNB",
  Gnq: "GNQ",
  Grc: "GRC",
  Grd: "GRD",
  Grl: "GRL",
  Gtm: "GTM",
  Guf: "GUF",
  Gum: "GUM",
  Guy: "GUY",
  Hkg: "HKG",
  Hmd: "HMD",
  Hnd: "HND",
  Hrv: "HRV",
  Hti: "HTI",
  Hun: "HUN",
  Idn: "IDN",
  Imn: "IMN",
  Ind: "IND",
  Iot: "IOT",
  Irl: "IRL",
  Irn: "IRN",
  Irq: "IRQ",
  Isl: "ISL",
  Isr: "ISR",
  Ita: "ITA",
  Jam: "JAM",
  Jey: "JEY",
  Jor: "JOR",
  Jpn: "JPN",
  Kaz: "KAZ",
  Ken: "KEN",
  Kgz: "KGZ",
  Khm: "KHM",
  Kir: "KIR",
  Kna: "KNA",
  Kor: "KOR",
  Kwt: "KWT",
  Lao: "LAO",
  Lbn: "LBN",
  Lbr: "LBR",
  Lby: "LBY",
  Lca: "LCA",
  Lie: "LIE",
  Lka: "LKA",
  Lso: "LSO",
  Ltu: "LTU",
  Lux: "LUX",
  Lva: "LVA",
  Mac: "MAC",
  Maf: "MAF",
  Mar: "MAR",
  Mco: "MCO",
  Mda: "MDA",
  Mdg: "MDG",
  Mdv: "MDV",
  Mex: "MEX",
  Mhl: "MHL",
  Mkd: "MKD",
  Mli: "MLI",
  Mlt: "MLT",
  Mmr: "MMR",
  Mne: "MNE",
  Mng: "MNG",
  Mnp: "MNP",
  Moz: "MOZ",
  Mrt: "MRT",
  Msr: "MSR",
  Mtq: "MTQ",
  Mus: "MUS",
  Mwi: "MWI",
  Mys: "MYS",
  Myt: "MYT",
  Nam: "NAM",
  Ncl: "NCL",
  Ner: "NER",
  Nfk: "NFK",
  Nga: "NGA",
  Nic: "NIC",
  Niu: "NIU",
  Nld: "NLD",
  Nor: "NOR",
  Npl: "NPL",
  Nru: "NRU",
  Nzl: "NZL",
  Omn: "OMN",
  Pak: "PAK",
  Pan: "PAN",
  Pcn: "PCN",
  Per: "PER",
  Phl: "PHL",
  Plw: "PLW",
  Png: "PNG",
  Pol: "POL",
  Pri: "PRI",
  Prk: "PRK",
  Prt: "PRT",
  Pry: "PRY",
  Pse: "PSE",
  Pyf: "PYF",
  Qat: "QAT",
  Reu: "REU",
  Rks: "RKS",
  Rou: "ROU",
  Rus: "RUS",
  Rwa: "RWA",
  Sau: "SAU",
  Sdn: "SDN",
  Sen: "SEN",
  Sgp: "SGP",
  Sgs: "SGS",
  Shn: "SHN",
  Sjm: "SJM",
  Slb: "SLB",
  Sle: "SLE",
  Slv: "SLV",
  Smr: "SMR",
  Som: "SOM",
  Spm: "SPM",
  Srb: "SRB",
  Ssd: "SSD",
  Stp: "STP",
  Sur: "SUR",
  Svk: "SVK",
  Svn: "SVN",
  Swe: "SWE",
  Swz: "SWZ",
  Sxm: "SXM",
  Syc: "SYC",
  Syr: "SYR",
  Tca: "TCA",
  Tcd: "TCD",
  Tgo: "TGO",
  Tha: "THA",
  Tjk: "TJK",
  Tkl: "TKL",
  Tkm: "TKM",
  Tls: "TLS",
  Ton: "TON",
  Tto: "TTO",
  Tun: "TUN",
  Tur: "TUR",
  Tuv: "TUV",
  Twn: "TWN",
  Tza: "TZA",
  Uga: "UGA",
  Ukr: "UKR",
  Umi: "UMI",
  Ury: "URY",
  Usa: "USA",
  Uzb: "UZB",
  Vat: "VAT",
  Vct: "VCT",
  Ven: "VEN",
  Vgb: "VGB",
  Vir: "VIR",
  Vnm: "VNM",
  Vut: "VUT",
  Wlf: "WLF",
  Wsm: "WSM",
  Yem: "YEM",
  Zaf: "ZAF",
  Zmb: "ZMB",
  Zwe: "ZWE",
} as const;
/**
 * 3-character country code based on ISO 3166
 */
export type ComCrmOrderSelfServiceResourceCreateOrderCountryCode = ClosedEnum<
  typeof ComCrmOrderSelfServiceResourceCreateOrderCountryCode
>;

/**
 * Details required if the pass is being created for a registered contact.
 */
export type RegisteredContact = {
  /**
   * The existing contact's unique id
   */
  contactId: string;
  /**
   * Wallet id of the existing contact
   */
  walletId: string;
};

/**
 * The recipient information.This is the registered/unregistered contact who will be redeeming the pass.
 */
export type Recipient = {
  /**
   * The recipient name
   */
  name: string;
  /**
   * The communication medium to be used to send the pass information to the recipient. Note: For electronic Gift passes - if the registered_contact information has been provided, then medium_type is not mandatory
   */
  mediumType: MediumType;
  /**
   * The value of the communication medium to be used to send the pass information Note: For electronic Gift passes - if the registered_contact information has been provided then medium_value is not mandatory
   */
  mediumValue?: string | undefined;
  /**
   * 3-character country code based on ISO 3166
   */
  countryCode?:
    | ComCrmOrderSelfServiceResourceCreateOrderCountryCode
    | undefined;
  /**
   * The 2-character language code in which the communication will be sent to the recipient. If not provided, the default language of the automation will be used
   */
  language?: string | undefined;
  /**
   * Details required if the pass is being created for a registered contact.
   */
  registeredContact?: RegisteredContact | undefined;
};

/**
 * Gift sender information
 */
export type GiftSender = {
  /**
   * Gift sender name
   */
  name: string;
  /**
   * A short message from the gift sender to accompany the gift pass
   */
  message?: string | undefined;
};

/**
 * The details of the e-gift pass to be created.
 */
export type ComCrmOrderSelfServiceResourceCreateOrderPass = {
  /**
   * The recipient information.This is the registered/unregistered contact who will be redeeming the pass.
   */
  recipient?: Recipient | undefined;
  /**
   * Gift sender information
   */
  giftSender?: GiftSender | undefined;
};

export type ComCrmOrderSelfServiceResourceCreateOrderRequest = {
  /**
   * The entity identifier that will be created
   */
  id?: string | undefined;
  /**
   * The estimation_id as this is returned back by the estimates/order Web API
   */
  estimationId: string;
  /**
   * Defines whether available wallet funds can be used on the order total amount. If wallet funds do not cover the entire order amount, then payment method will be used (not applicable for CRM_WALLET payment method)
   */
  useWalletFunds?: boolean | null | undefined;
  /**
   * Defines a specific amount that should be used on the order total amount (applicable only if “use_wallet_funds” is true)
   */
  walletFundsAmount?: number | null | undefined;
  /**
   * The order general notes
   */
  notes?: string | null | undefined;
  /**
   * The order intent in case you call payment intents flow
   */
  intentId?: string | null | undefined;
  /**
   * Defines whether available wallet funds can be used on the order total amount. If wallet funds do not cover the entire order amount, then payment method will be used
   */
  useAccountFunds?: boolean | null | undefined;
  accountFundsAmount?: number | undefined;
  /**
   * At least one payment method must be specified.
   */
  payments: Array<Payment>;
  /**
   * A list of devices unique identifiers
   */
  devices?: Array<ComCrmOrderSelfServiceResourceCreateOrderDevice> | undefined;
  customFields?:
    | Array<ComCrmOrderSelfServiceResourceCreateOrderCustomField>
    | null
    | undefined;
  /**
   * The details of the e-gift pass to be created.
   */
  pass?: ComCrmOrderSelfServiceResourceCreateOrderPass | undefined;
};

/**
 * Information about the organisation’s location
 */
export type ComCrmOrderSelfServiceResourceCreateOrderAddress = {
  /**
   * The address of the location
   */
  addressLine1?: string | undefined;
  /**
   * Additional address information about the location
   */
  addressLine2?: string | undefined;
  /**
   * The state/province/county of the location
   */
  stateProvinceCounty?: string | undefined;
  /**
   * The town/city of the location
   */
  townCity?: string | undefined;
  /**
   * The postal code of the location
   */
  postalCode?: string | undefined;
  /**
   * The latitude of the location
   */
  lat?: number | undefined;
  /**
   * The longitude of the location
   */
  lon?: number | undefined;
  /**
   * The Google textual identifier that uniquely identifies a location
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  googleplaceid?: string | undefined;
  /**
   * The Google textual identifier that uniquely identifies a location
   */
  googlePlaceId?: string | undefined;
};

/**
 * The organisation that will fulfill the Order
 */
export type ComCrmOrderSelfServiceResourceCreateOrderFulfilledBy = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
  /**
   * The name of the organisation
   */
  name?: string | undefined;
  /**
   * The organisation’s phone number
   */
  phone?: string | undefined;
  /**
   * Information about the organisation’s location
   */
  address?: ComCrmOrderSelfServiceResourceCreateOrderAddress | undefined;
};

export const ComCrmOrderSelfServiceResourceCreateOrderUot = {
  Second: "SECOND",
  Minute: "MINUTE",
  Hour: "HOUR",
  Day: "DAY",
  Week: "WEEK",
  Month: "MONTH",
  Year: "YEAR",
  Overall: "OVERALL",
} as const;
export type ComCrmOrderSelfServiceResourceCreateOrderUot = OpenEnum<
  typeof ComCrmOrderSelfServiceResourceCreateOrderUot
>;

/**
 * An estimation of the delivery time
 */
export type EstimatedDeliveryTime = {
  timeToDelivery?: number | undefined;
  uot?: ComCrmOrderSelfServiceResourceCreateOrderUot | undefined;
  /**
   * The actual delivery time
   */
  deliveryAt?: number | undefined;
};

/**
 * Created
 */
export type ComCrmOrderSelfServiceResourceCreateOrderResponse = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
  /**
   * The Order’s number
   */
  number?: string | undefined;
  /**
   * The organisation that will fulfill the Order
   */
  fulfilledBy?:
    | ComCrmOrderSelfServiceResourceCreateOrderFulfilledBy
    | undefined;
  /**
   * An estimation of the delivery time
   */
  estimatedDeliveryTime?: EstimatedDeliveryTime | undefined;
};

/** @internal */
export const ComCrmOrderSelfServiceResourceCreateOrderPaymentMethodType$outboundSchema:
  z.ZodMiniEnum<
    typeof ComCrmOrderSelfServiceResourceCreateOrderPaymentMethodType
  > = z.enum(ComCrmOrderSelfServiceResourceCreateOrderPaymentMethodType);

/** @internal */
export type Payment$Outbound = {
  payment_method_type: string;
  paid_on?: string | undefined;
  payment_method_id?: string | null | undefined;
  amount?: number | undefined;
  payment_token?: string | null | undefined;
};

/** @internal */
export const Payment$outboundSchema: z.ZodMiniType<Payment$Outbound, Payment> =
  z.pipe(
    z.object({
      paymentMethodType:
        ComCrmOrderSelfServiceResourceCreateOrderPaymentMethodType$outboundSchema,
      paidOn: z.optional(z.string()),
      paymentMethodId: z.optional(z.nullable(z.string())),
      amount: z.optional(z.number()),
      paymentToken: z.optional(z.nullable(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        paymentMethodType: "payment_method_type",
        paidOn: "paid_on",
        paymentMethodId: "payment_method_id",
        paymentToken: "payment_token",
      });
    }),
  );

export function paymentToJSON(payment: Payment): string {
  return JSON.stringify(Payment$outboundSchema.parse(payment));
}

/** @internal */
export type ComCrmOrderSelfServiceResourceCreateOrderDevice$Outbound = {
  product_id?: string | undefined;
  device_ids?: Array<string> | undefined;
};

/** @internal */
export const ComCrmOrderSelfServiceResourceCreateOrderDevice$outboundSchema:
  z.ZodMiniType<
    ComCrmOrderSelfServiceResourceCreateOrderDevice$Outbound,
    ComCrmOrderSelfServiceResourceCreateOrderDevice
  > = z.pipe(
    z.object({
      productId: z.optional(z.string()),
      deviceIds: z.optional(z.array(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        productId: "product_id",
        deviceIds: "device_ids",
      });
    }),
  );

export function comCrmOrderSelfServiceResourceCreateOrderDeviceToJSON(
  comCrmOrderSelfServiceResourceCreateOrderDevice:
    ComCrmOrderSelfServiceResourceCreateOrderDevice,
): string {
  return JSON.stringify(
    ComCrmOrderSelfServiceResourceCreateOrderDevice$outboundSchema.parse(
      comCrmOrderSelfServiceResourceCreateOrderDevice,
    ),
  );
}

/** @internal */
export type ComCrmOrderSelfServiceResourceCreateOrderCustomField$Outbound = {
  key?: string | undefined;
  value?: string | undefined;
};

/** @internal */
export const ComCrmOrderSelfServiceResourceCreateOrderCustomField$outboundSchema:
  z.ZodMiniType<
    ComCrmOrderSelfServiceResourceCreateOrderCustomField$Outbound,
    ComCrmOrderSelfServiceResourceCreateOrderCustomField
  > = z.object({
    key: z.optional(z.string()),
    value: z.optional(z.string()),
  });

export function comCrmOrderSelfServiceResourceCreateOrderCustomFieldToJSON(
  comCrmOrderSelfServiceResourceCreateOrderCustomField:
    ComCrmOrderSelfServiceResourceCreateOrderCustomField,
): string {
  return JSON.stringify(
    ComCrmOrderSelfServiceResourceCreateOrderCustomField$outboundSchema.parse(
      comCrmOrderSelfServiceResourceCreateOrderCustomField,
    ),
  );
}

/** @internal */
export const MediumType$outboundSchema: z.ZodMiniEnum<typeof MediumType> = z
  .enum(MediumType);

/** @internal */
export const ComCrmOrderSelfServiceResourceCreateOrderCountryCode$outboundSchema:
  z.ZodMiniEnum<typeof ComCrmOrderSelfServiceResourceCreateOrderCountryCode> = z
    .enum(ComCrmOrderSelfServiceResourceCreateOrderCountryCode);

/** @internal */
export type RegisteredContact$Outbound = {
  contact_id: string;
  wallet_id: string;
};

/** @internal */
export const RegisteredContact$outboundSchema: z.ZodMiniType<
  RegisteredContact$Outbound,
  RegisteredContact
> = z.pipe(
  z.object({
    contactId: z.string(),
    walletId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      contactId: "contact_id",
      walletId: "wallet_id",
    });
  }),
);

export function registeredContactToJSON(
  registeredContact: RegisteredContact,
): string {
  return JSON.stringify(
    RegisteredContact$outboundSchema.parse(registeredContact),
  );
}

/** @internal */
export type Recipient$Outbound = {
  name: string;
  medium_type: string;
  medium_value?: string | undefined;
  country_code?: string | undefined;
  language?: string | undefined;
  registered_contact?: RegisteredContact$Outbound | undefined;
};

/** @internal */
export const Recipient$outboundSchema: z.ZodMiniType<
  Recipient$Outbound,
  Recipient
> = z.pipe(
  z.object({
    name: z.string(),
    mediumType: MediumType$outboundSchema,
    mediumValue: z.optional(z.string()),
    countryCode: z.optional(
      ComCrmOrderSelfServiceResourceCreateOrderCountryCode$outboundSchema,
    ),
    language: z.optional(z.string()),
    registeredContact: z.optional(
      z.lazy(() => RegisteredContact$outboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      mediumType: "medium_type",
      mediumValue: "medium_value",
      countryCode: "country_code",
      registeredContact: "registered_contact",
    });
  }),
);

export function recipientToJSON(recipient: Recipient): string {
  return JSON.stringify(Recipient$outboundSchema.parse(recipient));
}

/** @internal */
export type GiftSender$Outbound = {
  name: string;
  message?: string | undefined;
};

/** @internal */
export const GiftSender$outboundSchema: z.ZodMiniType<
  GiftSender$Outbound,
  GiftSender
> = z.object({
  name: z.string(),
  message: z.optional(z.string()),
});

export function giftSenderToJSON(giftSender: GiftSender): string {
  return JSON.stringify(GiftSender$outboundSchema.parse(giftSender));
}

/** @internal */
export type ComCrmOrderSelfServiceResourceCreateOrderPass$Outbound = {
  recipient?: Recipient$Outbound | undefined;
  gift_sender?: GiftSender$Outbound | undefined;
};

/** @internal */
export const ComCrmOrderSelfServiceResourceCreateOrderPass$outboundSchema:
  z.ZodMiniType<
    ComCrmOrderSelfServiceResourceCreateOrderPass$Outbound,
    ComCrmOrderSelfServiceResourceCreateOrderPass
  > = z.pipe(
    z.object({
      recipient: z.optional(z.lazy(() => Recipient$outboundSchema)),
      giftSender: z.optional(z.lazy(() => GiftSender$outboundSchema)),
    }),
    z.transform((v) => {
      return remap$(v, {
        giftSender: "gift_sender",
      });
    }),
  );

export function comCrmOrderSelfServiceResourceCreateOrderPassToJSON(
  comCrmOrderSelfServiceResourceCreateOrderPass:
    ComCrmOrderSelfServiceResourceCreateOrderPass,
): string {
  return JSON.stringify(
    ComCrmOrderSelfServiceResourceCreateOrderPass$outboundSchema.parse(
      comCrmOrderSelfServiceResourceCreateOrderPass,
    ),
  );
}

/** @internal */
export type ComCrmOrderSelfServiceResourceCreateOrderRequest$Outbound = {
  id?: string | undefined;
  estimation_id: string;
  use_wallet_funds: boolean | null;
  wallet_funds_amount?: number | null | undefined;
  notes?: string | null | undefined;
  intent_id?: string | null | undefined;
  use_account_funds: boolean | null;
  account_funds_amount?: number | undefined;
  payments: Array<Payment$Outbound>;
  devices?:
    | Array<ComCrmOrderSelfServiceResourceCreateOrderDevice$Outbound>
    | undefined;
  custom_fields?:
    | Array<ComCrmOrderSelfServiceResourceCreateOrderCustomField$Outbound>
    | null
    | undefined;
  pass?: ComCrmOrderSelfServiceResourceCreateOrderPass$Outbound | undefined;
};

/** @internal */
export const ComCrmOrderSelfServiceResourceCreateOrderRequest$outboundSchema:
  z.ZodMiniType<
    ComCrmOrderSelfServiceResourceCreateOrderRequest$Outbound,
    ComCrmOrderSelfServiceResourceCreateOrderRequest
  > = z.pipe(
    z.object({
      id: z.optional(z.string()),
      estimationId: z.string(),
      useWalletFunds: z.nullable(z._default(z.boolean(), false)),
      walletFundsAmount: z.optional(z.nullable(z.number())),
      notes: z.optional(z.nullable(z.string())),
      intentId: z.optional(z.nullable(z.string())),
      useAccountFunds: z.nullable(z._default(z.boolean(), false)),
      accountFundsAmount: z.optional(z.number()),
      payments: z.array(z.lazy(() => Payment$outboundSchema)),
      devices: z.optional(z.array(z.lazy(() =>
        ComCrmOrderSelfServiceResourceCreateOrderDevice$outboundSchema
      ))),
      customFields: z.optional(z.nullable(z.array(z.lazy(() =>
        ComCrmOrderSelfServiceResourceCreateOrderCustomField$outboundSchema
      )))),
      pass: z.optional(z.lazy(() =>
        ComCrmOrderSelfServiceResourceCreateOrderPass$outboundSchema
      )),
    }),
    z.transform((v) => {
      return remap$(v, {
        estimationId: "estimation_id",
        useWalletFunds: "use_wallet_funds",
        walletFundsAmount: "wallet_funds_amount",
        intentId: "intent_id",
        useAccountFunds: "use_account_funds",
        accountFundsAmount: "account_funds_amount",
        customFields: "custom_fields",
      });
    }),
  );

export function comCrmOrderSelfServiceResourceCreateOrderRequestToJSON(
  comCrmOrderSelfServiceResourceCreateOrderRequest:
    ComCrmOrderSelfServiceResourceCreateOrderRequest,
): string {
  return JSON.stringify(
    ComCrmOrderSelfServiceResourceCreateOrderRequest$outboundSchema.parse(
      comCrmOrderSelfServiceResourceCreateOrderRequest,
    ),
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceCreateOrderAddress$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceCreateOrderAddress, unknown> = z
    .pipe(
      z.object({
        address_line_1: types.optional(types.string()),
        address_line_2: types.optional(types.string()),
        state_province_county: types.optional(types.string()),
        town_city: types.optional(types.string()),
        postal_code: types.optional(types.string()),
        lat: types.optional(types.number()),
        lon: types.optional(types.number()),
        googleplaceid: types.optional(types.string()),
        google_place_id: types.optional(types.string()),
      }),
      z.transform((v) => {
        return remap$(v, {
          "address_line_1": "addressLine1",
          "address_line_2": "addressLine2",
          "state_province_county": "stateProvinceCounty",
          "town_city": "townCity",
          "postal_code": "postalCode",
          "google_place_id": "googlePlaceId",
        });
      }),
    );

export function comCrmOrderSelfServiceResourceCreateOrderAddressFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceCreateOrderAddress,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceCreateOrderAddress$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmOrderSelfServiceResourceCreateOrderAddress' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceCreateOrderFulfilledBy$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceCreateOrderFulfilledBy, unknown> =
    z.object({
      id: types.optional(types.string()),
      name: types.optional(types.string()),
      phone: types.optional(types.string()),
      address: types.optional(
        z.lazy(() =>
          ComCrmOrderSelfServiceResourceCreateOrderAddress$inboundSchema
        ),
      ),
    });

export function comCrmOrderSelfServiceResourceCreateOrderFulfilledByFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceCreateOrderFulfilledBy,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceCreateOrderFulfilledBy$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmOrderSelfServiceResourceCreateOrderFulfilledBy' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceCreateOrderUot$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceCreateOrderUot, unknown> =
    openEnums.inboundSchema(ComCrmOrderSelfServiceResourceCreateOrderUot);

/** @internal */
export const EstimatedDeliveryTime$inboundSchema: z.ZodMiniType<
  EstimatedDeliveryTime,
  unknown
> = z.pipe(
  z.object({
    time_to_delivery: types.optional(types.number()),
    uot: types.optional(
      ComCrmOrderSelfServiceResourceCreateOrderUot$inboundSchema,
    ),
    delivery_at: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "time_to_delivery": "timeToDelivery",
      "delivery_at": "deliveryAt",
    });
  }),
);

export function estimatedDeliveryTimeFromJSON(
  jsonString: string,
): SafeParseResult<EstimatedDeliveryTime, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EstimatedDeliveryTime$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EstimatedDeliveryTime' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceCreateOrderResponse$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceCreateOrderResponse, unknown> = z
    .pipe(
      z.object({
        id: types.optional(types.string()),
        number: types.optional(types.string()),
        fulfilled_by: types.optional(z.lazy(() =>
          ComCrmOrderSelfServiceResourceCreateOrderFulfilledBy$inboundSchema
        )),
        estimated_delivery_time: types.optional(z.lazy(() =>
          EstimatedDeliveryTime$inboundSchema
        )),
      }),
      z.transform((v) => {
        return remap$(v, {
          "fulfilled_by": "fulfilledBy",
          "estimated_delivery_time": "estimatedDeliveryTime",
        });
      }),
    );

export function comCrmOrderSelfServiceResourceCreateOrderResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceCreateOrderResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceCreateOrderResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmOrderSelfServiceResourceCreateOrderResponse' from JSON`,
  );
}
