/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ComCrmContactSelfServiceResourceGetFilesSecurity = {
  secretAPIKey?: string | undefined;
  authorization?: string | undefined;
};

/**
 * Defines how the results will be ordered
 */
export const ComCrmContactSelfServiceResourceGetFilesOrder = {
  Asc: "ASC",
  Desc: "DESC",
} as const;
/**
 * Defines how the results will be ordered
 */
export type ComCrmContactSelfServiceResourceGetFilesOrder = ClosedEnum<
  typeof ComCrmContactSelfServiceResourceGetFilesOrder
>;

export type ComCrmContactSelfServiceResourceGetFilesRequest = {
  /**
   * The contact (identifier) for whom attachments will be retrieved
   */
  id: string;
  /**
   * Defines how the results will be ordered
   */
  order?: ComCrmContactSelfServiceResourceGetFilesOrder | undefined;
  /**
   * The page number that should be retrieved
   */
  page?: number | undefined;
  /**
   * The size (total records) of each page
   */
  size?: number | undefined;
  /**
   * Defines on which attribute the results should be sorted
   */
  sort?: string | undefined;
};

export type ComCrmContactSelfServiceResourceGetFilesPaging = {
  /**
   * The page number
   */
  page?: number | undefined;
  /**
   * The number of records per page
   */
  size?: number | undefined;
  /**
   * The total number of records. If "include_total" is not specified, then this total is null. If "include_total" is specified, total has a value but it is accurate up to 10K records.
   */
  total?: number | undefined;
  /**
   * Shows if there are more records available to fetch
   */
  hasMore?: boolean | undefined;
};

/**
 * The file mime type
 */
export const ComCrmContactSelfServiceResourceGetFilesMime = {
  Doc: "DOC",
  Docx: "DOCX",
  Xls: "XLS",
  Xlsx: "XLSX",
  Pdf: "PDF",
  Json: "JSON",
  Txt: "TXT",
  Log: "LOG",
  Csv: "CSV",
  Jpeg: "JPEG",
  Png: "PNG",
  Msg: "MSG",
  Eml: "EML",
  Svg: "SVG",
} as const;
/**
 * The file mime type
 */
export type ComCrmContactSelfServiceResourceGetFilesMime = OpenEnum<
  typeof ComCrmContactSelfServiceResourceGetFilesMime
>;

/**
 * The attached file details
 */
export type ComCrmContactSelfServiceResourceGetFilesFile = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
  /**
   * The entity name
   */
  name?: string | undefined;
  /**
   * The file mime type
   */
  mime?: ComCrmContactSelfServiceResourceGetFilesMime | undefined;
};

export type ComCrmContactSelfServiceResourceGetFilesContent = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
  /**
   * The attached file details
   */
  file?: ComCrmContactSelfServiceResourceGetFilesFile | undefined;
  /**
   * The attachment description
   */
  description?: string | undefined;
  /**
   * The attached URL endpoint
   */
  link?: string | undefined;
};

/**
 * OK
 */
export type ComCrmContactSelfServiceResourceGetFilesResponse = {
  paging?: ComCrmContactSelfServiceResourceGetFilesPaging | undefined;
  content?: Array<ComCrmContactSelfServiceResourceGetFilesContent> | undefined;
};

/** @internal */
export type ComCrmContactSelfServiceResourceGetFilesSecurity$Outbound = {
  Secret_API_key?: string | undefined;
  authorization?: string | undefined;
};

/** @internal */
export const ComCrmContactSelfServiceResourceGetFilesSecurity$outboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetFilesSecurity$Outbound,
    ComCrmContactSelfServiceResourceGetFilesSecurity
  > = z.pipe(
    z.object({
      secretAPIKey: z.optional(z.string()),
      authorization: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        secretAPIKey: "Secret_API_key",
      });
    }),
  );

export function comCrmContactSelfServiceResourceGetFilesSecurityToJSON(
  comCrmContactSelfServiceResourceGetFilesSecurity:
    ComCrmContactSelfServiceResourceGetFilesSecurity,
): string {
  return JSON.stringify(
    ComCrmContactSelfServiceResourceGetFilesSecurity$outboundSchema.parse(
      comCrmContactSelfServiceResourceGetFilesSecurity,
    ),
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetFilesOrder$outboundSchema:
  z.ZodMiniEnum<typeof ComCrmContactSelfServiceResourceGetFilesOrder> = z.enum(
    ComCrmContactSelfServiceResourceGetFilesOrder,
  );

/** @internal */
export type ComCrmContactSelfServiceResourceGetFilesRequest$Outbound = {
  id: string;
  order: string;
  page: number;
  size: number;
  sort: string;
};

/** @internal */
export const ComCrmContactSelfServiceResourceGetFilesRequest$outboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceGetFilesRequest$Outbound,
    ComCrmContactSelfServiceResourceGetFilesRequest
  > = z.object({
    id: z.string(),
    order: z._default(
      ComCrmContactSelfServiceResourceGetFilesOrder$outboundSchema,
      "DESC",
    ),
    page: z._default(z.int(), 1),
    size: z._default(z.int(), 10),
    sort: z._default(z.string(), "CREATED_DATE"),
  });

export function comCrmContactSelfServiceResourceGetFilesRequestToJSON(
  comCrmContactSelfServiceResourceGetFilesRequest:
    ComCrmContactSelfServiceResourceGetFilesRequest,
): string {
  return JSON.stringify(
    ComCrmContactSelfServiceResourceGetFilesRequest$outboundSchema.parse(
      comCrmContactSelfServiceResourceGetFilesRequest,
    ),
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetFilesPaging$inboundSchema:
  z.ZodMiniType<ComCrmContactSelfServiceResourceGetFilesPaging, unknown> = z
    .pipe(
      z.object({
        page: types.optional(types.number()),
        size: types.optional(types.number()),
        total: types.optional(types.number()),
        has_more: types.optional(types.boolean()),
      }),
      z.transform((v) => {
        return remap$(v, {
          "has_more": "hasMore",
        });
      }),
    );

export function comCrmContactSelfServiceResourceGetFilesPagingFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetFilesPaging,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetFilesPaging$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetFilesPaging' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetFilesMime$inboundSchema:
  z.ZodMiniType<ComCrmContactSelfServiceResourceGetFilesMime, unknown> =
    openEnums.inboundSchema(ComCrmContactSelfServiceResourceGetFilesMime);

/** @internal */
export const ComCrmContactSelfServiceResourceGetFilesFile$inboundSchema:
  z.ZodMiniType<ComCrmContactSelfServiceResourceGetFilesFile, unknown> = z
    .object({
      id: types.optional(types.string()),
      name: types.optional(types.string()),
      mime: types.optional(
        ComCrmContactSelfServiceResourceGetFilesMime$inboundSchema,
      ),
    });

export function comCrmContactSelfServiceResourceGetFilesFileFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetFilesFile,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetFilesFile$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetFilesFile' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetFilesContent$inboundSchema:
  z.ZodMiniType<ComCrmContactSelfServiceResourceGetFilesContent, unknown> = z
    .object({
      id: types.optional(types.string()),
      file: types.optional(
        z.lazy(() =>
          ComCrmContactSelfServiceResourceGetFilesFile$inboundSchema
        ),
      ),
      description: types.optional(types.string()),
      link: types.optional(types.string()),
    });

export function comCrmContactSelfServiceResourceGetFilesContentFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetFilesContent,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetFilesContent$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetFilesContent' from JSON`,
  );
}

/** @internal */
export const ComCrmContactSelfServiceResourceGetFilesResponse$inboundSchema:
  z.ZodMiniType<ComCrmContactSelfServiceResourceGetFilesResponse, unknown> = z
    .object({
      paging: types.optional(
        z.lazy(() =>
          ComCrmContactSelfServiceResourceGetFilesPaging$inboundSchema
        ),
      ),
      content: types.optional(
        z.array(z.lazy(() =>
          ComCrmContactSelfServiceResourceGetFilesContent$inboundSchema
        )),
      ),
    });

export function comCrmContactSelfServiceResourceGetFilesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmContactSelfServiceResourceGetFilesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmContactSelfServiceResourceGetFilesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmContactSelfServiceResourceGetFilesResponse' from JSON`,
  );
}
