/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * The date on which Orders were completed.
 */
export const CompletedOn = {
  CompletedOnLt: "completed_on[lt]",
  CompletedOnLte: "completed_on[lte]",
  CompletedOnGt: "completed_on[gt]",
  CompletedOnGte: "completed_on[gte]",
} as const;
/**
 * The date on which Orders were completed.
 */
export type CompletedOn = ClosedEnum<typeof CompletedOn>;

/**
 * Filters orders based on created date
 */
export const ComCrmOrderSelfServiceResourceListOrdersCreatedOn = {
  CreatedOnLt: "created_on[lt]",
  CreatedOnLte: "created_on[lte]",
  CreatedOnGt: "created_on[gt]",
  CreatedOnGte: "created_on[gte]",
} as const;
/**
 * Filters orders based on created date
 */
export type ComCrmOrderSelfServiceResourceListOrdersCreatedOn = ClosedEnum<
  typeof ComCrmOrderSelfServiceResourceListOrdersCreatedOn
>;

/**
 * Defines how delivery order was/will be provided - comma separated e.g. DIRECT_DELIVERY, COURIER_SERVICE
 */
export const DeliveryMethods = {
  DirectDelivery: "DIRECT_DELIVERY",
  CourierService: "COURIER_SERVICE",
  PickupPoint: "PICKUP_POINT",
} as const;
/**
 * Defines how delivery order was/will be provided - comma separated e.g. DIRECT_DELIVERY, COURIER_SERVICE
 */
export type DeliveryMethods = ClosedEnum<typeof DeliveryMethods>;

/**
 * The date on which scheduled Orders were delivered.
 */
export const ScheduledOn = {
  ScheduledOnLt: "scheduled_on[lt]",
  ScheduledOnLte: "scheduled_on[lte]",
  ScheduledOnGt: "scheduled_on[gt]",
  ScheduledOnGte: "scheduled_on[gte]",
} as const;
/**
 * The date on which scheduled Orders were delivered.
 */
export type ScheduledOn = ClosedEnum<typeof ScheduledOn>;

/**
 * Fitlers based on the order state
 */
export const ComCrmOrderSelfServiceResourceListOrdersQueryParamState = {
  New: "NEW",
  InProgress: "IN_PROGRESS",
  Completed: "COMPLETED",
  Cancelled: "CANCELLED",
} as const;
/**
 * Fitlers based on the order state
 */
export type ComCrmOrderSelfServiceResourceListOrdersQueryParamState =
  ClosedEnum<typeof ComCrmOrderSelfServiceResourceListOrdersQueryParamState>;

/**
 * Defines how order was/will be provided
 */
export const ComCrmOrderSelfServiceResourceListOrdersQueryParamSupplyMethod = {
  Delivery: "DELIVERY",
  PickUp: "PICK_UP",
  DirectSale: "DIRECT_SALE",
} as const;
/**
 * Defines how order was/will be provided
 */
export type ComCrmOrderSelfServiceResourceListOrdersQueryParamSupplyMethod =
  ClosedEnum<
    typeof ComCrmOrderSelfServiceResourceListOrdersQueryParamSupplyMethod
  >;

/**
 * Defines how the results will be ordered
 */
export const ComCrmOrderSelfServiceResourceListOrdersOrder = {
  Asc: "ASC",
  Desc: "DESC",
} as const;
/**
 * Defines how the results will be ordered
 */
export type ComCrmOrderSelfServiceResourceListOrdersOrder = ClosedEnum<
  typeof ComCrmOrderSelfServiceResourceListOrdersOrder
>;

export type ComCrmOrderSelfServiceResourceListOrdersRequest = {
  /**
   * The contact identifier whose orders will be retrieved
   */
  id: string;
  /**
   * The date on which Orders were completed.
   */
  completedOn?: CompletedOn | undefined;
  /**
   * Filters orders based on created date
   */
  createdOn?: ComCrmOrderSelfServiceResourceListOrdersCreatedOn | undefined;
  /**
   * Filters based on custom fields (key/value set should be semicolon separated)
   */
  customFields?: string | undefined;
  /**
   * Defines how delivery order was/will be provided - comma separated e.g. DIRECT_DELIVERY, COURIER_SERVICE
   */
  deliveryMethods?: DeliveryMethods | undefined;
  /**
   * Determines whether custom fields should be retrieved or not
   */
  includeCustomFields?: boolean | undefined;
  /**
   * The date on which scheduled Orders were delivered.
   */
  scheduledOn?: ScheduledOn | undefined;
  /**
   * Fitlers based on the order state
   */
  state?: ComCrmOrderSelfServiceResourceListOrdersQueryParamState | undefined;
  /**
   * Defines how order was/will be provided
   */
  supplyMethod?:
    | ComCrmOrderSelfServiceResourceListOrdersQueryParamSupplyMethod
    | undefined;
  /**
   * Determine if a "total" will be returned in paging reference. If set to True, then "total" is also returned but it will return up to 10K value. If set to False, then the "total" in paging is null.
   */
  includeTotal?: boolean | undefined;
  /**
   * Defines how the results will be ordered
   */
  order?: ComCrmOrderSelfServiceResourceListOrdersOrder | undefined;
  /**
   * The page number that should be retrieved
   */
  page?: number | undefined;
  /**
   * The size (total records) of each page
   */
  size?: number | undefined;
  /**
   * Defines on which attribute the results should be sorted
   */
  sort?: string | undefined;
};

export type ComCrmOrderSelfServiceResourceListOrdersPaging = {
  /**
   * The page number
   */
  page?: number | undefined;
  /**
   * The number of records per page
   */
  size?: number | undefined;
  /**
   * The total number of records. If "include_total" is not specified, then this total is null. If "include_total" is specified, total has a value but it is accurate up to 10K records.
   */
  total?: number | undefined;
  /**
   * Shows if there are more records available to fetch
   */
  hasMore?: boolean | undefined;
};

/**
 * Defines the order’ supply method
 */
export const ComCrmOrderSelfServiceResourceListOrdersContentSupplyMethod = {
  Delivery: "DELIVERY",
  PickUp: "PICK_UP",
  DirectSale: "DIRECT_SALE",
} as const;
/**
 * Defines the order’ supply method
 */
export type ComCrmOrderSelfServiceResourceListOrdersContentSupplyMethod =
  OpenEnum<typeof ComCrmOrderSelfServiceResourceListOrdersContentSupplyMethod>;

/**
 * The type of the event:
 *
 * @remarks
 *  * `DIRECT_DELIVERY` - Deliver locally by the business or the merchant
 *  * `COURIER_SERVICE` - Deliver by a courier service/shipping partner up
 *  * `PICKUP_POINT` - Deliver to a pick-up point
 */
export const ComCrmOrderSelfServiceResourceListOrdersDeliveryMethod = {
  DirectDelivery: "DIRECT_DELIVERY",
  CourierService: "COURIER_SERVICE",
  PickupPoint: "PICKUP_POINT",
} as const;
/**
 * The type of the event:
 *
 * @remarks
 *  * `DIRECT_DELIVERY` - Deliver locally by the business or the merchant
 *  * `COURIER_SERVICE` - Deliver by a courier service/shipping partner up
 *  * `PICKUP_POINT` - Deliver to a pick-up point
 */
export type ComCrmOrderSelfServiceResourceListOrdersDeliveryMethod = OpenEnum<
  typeof ComCrmOrderSelfServiceResourceListOrdersDeliveryMethod
>;

/**
 * The order’s life cycle state
 */
export const ComCrmOrderSelfServiceResourceListOrdersContentState = {
  New: "NEW",
  InProgress: "IN_PROGRESS",
  Completed: "COMPLETED",
  Cancelled: "CANCELLED",
  OnHold: "ON_HOLD",
} as const;
/**
 * The order’s life cycle state
 */
export type ComCrmOrderSelfServiceResourceListOrdersContentState = OpenEnum<
  typeof ComCrmOrderSelfServiceResourceListOrdersContentState
>;

/**
 * Details about the organisation
 */
export type ComCrmOrderSelfServiceResourceListOrdersFulfilledBy = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
  /**
   * The organisation name
   */
  name?: string | undefined;
};

export type ComCrmOrderSelfServiceResourceListOrdersDiscount = {
  /**
   * Total discount amount excluding taxes. This amount equals to the sum of all discount amounts among all invoiced items. Note that this amount does not include the taxed amount.
   */
  amount?: number | undefined;
  /**
   * The total discount amount including taxes
   */
  amountInclTax?: number | undefined;
};

export type ComCrmOrderSelfServiceResourceListOrdersStage = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
  /**
   * The entity name
   */
  name?: string | undefined;
};

/**
 * Allows contacts to specify their preferred billing day at the time of ordering. Optional but applicable only when Anniversary billing is enabled and the order includes termed services with billing cycles longer than a week.
 */
export type ComCrmOrderSelfServiceResourceListOrdersPreferredBillingDay = {
  /**
   * The subscription's billing day which can either be a day of a month (for subscriptions with billing cycles longer than a month) or a week day (for subscriptions with cycles of duration less than a month)
   */
  dayOfWeek?: string | undefined;
  /**
   * The subscription's billing day which can either be a day of a month (for subscriptions with billing cycles longer than a month) or a week day (for subscriptions with cycles of duration less than a month)
   */
  dayOfMonth?: number | undefined;
  /**
   * The subscription's billing month of year
   */
  monthOfYear?: string | undefined;
};

/**
 * A list of custom fields whose values can be set when creating or updating entities
 */
export type ComCrmOrderSelfServiceResourceListOrdersCustomField = {
  /**
   * The custom field’s unique key
   */
  key?: string | undefined;
  /**
   * The custom field’s value
   */
  value?: string | undefined;
};

/**
 * The order item state
 */
export const ComCrmOrderSelfServiceResourceListOrdersLifeCycleState = {
  PendingDelivery: "PENDING_DELIVERY",
  Delivered: "DELIVERED",
  PendingStockMovement: "PENDING_STOCK_MOVEMENT",
} as const;
/**
 * The order item state
 */
export type ComCrmOrderSelfServiceResourceListOrdersLifeCycleState = OpenEnum<
  typeof ComCrmOrderSelfServiceResourceListOrdersLifeCycleState
>;

/**
 * Product type classification
 */
export const ComCrmOrderSelfServiceResourceListOrdersClassification = {
  TermedService: "TERMED_SERVICE",
  UsageService: "USAGE_SERVICE",
  OneTimeService: "ONE_TIME_SERVICE",
  TraceablePhysicalGood: "TRACEABLE_PHYSICAL_GOOD",
  NonTraceablePhysicalGood: "NON_TRACEABLE_PHYSICAL_GOOD",
  ExpensesService: "EXPENSES_SERVICE",
} as const;
/**
 * Product type classification
 */
export type ComCrmOrderSelfServiceResourceListOrdersClassification = OpenEnum<
  typeof ComCrmOrderSelfServiceResourceListOrdersClassification
>;

/**
 * The discount provided to the ordered item
 */
export type ProductDiscount = {
  /**
   * The applied discount amount excluding taxes
   */
  amount?: number | undefined;
  /**
   * The applied disocunt with its taxed amount
   */
  amountInclTax?: number | undefined;
  /**
   * The applied discount percentage
   */
  percentage?: number | undefined;
};

export type VariantAttribute = {
  key?: string | undefined;
  value?: string | undefined;
  name?: string | undefined;
};

/**
 * Information about the creative type
 */
export const ComCrmOrderSelfServiceResourceListOrdersUsageType = {
  Logo: "LOGO",
  Background: "BACKGROUND",
  Avatar: "AVATAR",
  Hero: "HERO",
  Marketing: "MARKETING",
  Attachment: "ATTACHMENT",
  Profileimage: "PROFILEIMAGE",
  AppleLockscreenIcon: "APPLE_LOCKSCREEN_ICON",
  AppleLogoImage: "APPLE_LOGO_IMAGE",
  AppleStripImage: "APPLE_STRIP_IMAGE",
  GoogleLogoImage: "GOOGLE_LOGO_IMAGE",
  GoogleStripImage: "GOOGLE_STRIP_IMAGE",
  LandingPageLogoImage: "LANDING_PAGE_LOGO_IMAGE",
  LandingPageHeaderImage: "LANDING_PAGE_HEADER_IMAGE",
  LandingPageBackgroundImage: "LANDING_PAGE_BACKGROUND_IMAGE",
  DeliveryImage: "DELIVERY_IMAGE",
  PickupImage: "PICKUP_IMAGE",
  DirectSaleImage: "DIRECT_SALE_IMAGE",
  WalletImage: "WALLET_IMAGE",
  LandingPageImage: "LANDING_PAGE_IMAGE",
  AppLogo: "APP_LOGO",
  PartnerLogo: "PARTNER_LOGO",
  Carousel: "CAROUSEL",
  Shortcut: "SHORTCUT",
  ShortcutImage: "SHORTCUT_IMAGE",
  EmbeddedLinkImage: "EMBEDDED_LINK_IMAGE",
  Image: "IMAGE",
  AppLoaderImage: "APP_LOADER_IMAGE",
  MobileBackgroundImage: "MOBILE_BACKGROUND_IMAGE",
} as const;
/**
 * Information about the creative type
 */
export type ComCrmOrderSelfServiceResourceListOrdersUsageType = OpenEnum<
  typeof ComCrmOrderSelfServiceResourceListOrdersUsageType
>;

export type ComCrmOrderSelfServiceResourceListOrdersMedia = {
  /**
   * The transformed creative width
   */
  width?: number | undefined;
  /**
   * The transformed creative height
   */
  height?: number | undefined;
  /**
   * The transformed creative URL
   */
  url?: string | undefined;
};

export type ComCrmOrderSelfServiceResourceListOrdersCreative = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
  /**
   * the identifier of media
   */
  mediaGroupId?: string | undefined;
  /**
   * Information about the creative type
   */
  usageType?: ComCrmOrderSelfServiceResourceListOrdersUsageType | undefined;
  /**
   * The creative width
   */
  width?: number | undefined;
  /**
   * The creative height
   */
  height?: number | undefined;
  /**
   * The creative format
   */
  format?: string | undefined;
  /**
   * The creative content URL
   */
  url?: string | undefined;
  /**
   * The creative public identifier
   */
  publicId?: string | undefined;
  /**
   * The media identifier
   */
  mediaId?: string | undefined;
  /**
   * The creative caption used in cases where usage_type=CAROUSEL
   */
  caption?: string | undefined;
  /**
   * The creative sort order used in cases where usage_type=CAROUSEL
   */
  sortOrder?: number | undefined;
  /**
   * Information about the creative transformations
   */
  media?: Array<ComCrmOrderSelfServiceResourceListOrdersMedia> | undefined;
};

export type ComCrmOrderSelfServiceResourceListOrdersTag = {
  /**
   * The configuration tag identifier
   */
  tagId?: string | undefined;
  /**
   * Name of Tag
   */
  name?: string | undefined;
  /**
   * The tag color (hex code) that will be used for visual purposes
   */
  colour?: string | undefined;
};

/**
 * The bundle product
 */
export type ComCrmOrderSelfServiceResourceListOrdersBundledItemProduct = {
  /**
   * Product identifier
   */
  id?: string | undefined;
  /**
   * Prodcut sku
   */
  sku?: string | undefined;
  /**
   * Product name
   */
  name?: string | undefined;
};

export type ComCrmOrderSelfServiceResourceListOrdersBundledItem = {
  /**
   * The bundled order item's identifier
   */
  id?: string | undefined;
  /**
   * The bundle product
   */
  product?:
    | ComCrmOrderSelfServiceResourceListOrdersBundledItemProduct
    | undefined;
};

export const ComCrmOrderSelfServiceResourceListOrdersUot = {
  Second: "SECOND",
  Minute: "MINUTE",
  Hour: "HOUR",
  Day: "DAY",
  Week: "WEEK",
  Month: "MONTH",
  Year: "YEAR",
  Overall: "OVERALL",
} as const;
export type ComCrmOrderSelfServiceResourceListOrdersUot = OpenEnum<
  typeof ComCrmOrderSelfServiceResourceListOrdersUot
>;

export type ComCrmOrderSelfServiceResourceListOrdersBillingPeriod = {
  duration?: number | undefined;
  uot?: ComCrmOrderSelfServiceResourceListOrdersUot | undefined;
};

/**
 * The price terms of the ordered item. Applicable only when ordering termed and one-time services
 */
export type ComCrmOrderSelfServiceResourceListOrdersPriceTerms = {
  billingPeriod?:
    | ComCrmOrderSelfServiceResourceListOrdersBillingPeriod
    | undefined;
  autoRenew?: boolean | undefined;
};

/**
 * Details about the ordered product
 */
export type ComCrmOrderSelfServiceResourceListOrdersProduct = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
  /**
   * The product SKU
   */
  sku?: string | undefined;
  /**
   * The product name
   */
  name?: string | undefined;
  description?: string | undefined;
  /**
   * How many products were ordered
   */
  quantity?: number | undefined;
  /**
   * The unit price as defined in the order’s Invoice,excluding taxed amount
   */
  price?: number | undefined;
  /**
   * The order item’s sub-total. The sub-total includes the discount amount i.e. the discount is deducted from the product’s price
   */
  cost?: number | undefined;
  /**
   * Product type classification
   */
  classification?:
    | ComCrmOrderSelfServiceResourceListOrdersClassification
    | undefined;
  isStockable?: boolean | undefined;
  typeComposition?: string | undefined;
  /**
   * The applied tax amount
   */
  taxAmount?: number | undefined;
  netAmount?: number | undefined;
  /**
   * The discount provided to the ordered item
   */
  discount?: ProductDiscount | undefined;
  /**
   * The sub-total of the product before applying the discount. Tax amount is included
   */
  costBeforeDiscount?: number | undefined;
  variantAttributes?: Array<VariantAttribute> | undefined;
  /**
   * Creatives images for marketing includes the primary image and scaled versions to create a srcset
   */
  creatives?:
    | Array<ComCrmOrderSelfServiceResourceListOrdersCreative>
    | undefined;
  tags?: Array<ComCrmOrderSelfServiceResourceListOrdersTag> | undefined;
  bundledItem?: ComCrmOrderSelfServiceResourceListOrdersBundledItem | undefined;
  /**
   * The price terms of the ordered item. Applicable only when ordering termed and one-time services
   */
  priceTerms?: ComCrmOrderSelfServiceResourceListOrdersPriceTerms | undefined;
};

export type ComCrmOrderSelfServiceResourceListOrdersItem = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
  /**
   * The quantity of the ordered items
   */
  quantity?: number | undefined;
  notes?: string | undefined;
  /**
   * The order item state
   */
  lifeCycleState?:
    | ComCrmOrderSelfServiceResourceListOrdersLifeCycleState
    | undefined;
  /**
   * Details about the ordered product
   */
  product?: ComCrmOrderSelfServiceResourceListOrdersProduct | undefined;
};

export type ComCrmOrderSelfServiceResourceListOrdersContent = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
  /**
   * The order number
   */
  number?: string | undefined;
  /**
   * Defines the order’ supply method
   */
  supplyMethod?:
    | ComCrmOrderSelfServiceResourceListOrdersContentSupplyMethod
    | undefined;
  /**
   * The type of the event:
   *
   * @remarks
   *  * `DIRECT_DELIVERY` - Deliver locally by the business or the merchant
   *  * `COURIER_SERVICE` - Deliver by a courier service/shipping partner up
   *  * `PICKUP_POINT` - Deliver to a pick-up point
   */
  deliveryMethod?:
    | ComCrmOrderSelfServiceResourceListOrdersDeliveryMethod
    | undefined;
  /**
   * The order’s life cycle state
   */
  state?: ComCrmOrderSelfServiceResourceListOrdersContentState | undefined;
  /**
   * Indicates the Order that the contact marked as his/her favorite one. A single Order can be marked as a favorite.
   */
  isFavorite?: boolean | undefined;
  /**
   * The total cost of all order items. The cost equals to the total cost of the order’s invoice, taxes and discounts included
   */
  total?: number | undefined;
  /**
   * The amount that was used from wallet funds
   */
  walletFunds?: number | undefined;
  /**
   * The amount due. This is the due amount of the order’s invoice, calculated cosidering its due date
   */
  amountDue?: number | undefined;
  /**
   * The currency in which the Order will be/was paid
   */
  currency?: string | undefined;
  submittedDate?: number | undefined;
  /**
   * Details about the organisation
   */
  fulfilledBy?: ComCrmOrderSelfServiceResourceListOrdersFulfilledBy | undefined;
  /**
   * The amount of money that was collected to pay off the order’s invoice. This amount equals to the order’s cost minus wallet funds (if any)
   */
  amountToCollect?: number | undefined;
  discount?: ComCrmOrderSelfServiceResourceListOrdersDiscount | undefined;
  /**
   * Total cost of the order before applying the discount, if any. Tax amount is included
   */
  subTotal?: number | undefined;
  /**
   * The total net amount of all order items
   */
  netAmount?: number | undefined;
  /**
   * The tax amount of all order items
   */
  taxAmount?: number | undefined;
  /**
   * The total in default currency
   */
  totalDefaultCurrency?: number | undefined;
  /**
   * The exchange rate
   */
  exchangeRate?: number | undefined;
  /**
   * The default currency code
   */
  defaultCurrencyCode?: string | undefined;
  stage?: ComCrmOrderSelfServiceResourceListOrdersStage | undefined;
  /**
   * Allows contacts to specify their preferred billing day at the time of ordering. Optional but applicable only when Anniversary billing is enabled and the order includes termed services with billing cycles longer than a week.
   */
  preferredBillingDay?:
    | ComCrmOrderSelfServiceResourceListOrdersPreferredBillingDay
    | undefined;
  customFields?:
    | Array<ComCrmOrderSelfServiceResourceListOrdersCustomField>
    | undefined;
  /**
   * List of order items
   */
  items?: Array<ComCrmOrderSelfServiceResourceListOrdersItem> | undefined;
};

/**
 * OK
 */
export type ComCrmOrderSelfServiceResourceListOrdersResponse = {
  paging?: ComCrmOrderSelfServiceResourceListOrdersPaging | undefined;
  content?: Array<ComCrmOrderSelfServiceResourceListOrdersContent> | undefined;
};

/** @internal */
export const CompletedOn$outboundSchema: z.ZodMiniEnum<typeof CompletedOn> = z
  .enum(CompletedOn);

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersCreatedOn$outboundSchema:
  z.ZodMiniEnum<typeof ComCrmOrderSelfServiceResourceListOrdersCreatedOn> = z
    .enum(ComCrmOrderSelfServiceResourceListOrdersCreatedOn);

/** @internal */
export const DeliveryMethods$outboundSchema: z.ZodMiniEnum<
  typeof DeliveryMethods
> = z.enum(DeliveryMethods);

/** @internal */
export const ScheduledOn$outboundSchema: z.ZodMiniEnum<typeof ScheduledOn> = z
  .enum(ScheduledOn);

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersQueryParamState$outboundSchema:
  z.ZodMiniEnum<
    typeof ComCrmOrderSelfServiceResourceListOrdersQueryParamState
  > = z.enum(ComCrmOrderSelfServiceResourceListOrdersQueryParamState);

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersQueryParamSupplyMethod$outboundSchema:
  z.ZodMiniEnum<
    typeof ComCrmOrderSelfServiceResourceListOrdersQueryParamSupplyMethod
  > = z.enum(ComCrmOrderSelfServiceResourceListOrdersQueryParamSupplyMethod);

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersOrder$outboundSchema:
  z.ZodMiniEnum<typeof ComCrmOrderSelfServiceResourceListOrdersOrder> = z.enum(
    ComCrmOrderSelfServiceResourceListOrdersOrder,
  );

/** @internal */
export type ComCrmOrderSelfServiceResourceListOrdersRequest$Outbound = {
  id: string;
  completed_on?: string | undefined;
  created_on?: string | undefined;
  custom_fields?: string | undefined;
  delivery_methods?: string | undefined;
  include_custom_fields?: boolean | undefined;
  scheduled_on?: string | undefined;
  state?: string | undefined;
  supply_method?: string | undefined;
  include_total: boolean;
  order: string;
  page: number;
  size: number;
  sort: string;
};

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersRequest$outboundSchema:
  z.ZodMiniType<
    ComCrmOrderSelfServiceResourceListOrdersRequest$Outbound,
    ComCrmOrderSelfServiceResourceListOrdersRequest
  > = z.pipe(
    z.object({
      id: z.string(),
      completedOn: z.optional(CompletedOn$outboundSchema),
      createdOn: z.optional(
        ComCrmOrderSelfServiceResourceListOrdersCreatedOn$outboundSchema,
      ),
      customFields: z.optional(z.string()),
      deliveryMethods: z.optional(DeliveryMethods$outboundSchema),
      includeCustomFields: z.optional(z.boolean()),
      scheduledOn: z.optional(ScheduledOn$outboundSchema),
      state: z.optional(
        ComCrmOrderSelfServiceResourceListOrdersQueryParamState$outboundSchema,
      ),
      supplyMethod: z.optional(
        ComCrmOrderSelfServiceResourceListOrdersQueryParamSupplyMethod$outboundSchema,
      ),
      includeTotal: z._default(z.boolean(), false),
      order: z._default(
        ComCrmOrderSelfServiceResourceListOrdersOrder$outboundSchema,
        "DESC",
      ),
      page: z._default(z.int(), 1),
      size: z._default(z.int(), 10),
      sort: z._default(z.string(), "CREATED_DATE"),
    }),
    z.transform((v) => {
      return remap$(v, {
        completedOn: "completed_on",
        createdOn: "created_on",
        customFields: "custom_fields",
        deliveryMethods: "delivery_methods",
        includeCustomFields: "include_custom_fields",
        scheduledOn: "scheduled_on",
        supplyMethod: "supply_method",
        includeTotal: "include_total",
      });
    }),
  );

export function comCrmOrderSelfServiceResourceListOrdersRequestToJSON(
  comCrmOrderSelfServiceResourceListOrdersRequest:
    ComCrmOrderSelfServiceResourceListOrdersRequest,
): string {
  return JSON.stringify(
    ComCrmOrderSelfServiceResourceListOrdersRequest$outboundSchema.parse(
      comCrmOrderSelfServiceResourceListOrdersRequest,
    ),
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersPaging$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceListOrdersPaging, unknown> = z
    .pipe(
      z.object({
        page: types.optional(types.number()),
        size: types.optional(types.number()),
        total: types.optional(types.number()),
        has_more: types.optional(types.boolean()),
      }),
      z.transform((v) => {
        return remap$(v, {
          "has_more": "hasMore",
        });
      }),
    );

export function comCrmOrderSelfServiceResourceListOrdersPagingFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceListOrdersPaging,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceListOrdersPaging$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmOrderSelfServiceResourceListOrdersPaging' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersContentSupplyMethod$inboundSchema:
  z.ZodMiniType<
    ComCrmOrderSelfServiceResourceListOrdersContentSupplyMethod,
    unknown
  > = openEnums.inboundSchema(
    ComCrmOrderSelfServiceResourceListOrdersContentSupplyMethod,
  );

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersDeliveryMethod$inboundSchema:
  z.ZodMiniType<
    ComCrmOrderSelfServiceResourceListOrdersDeliveryMethod,
    unknown
  > = openEnums.inboundSchema(
    ComCrmOrderSelfServiceResourceListOrdersDeliveryMethod,
  );

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersContentState$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceListOrdersContentState, unknown> =
    openEnums.inboundSchema(
      ComCrmOrderSelfServiceResourceListOrdersContentState,
    );

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersFulfilledBy$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceListOrdersFulfilledBy, unknown> =
    z.object({
      id: types.optional(types.string()),
      name: types.optional(types.string()),
    });

export function comCrmOrderSelfServiceResourceListOrdersFulfilledByFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceListOrdersFulfilledBy,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceListOrdersFulfilledBy$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmOrderSelfServiceResourceListOrdersFulfilledBy' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersDiscount$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceListOrdersDiscount, unknown> = z
    .pipe(
      z.object({
        amount: types.optional(types.number()),
        amount_incl_tax: types.optional(types.number()),
      }),
      z.transform((v) => {
        return remap$(v, {
          "amount_incl_tax": "amountInclTax",
        });
      }),
    );

export function comCrmOrderSelfServiceResourceListOrdersDiscountFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceListOrdersDiscount,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceListOrdersDiscount$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmOrderSelfServiceResourceListOrdersDiscount' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersStage$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceListOrdersStage, unknown> = z
    .object({
      id: types.optional(types.string()),
      name: types.optional(types.string()),
    });

export function comCrmOrderSelfServiceResourceListOrdersStageFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceListOrdersStage,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceListOrdersStage$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmOrderSelfServiceResourceListOrdersStage' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersPreferredBillingDay$inboundSchema:
  z.ZodMiniType<
    ComCrmOrderSelfServiceResourceListOrdersPreferredBillingDay,
    unknown
  > = z.pipe(
    z.object({
      day_of_week: types.optional(types.string()),
      day_of_month: types.optional(types.number()),
      month_of_year: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "day_of_week": "dayOfWeek",
        "day_of_month": "dayOfMonth",
        "month_of_year": "monthOfYear",
      });
    }),
  );

export function comCrmOrderSelfServiceResourceListOrdersPreferredBillingDayFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceListOrdersPreferredBillingDay,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceListOrdersPreferredBillingDay$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmOrderSelfServiceResourceListOrdersPreferredBillingDay' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersCustomField$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceListOrdersCustomField, unknown> =
    z.object({
      key: types.optional(types.string()),
      value: types.optional(types.string()),
    });

export function comCrmOrderSelfServiceResourceListOrdersCustomFieldFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceListOrdersCustomField,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceListOrdersCustomField$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmOrderSelfServiceResourceListOrdersCustomField' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersLifeCycleState$inboundSchema:
  z.ZodMiniType<
    ComCrmOrderSelfServiceResourceListOrdersLifeCycleState,
    unknown
  > = openEnums.inboundSchema(
    ComCrmOrderSelfServiceResourceListOrdersLifeCycleState,
  );

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersClassification$inboundSchema:
  z.ZodMiniType<
    ComCrmOrderSelfServiceResourceListOrdersClassification,
    unknown
  > = openEnums.inboundSchema(
    ComCrmOrderSelfServiceResourceListOrdersClassification,
  );

/** @internal */
export const ProductDiscount$inboundSchema: z.ZodMiniType<
  ProductDiscount,
  unknown
> = z.pipe(
  z.object({
    amount: types.optional(types.number()),
    amount_incl_tax: types.optional(types.number()),
    percentage: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "amount_incl_tax": "amountInclTax",
    });
  }),
);

export function productDiscountFromJSON(
  jsonString: string,
): SafeParseResult<ProductDiscount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProductDiscount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProductDiscount' from JSON`,
  );
}

/** @internal */
export const VariantAttribute$inboundSchema: z.ZodMiniType<
  VariantAttribute,
  unknown
> = z.object({
  key: types.optional(types.string()),
  value: types.optional(types.string()),
  name: types.optional(types.string()),
});

export function variantAttributeFromJSON(
  jsonString: string,
): SafeParseResult<VariantAttribute, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VariantAttribute$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VariantAttribute' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersUsageType$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceListOrdersUsageType, unknown> =
    openEnums.inboundSchema(ComCrmOrderSelfServiceResourceListOrdersUsageType);

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersMedia$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceListOrdersMedia, unknown> = z
    .object({
      width: types.optional(types.number()),
      height: types.optional(types.number()),
      url: types.optional(types.string()),
    });

export function comCrmOrderSelfServiceResourceListOrdersMediaFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceListOrdersMedia,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceListOrdersMedia$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmOrderSelfServiceResourceListOrdersMedia' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersCreative$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceListOrdersCreative, unknown> = z
    .pipe(
      z.object({
        id: types.optional(types.string()),
        media_group_id: types.optional(types.string()),
        usage_type: types.optional(
          ComCrmOrderSelfServiceResourceListOrdersUsageType$inboundSchema,
        ),
        width: types.optional(types.number()),
        height: types.optional(types.number()),
        format: types.optional(types.string()),
        url: types.optional(types.string()),
        public_id: types.optional(types.string()),
        media_id: types.optional(types.string()),
        caption: types.optional(types.string()),
        sort_order: types.optional(types.number()),
        media: types.optional(z.array(z.lazy(() =>
          ComCrmOrderSelfServiceResourceListOrdersMedia$inboundSchema
        ))),
      }),
      z.transform((v) => {
        return remap$(v, {
          "media_group_id": "mediaGroupId",
          "usage_type": "usageType",
          "public_id": "publicId",
          "media_id": "mediaId",
          "sort_order": "sortOrder",
        });
      }),
    );

export function comCrmOrderSelfServiceResourceListOrdersCreativeFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceListOrdersCreative,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceListOrdersCreative$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmOrderSelfServiceResourceListOrdersCreative' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersTag$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceListOrdersTag, unknown> = z.pipe(
    z.object({
      tag_id: types.optional(types.string()),
      name: types.optional(types.string()),
      colour: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "tag_id": "tagId",
      });
    }),
  );

export function comCrmOrderSelfServiceResourceListOrdersTagFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceListOrdersTag,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceListOrdersTag$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmOrderSelfServiceResourceListOrdersTag' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersBundledItemProduct$inboundSchema:
  z.ZodMiniType<
    ComCrmOrderSelfServiceResourceListOrdersBundledItemProduct,
    unknown
  > = z.object({
    id: types.optional(types.string()),
    sku: types.optional(types.string()),
    name: types.optional(types.string()),
  });

export function comCrmOrderSelfServiceResourceListOrdersBundledItemProductFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceListOrdersBundledItemProduct,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceListOrdersBundledItemProduct$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmOrderSelfServiceResourceListOrdersBundledItemProduct' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersBundledItem$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceListOrdersBundledItem, unknown> =
    z.object({
      id: types.optional(types.string()),
      product: types.optional(
        z.lazy(() =>
          ComCrmOrderSelfServiceResourceListOrdersBundledItemProduct$inboundSchema
        ),
      ),
    });

export function comCrmOrderSelfServiceResourceListOrdersBundledItemFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceListOrdersBundledItem,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceListOrdersBundledItem$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmOrderSelfServiceResourceListOrdersBundledItem' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersUot$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceListOrdersUot, unknown> =
    openEnums.inboundSchema(ComCrmOrderSelfServiceResourceListOrdersUot);

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersBillingPeriod$inboundSchema:
  z.ZodMiniType<
    ComCrmOrderSelfServiceResourceListOrdersBillingPeriod,
    unknown
  > = z.object({
    duration: types.optional(types.number()),
    uot: types.optional(
      ComCrmOrderSelfServiceResourceListOrdersUot$inboundSchema,
    ),
  });

export function comCrmOrderSelfServiceResourceListOrdersBillingPeriodFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceListOrdersBillingPeriod,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceListOrdersBillingPeriod$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmOrderSelfServiceResourceListOrdersBillingPeriod' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersPriceTerms$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceListOrdersPriceTerms, unknown> = z
    .pipe(
      z.object({
        billing_period: types.optional(z.lazy(() =>
          ComCrmOrderSelfServiceResourceListOrdersBillingPeriod$inboundSchema
        )),
        auto_renew: types.optional(types.boolean()),
      }),
      z.transform((v) => {
        return remap$(v, {
          "billing_period": "billingPeriod",
          "auto_renew": "autoRenew",
        });
      }),
    );

export function comCrmOrderSelfServiceResourceListOrdersPriceTermsFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceListOrdersPriceTerms,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceListOrdersPriceTerms$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmOrderSelfServiceResourceListOrdersPriceTerms' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersProduct$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceListOrdersProduct, unknown> = z
    .pipe(
      z.object({
        id: types.optional(types.string()),
        sku: types.optional(types.string()),
        name: types.optional(types.string()),
        description: types.optional(types.string()),
        quantity: types.optional(types.number()),
        price: types.optional(types.number()),
        cost: types.optional(types.number()),
        classification: types.optional(
          ComCrmOrderSelfServiceResourceListOrdersClassification$inboundSchema,
        ),
        is_stockable: types.optional(types.boolean()),
        type_composition: types.optional(types.string()),
        tax_amount: types.optional(types.number()),
        net_amount: types.optional(types.number()),
        discount: types.optional(z.lazy(() => ProductDiscount$inboundSchema)),
        cost_before_discount: types.optional(types.number()),
        variant_attributes: types.optional(
          z.array(z.lazy(() => VariantAttribute$inboundSchema)),
        ),
        creatives: types.optional(z.array(z.lazy(() =>
          ComCrmOrderSelfServiceResourceListOrdersCreative$inboundSchema
        ))),
        tags: types.optional(z.array(z.lazy(() =>
          ComCrmOrderSelfServiceResourceListOrdersTag$inboundSchema
        ))),
        bundled_item: types.optional(z.lazy(() =>
          ComCrmOrderSelfServiceResourceListOrdersBundledItem$inboundSchema
        )),
        price_terms: types.optional(z.lazy(() =>
          ComCrmOrderSelfServiceResourceListOrdersPriceTerms$inboundSchema
        )),
      }),
      z.transform((v) => {
        return remap$(v, {
          "is_stockable": "isStockable",
          "type_composition": "typeComposition",
          "tax_amount": "taxAmount",
          "net_amount": "netAmount",
          "cost_before_discount": "costBeforeDiscount",
          "variant_attributes": "variantAttributes",
          "bundled_item": "bundledItem",
          "price_terms": "priceTerms",
        });
      }),
    );

export function comCrmOrderSelfServiceResourceListOrdersProductFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceListOrdersProduct,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceListOrdersProduct$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmOrderSelfServiceResourceListOrdersProduct' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersItem$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceListOrdersItem, unknown> = z.pipe(
    z.object({
      id: types.optional(types.string()),
      quantity: types.optional(types.number()),
      notes: types.optional(types.string()),
      life_cycle_state: types.optional(
        ComCrmOrderSelfServiceResourceListOrdersLifeCycleState$inboundSchema,
      ),
      product: types.optional(z.lazy(() =>
        ComCrmOrderSelfServiceResourceListOrdersProduct$inboundSchema
      )),
    }),
    z.transform((v) => {
      return remap$(v, {
        "life_cycle_state": "lifeCycleState",
      });
    }),
  );

export function comCrmOrderSelfServiceResourceListOrdersItemFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceListOrdersItem,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceListOrdersItem$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmOrderSelfServiceResourceListOrdersItem' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersContent$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceListOrdersContent, unknown> = z
    .pipe(
      z.object({
        id: types.optional(types.string()),
        number: types.optional(types.string()),
        supply_method: types.optional(
          ComCrmOrderSelfServiceResourceListOrdersContentSupplyMethod$inboundSchema,
        ),
        delivery_method: types.optional(
          ComCrmOrderSelfServiceResourceListOrdersDeliveryMethod$inboundSchema,
        ),
        state: types.optional(
          ComCrmOrderSelfServiceResourceListOrdersContentState$inboundSchema,
        ),
        is_favorite: types.optional(types.boolean()),
        total: types.optional(types.number()),
        wallet_funds: types.optional(types.number()),
        amount_due: types.optional(types.number()),
        currency: types.optional(types.string()),
        submitted_date: types.optional(types.number()),
        fulfilled_by: types.optional(z.lazy(() =>
          ComCrmOrderSelfServiceResourceListOrdersFulfilledBy$inboundSchema
        )),
        amount_to_collect: types.optional(types.number()),
        discount: types.optional(z.lazy(() =>
          ComCrmOrderSelfServiceResourceListOrdersDiscount$inboundSchema
        )),
        sub_total: types.optional(types.number()),
        net_amount: types.optional(types.number()),
        tax_amount: types.optional(types.number()),
        total_default_currency: types.optional(types.number()),
        exchange_rate: types.optional(types.number()),
        default_currency_code: types.optional(types.string()),
        stage: types.optional(z.lazy(() =>
          ComCrmOrderSelfServiceResourceListOrdersStage$inboundSchema
        )),
        preferred_billing_day: types.optional(z.lazy(() =>
          ComCrmOrderSelfServiceResourceListOrdersPreferredBillingDay$inboundSchema
        )),
        custom_fields: types.optional(z.array(z.lazy(() =>
          ComCrmOrderSelfServiceResourceListOrdersCustomField$inboundSchema
        ))),
        items: types.optional(z.array(z.lazy(() =>
          ComCrmOrderSelfServiceResourceListOrdersItem$inboundSchema
        ))),
      }),
      z.transform((v) => {
        return remap$(v, {
          "supply_method": "supplyMethod",
          "delivery_method": "deliveryMethod",
          "is_favorite": "isFavorite",
          "wallet_funds": "walletFunds",
          "amount_due": "amountDue",
          "submitted_date": "submittedDate",
          "fulfilled_by": "fulfilledBy",
          "amount_to_collect": "amountToCollect",
          "sub_total": "subTotal",
          "net_amount": "netAmount",
          "tax_amount": "taxAmount",
          "total_default_currency": "totalDefaultCurrency",
          "exchange_rate": "exchangeRate",
          "default_currency_code": "defaultCurrencyCode",
          "preferred_billing_day": "preferredBillingDay",
          "custom_fields": "customFields",
        });
      }),
    );

export function comCrmOrderSelfServiceResourceListOrdersContentFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceListOrdersContent,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceListOrdersContent$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmOrderSelfServiceResourceListOrdersContent' from JSON`,
  );
}

/** @internal */
export const ComCrmOrderSelfServiceResourceListOrdersResponse$inboundSchema:
  z.ZodMiniType<ComCrmOrderSelfServiceResourceListOrdersResponse, unknown> = z
    .object({
      paging: types.optional(
        z.lazy(() =>
          ComCrmOrderSelfServiceResourceListOrdersPaging$inboundSchema
        ),
      ),
      content: types.optional(
        z.array(z.lazy(() =>
          ComCrmOrderSelfServiceResourceListOrdersContent$inboundSchema
        )),
      ),
    });

export function comCrmOrderSelfServiceResourceListOrdersResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmOrderSelfServiceResourceListOrdersResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmOrderSelfServiceResourceListOrdersResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmOrderSelfServiceResourceListOrdersResponse' from JSON`,
  );
}
