/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6ec6f8e64837
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Defines how the results will be ordered
 */
export const ComCrmServiceRequestSelfServiceResourceGetFilesOrder = {
  Asc: "ASC",
  Desc: "DESC",
} as const;
/**
 * Defines how the results will be ordered
 */
export type ComCrmServiceRequestSelfServiceResourceGetFilesOrder = ClosedEnum<
  typeof ComCrmServiceRequestSelfServiceResourceGetFilesOrder
>;

export type ComCrmServiceRequestSelfServiceResourceGetFilesRequest = {
  /**
   * The service request (identifier) for which attachments will be retrieved
   */
  id: string;
  /**
   * Determine if a "total" will be returned in paging reference. If set to True, then "total" is also returned but it will return up to 10K value. If set to False, then the "total" in paging is null.
   */
  includeTotal?: boolean | undefined;
  /**
   * Defines how the results will be ordered
   */
  order?: ComCrmServiceRequestSelfServiceResourceGetFilesOrder | undefined;
  /**
   * The page number that should be retrieved
   */
  page?: number | undefined;
  /**
   * The size (total records) of each page
   */
  size?: number | undefined;
  /**
   * Defines on which attribute the results should be sorted
   */
  sort?: string | undefined;
};

export type ComCrmServiceRequestSelfServiceResourceGetFilesPaging = {
  /**
   * The page number
   */
  page?: number | undefined;
  /**
   * The number of records per page
   */
  size?: number | undefined;
  /**
   * The total number of records. If "include_total" is not specified, then this total is null. If "include_total" is specified, total has a value but it is accurate up to 10K records.
   */
  total?: number | undefined;
  /**
   * Shows if there are more records available to fetch
   */
  hasMore?: boolean | undefined;
};

/**
 * The file mime type
 */
export const ComCrmServiceRequestSelfServiceResourceGetFilesMime = {
  Doc: "DOC",
  Docx: "DOCX",
  Xls: "XLS",
  Xlsx: "XLSX",
  Pdf: "PDF",
  Json: "JSON",
  Txt: "TXT",
  Log: "LOG",
  Csv: "CSV",
  Jpeg: "JPEG",
  Png: "PNG",
  Msg: "MSG",
  Eml: "EML",
  Svg: "SVG",
} as const;
/**
 * The file mime type
 */
export type ComCrmServiceRequestSelfServiceResourceGetFilesMime = OpenEnum<
  typeof ComCrmServiceRequestSelfServiceResourceGetFilesMime
>;

/**
 * The attached file details
 */
export type ComCrmServiceRequestSelfServiceResourceGetFilesFile = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
  /**
   * The entity name
   */
  name?: string | undefined;
  /**
   * The file mime type
   */
  mime?: ComCrmServiceRequestSelfServiceResourceGetFilesMime | undefined;
};

export type ComCrmServiceRequestSelfServiceResourceGetFilesContent = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
  /**
   * The attached file details
   */
  file?: ComCrmServiceRequestSelfServiceResourceGetFilesFile | undefined;
  /**
   * The attachment description
   */
  description?: string | undefined;
  /**
   * The attached URL endpoint
   */
  link?: string | undefined;
};

/**
 * OK
 */
export type ComCrmServiceRequestSelfServiceResourceGetFilesResponse = {
  paging?: ComCrmServiceRequestSelfServiceResourceGetFilesPaging | undefined;
  content?:
    | Array<ComCrmServiceRequestSelfServiceResourceGetFilesContent>
    | undefined;
};

/** @internal */
export const ComCrmServiceRequestSelfServiceResourceGetFilesOrder$outboundSchema:
  z.ZodMiniEnum<typeof ComCrmServiceRequestSelfServiceResourceGetFilesOrder> = z
    .enum(ComCrmServiceRequestSelfServiceResourceGetFilesOrder);

/** @internal */
export type ComCrmServiceRequestSelfServiceResourceGetFilesRequest$Outbound = {
  id: string;
  include_total: boolean;
  order: string;
  page: number;
  size: number;
  sort: string;
};

/** @internal */
export const ComCrmServiceRequestSelfServiceResourceGetFilesRequest$outboundSchema:
  z.ZodMiniType<
    ComCrmServiceRequestSelfServiceResourceGetFilesRequest$Outbound,
    ComCrmServiceRequestSelfServiceResourceGetFilesRequest
  > = z.pipe(
    z.object({
      id: z.string(),
      includeTotal: z._default(z.boolean(), false),
      order: z._default(
        ComCrmServiceRequestSelfServiceResourceGetFilesOrder$outboundSchema,
        "DESC",
      ),
      page: z._default(z.int(), 1),
      size: z._default(z.int(), 10),
      sort: z._default(z.string(), "CREATED_DATE"),
    }),
    z.transform((v) => {
      return remap$(v, {
        includeTotal: "include_total",
      });
    }),
  );

export function comCrmServiceRequestSelfServiceResourceGetFilesRequestToJSON(
  comCrmServiceRequestSelfServiceResourceGetFilesRequest:
    ComCrmServiceRequestSelfServiceResourceGetFilesRequest,
): string {
  return JSON.stringify(
    ComCrmServiceRequestSelfServiceResourceGetFilesRequest$outboundSchema.parse(
      comCrmServiceRequestSelfServiceResourceGetFilesRequest,
    ),
  );
}

/** @internal */
export const ComCrmServiceRequestSelfServiceResourceGetFilesPaging$inboundSchema:
  z.ZodMiniType<
    ComCrmServiceRequestSelfServiceResourceGetFilesPaging,
    unknown
  > = z.pipe(
    z.object({
      page: types.optional(types.number()),
      size: types.optional(types.number()),
      total: types.optional(types.number()),
      has_more: types.optional(types.boolean()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "has_more": "hasMore",
      });
    }),
  );

export function comCrmServiceRequestSelfServiceResourceGetFilesPagingFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmServiceRequestSelfServiceResourceGetFilesPaging,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmServiceRequestSelfServiceResourceGetFilesPaging$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmServiceRequestSelfServiceResourceGetFilesPaging' from JSON`,
  );
}

/** @internal */
export const ComCrmServiceRequestSelfServiceResourceGetFilesMime$inboundSchema:
  z.ZodMiniType<ComCrmServiceRequestSelfServiceResourceGetFilesMime, unknown> =
    openEnums.inboundSchema(
      ComCrmServiceRequestSelfServiceResourceGetFilesMime,
    );

/** @internal */
export const ComCrmServiceRequestSelfServiceResourceGetFilesFile$inboundSchema:
  z.ZodMiniType<ComCrmServiceRequestSelfServiceResourceGetFilesFile, unknown> =
    z.object({
      id: types.optional(types.string()),
      name: types.optional(types.string()),
      mime: types.optional(
        ComCrmServiceRequestSelfServiceResourceGetFilesMime$inboundSchema,
      ),
    });

export function comCrmServiceRequestSelfServiceResourceGetFilesFileFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmServiceRequestSelfServiceResourceGetFilesFile,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmServiceRequestSelfServiceResourceGetFilesFile$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComCrmServiceRequestSelfServiceResourceGetFilesFile' from JSON`,
  );
}

/** @internal */
export const ComCrmServiceRequestSelfServiceResourceGetFilesContent$inboundSchema:
  z.ZodMiniType<
    ComCrmServiceRequestSelfServiceResourceGetFilesContent,
    unknown
  > = z.object({
    id: types.optional(types.string()),
    file: types.optional(
      z.lazy(() =>
        ComCrmServiceRequestSelfServiceResourceGetFilesFile$inboundSchema
      ),
    ),
    description: types.optional(types.string()),
    link: types.optional(types.string()),
  });

export function comCrmServiceRequestSelfServiceResourceGetFilesContentFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmServiceRequestSelfServiceResourceGetFilesContent,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmServiceRequestSelfServiceResourceGetFilesContent$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmServiceRequestSelfServiceResourceGetFilesContent' from JSON`,
  );
}

/** @internal */
export const ComCrmServiceRequestSelfServiceResourceGetFilesResponse$inboundSchema:
  z.ZodMiniType<
    ComCrmServiceRequestSelfServiceResourceGetFilesResponse,
    unknown
  > = z.object({
    paging: types.optional(
      z.lazy(() =>
        ComCrmServiceRequestSelfServiceResourceGetFilesPaging$inboundSchema
      ),
    ),
    content: types.optional(
      z.array(z.lazy(() =>
        ComCrmServiceRequestSelfServiceResourceGetFilesContent$inboundSchema
      )),
    ),
  });

export function comCrmServiceRequestSelfServiceResourceGetFilesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmServiceRequestSelfServiceResourceGetFilesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmServiceRequestSelfServiceResourceGetFilesResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmServiceRequestSelfServiceResourceGetFilesResponse' from JSON`,
  );
}
