/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ComCrmApprovalRequestSelfServiceResourceAcceptApprovalRequestRequest =
  {
    /**
     * The token that will verify that the client is trusted and will approve the related request
     */
    token: string;
  };

/** @internal */
export type ComCrmApprovalRequestSelfServiceResourceAcceptApprovalRequestRequest$Outbound =
  {
    token: string;
  };

/** @internal */
export const ComCrmApprovalRequestSelfServiceResourceAcceptApprovalRequestRequest$outboundSchema:
  z.ZodMiniType<
    ComCrmApprovalRequestSelfServiceResourceAcceptApprovalRequestRequest$Outbound,
    ComCrmApprovalRequestSelfServiceResourceAcceptApprovalRequestRequest
  > = z.object({
    token: z.string(),
  });

export function comCrmApprovalRequestSelfServiceResourceAcceptApprovalRequestRequestToJSON(
  comCrmApprovalRequestSelfServiceResourceAcceptApprovalRequestRequest:
    ComCrmApprovalRequestSelfServiceResourceAcceptApprovalRequestRequest,
): string {
  return JSON.stringify(
    ComCrmApprovalRequestSelfServiceResourceAcceptApprovalRequestRequest$outboundSchema
      .parse(
        comCrmApprovalRequestSelfServiceResourceAcceptApprovalRequestRequest,
      ),
  );
}
