/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f48714c38b72
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Defines how the results will be ordered
 */
export const ComCrmRewardOfferDonationsSelfServiceResourceListOrder = {
  Asc: "ASC",
  Desc: "DESC",
} as const;
/**
 * Defines how the results will be ordered
 */
export type ComCrmRewardOfferDonationsSelfServiceResourceListOrder = ClosedEnum<
  typeof ComCrmRewardOfferDonationsSelfServiceResourceListOrder
>;

export type ComCrmRewardOfferDonationsSelfServiceResourceListRequest = {
  /**
   * Filter based on organisation (identifier) that such reward offer is donating to
   */
  donatedTo?: string | undefined;
  /**
   * The donation offer id
   */
  donationOfferId?: string | undefined;
  /**
   * Filter based on donation type
   */
  donationTypes?: string | undefined;
  /**
   * Filter based on organisation (identifier) that such reward offer is targeting to
   */
  organisations?: string | undefined;
  /**
   * Filter based on organisation (identifier) that such donations are owned (created by) by them
   */
  owner?: string | undefined;
  /**
   * Filter based on search value (case insensitive) across name
   */
  searchValue?: string | undefined;
  /**
   * Filter based on type
   */
  types?: string | undefined;
  /**
   * Determine if a "total" will be returned in paging reference. If set to True, then "total" is also returned but it will return up to 10K value. If set to False, then the "total" in paging is null.
   */
  includeTotal?: boolean | undefined;
  /**
   * Defines how the results will be ordered
   */
  order?: ComCrmRewardOfferDonationsSelfServiceResourceListOrder | undefined;
  /**
   * The page number that should be retrieved
   */
  page?: number | undefined;
  /**
   * The size (total records) of each page
   */
  size?: number | undefined;
  /**
   * Defines on which attribute the results should be sorted
   */
  sort?: string | undefined;
};

export type ComCrmRewardOfferDonationsSelfServiceResourceListPaging = {
  /**
   * The page number
   */
  page?: number | undefined;
  /**
   * The number of records per page
   */
  size?: number | undefined;
  /**
   * The total number of records. If "include_total" is not specified, then this total is null. If "include_total" is specified, total has a value but it is accurate up to 10K records.
   */
  total?: number | undefined;
  /**
   * Shows if there are more records available to fetch
   */
  hasMore?: boolean | undefined;
};

/**
 * Information about the creative type
 */
export const ComCrmRewardOfferDonationsSelfServiceResourceListUsageType = {
  Logo: "LOGO",
  Background: "BACKGROUND",
  Avatar: "AVATAR",
  Hero: "HERO",
  Marketing: "MARKETING",
  Attachment: "ATTACHMENT",
  Profileimage: "PROFILEIMAGE",
  AppleLockscreenIcon: "APPLE_LOCKSCREEN_ICON",
  AppleLogoImage: "APPLE_LOGO_IMAGE",
  AppleStripImage: "APPLE_STRIP_IMAGE",
  GoogleLogoImage: "GOOGLE_LOGO_IMAGE",
  GoogleStripImage: "GOOGLE_STRIP_IMAGE",
  LandingPageLogoImage: "LANDING_PAGE_LOGO_IMAGE",
  LandingPageHeaderImage: "LANDING_PAGE_HEADER_IMAGE",
  LandingPageBackgroundImage: "LANDING_PAGE_BACKGROUND_IMAGE",
  DeliveryImage: "DELIVERY_IMAGE",
  PickupImage: "PICKUP_IMAGE",
  DirectSaleImage: "DIRECT_SALE_IMAGE",
  WalletImage: "WALLET_IMAGE",
  LandingPageImage: "LANDING_PAGE_IMAGE",
  AppLogo: "APP_LOGO",
  PartnerLogo: "PARTNER_LOGO",
  Carousel: "CAROUSEL",
  Shortcut: "SHORTCUT",
  ShortcutImage: "SHORTCUT_IMAGE",
  EmbeddedLinkImage: "EMBEDDED_LINK_IMAGE",
  Image: "IMAGE",
  AppLoaderImage: "APP_LOADER_IMAGE",
  MobileBackgroundImage: "MOBILE_BACKGROUND_IMAGE",
} as const;
/**
 * Information about the creative type
 */
export type ComCrmRewardOfferDonationsSelfServiceResourceListUsageType =
  OpenEnum<typeof ComCrmRewardOfferDonationsSelfServiceResourceListUsageType>;

export type ComCrmRewardOfferDonationsSelfServiceResourceListMedia = {
  /**
   * The transformed creative width
   */
  width?: number | undefined;
  /**
   * The transformed creative height
   */
  height?: number | undefined;
  /**
   * The transformed creative URL
   */
  url?: string | undefined;
};

export type ComCrmRewardOfferDonationsSelfServiceResourceListCreative = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
  /**
   * the identifier of media
   */
  mediaGroupId?: string | undefined;
  /**
   * Information about the creative type
   */
  usageType?:
    | ComCrmRewardOfferDonationsSelfServiceResourceListUsageType
    | undefined;
  /**
   * The creative width
   */
  width?: number | undefined;
  /**
   * The creative height
   */
  height?: number | undefined;
  /**
   * The creative format
   */
  format?: string | undefined;
  /**
   * The creative content URL
   */
  url?: string | undefined;
  /**
   * The creative public identifier
   */
  publicId?: string | undefined;
  /**
   * The media identifier
   */
  mediaId?: string | undefined;
  /**
   * The creative caption used in cases where usage_type=CAROUSEL
   */
  caption?: string | undefined;
  /**
   * The creative sort order used in cases where usage_type=CAROUSEL
   */
  sortOrder?: number | undefined;
  /**
   * Information about the creative transformations
   */
  media?:
    | Array<ComCrmRewardOfferDonationsSelfServiceResourceListMedia>
    | undefined;
};

/**
 * Defines how the donated amount will be calculated on each donation made by the contact. In Spare Change and Fixed types, the business defines the donated amount’s rules, whereas in Variable type, the contact decides how much to donate.
 */
export const ComCrmRewardOfferDonationsSelfServiceResourceListDonationType = {
  PerTransaction: "PER_TRANSACTION",
  Termed: "TERMED",
  Variable: "VARIABLE",
} as const;
/**
 * Defines how the donated amount will be calculated on each donation made by the contact. In Spare Change and Fixed types, the business defines the donated amount’s rules, whereas in Variable type, the contact decides how much to donate.
 */
export type ComCrmRewardOfferDonationsSelfServiceResourceListDonationType =
  OpenEnum<
    typeof ComCrmRewardOfferDonationsSelfServiceResourceListDonationType
  >;

/**
 * The offer type (each goal is related with a type)
 */
export const ComCrmRewardOfferDonationsSelfServiceResourceListType = {
  Gift: "GIFT",
  Discount: "DISCOUNT",
  Bundle: "BUNDLE",
  OneOff: "ONE_OFF",
} as const;
/**
 * The offer type (each goal is related with a type)
 */
export type ComCrmRewardOfferDonationsSelfServiceResourceListType = OpenEnum<
  typeof ComCrmRewardOfferDonationsSelfServiceResourceListType
>;

export type ComCrmRewardOfferDonationsSelfServiceResourceListContent = {
  /**
   * The entity identifier
   */
  id?: string | undefined;
  /**
   * The Donation Offer name
   */
  name?: string | undefined;
  /**
   * Details about creatives. A creative is an object that contains all the data required for visually rendering an image responsively, such as the initial image and a number of scale versions of it (srcset)
   */
  creatives?:
    | Array<ComCrmRewardOfferDonationsSelfServiceResourceListCreative>
    | undefined;
  /**
   * Defines how the donated amount will be calculated on each donation made by the contact. In Spare Change and Fixed types, the business defines the donated amount’s rules, whereas in Variable type, the contact decides how much to donate.
   */
  donationType?:
    | ComCrmRewardOfferDonationsSelfServiceResourceListDonationType
    | undefined;
  /**
   * The offer type (each goal is related with a type)
   */
  type?: ComCrmRewardOfferDonationsSelfServiceResourceListType | undefined;
  /**
   * The donation's amount. Applicable only for termed donation offers.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  termedAmount?: number | undefined;
};

/**
 * OK
 */
export type ComCrmRewardOfferDonationsSelfServiceResourceListResponse = {
  paging?: ComCrmRewardOfferDonationsSelfServiceResourceListPaging | undefined;
  content?:
    | Array<ComCrmRewardOfferDonationsSelfServiceResourceListContent>
    | undefined;
};

/** @internal */
export const ComCrmRewardOfferDonationsSelfServiceResourceListOrder$outboundSchema:
  z.ZodMiniEnum<typeof ComCrmRewardOfferDonationsSelfServiceResourceListOrder> =
    z.enum(ComCrmRewardOfferDonationsSelfServiceResourceListOrder);

/** @internal */
export type ComCrmRewardOfferDonationsSelfServiceResourceListRequest$Outbound =
  {
    donated_to?: string | undefined;
    donation_offer_id?: string | undefined;
    donation_types?: string | undefined;
    organisations?: string | undefined;
    owner?: string | undefined;
    search_value?: string | undefined;
    types?: string | undefined;
    include_total: boolean;
    order: string;
    page: number;
    size: number;
    sort: string;
  };

/** @internal */
export const ComCrmRewardOfferDonationsSelfServiceResourceListRequest$outboundSchema:
  z.ZodMiniType<
    ComCrmRewardOfferDonationsSelfServiceResourceListRequest$Outbound,
    ComCrmRewardOfferDonationsSelfServiceResourceListRequest
  > = z.pipe(
    z.object({
      donatedTo: z.optional(z.string()),
      donationOfferId: z.optional(z.string()),
      donationTypes: z.optional(z.string()),
      organisations: z.optional(z.string()),
      owner: z.optional(z.string()),
      searchValue: z.optional(z.string()),
      types: z.optional(z.string()),
      includeTotal: z._default(z.boolean(), false),
      order: z._default(
        ComCrmRewardOfferDonationsSelfServiceResourceListOrder$outboundSchema,
        "DESC",
      ),
      page: z._default(z.int(), 1),
      size: z._default(z.int(), 10),
      sort: z._default(z.string(), "CREATED_DATE"),
    }),
    z.transform((v) => {
      return remap$(v, {
        donatedTo: "donated_to",
        donationOfferId: "donation_offer_id",
        donationTypes: "donation_types",
        searchValue: "search_value",
        includeTotal: "include_total",
      });
    }),
  );

export function comCrmRewardOfferDonationsSelfServiceResourceListRequestToJSON(
  comCrmRewardOfferDonationsSelfServiceResourceListRequest:
    ComCrmRewardOfferDonationsSelfServiceResourceListRequest,
): string {
  return JSON.stringify(
    ComCrmRewardOfferDonationsSelfServiceResourceListRequest$outboundSchema
      .parse(comCrmRewardOfferDonationsSelfServiceResourceListRequest),
  );
}

/** @internal */
export const ComCrmRewardOfferDonationsSelfServiceResourceListPaging$inboundSchema:
  z.ZodMiniType<
    ComCrmRewardOfferDonationsSelfServiceResourceListPaging,
    unknown
  > = z.pipe(
    z.object({
      page: types.optional(types.number()),
      size: types.optional(types.number()),
      total: types.optional(types.number()),
      has_more: types.optional(types.boolean()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "has_more": "hasMore",
      });
    }),
  );

export function comCrmRewardOfferDonationsSelfServiceResourceListPagingFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmRewardOfferDonationsSelfServiceResourceListPaging,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmRewardOfferDonationsSelfServiceResourceListPaging$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmRewardOfferDonationsSelfServiceResourceListPaging' from JSON`,
  );
}

/** @internal */
export const ComCrmRewardOfferDonationsSelfServiceResourceListUsageType$inboundSchema:
  z.ZodMiniType<
    ComCrmRewardOfferDonationsSelfServiceResourceListUsageType,
    unknown
  > = openEnums.inboundSchema(
    ComCrmRewardOfferDonationsSelfServiceResourceListUsageType,
  );

/** @internal */
export const ComCrmRewardOfferDonationsSelfServiceResourceListMedia$inboundSchema:
  z.ZodMiniType<
    ComCrmRewardOfferDonationsSelfServiceResourceListMedia,
    unknown
  > = z.object({
    width: types.optional(types.number()),
    height: types.optional(types.number()),
    url: types.optional(types.string()),
  });

export function comCrmRewardOfferDonationsSelfServiceResourceListMediaFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmRewardOfferDonationsSelfServiceResourceListMedia,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmRewardOfferDonationsSelfServiceResourceListMedia$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmRewardOfferDonationsSelfServiceResourceListMedia' from JSON`,
  );
}

/** @internal */
export const ComCrmRewardOfferDonationsSelfServiceResourceListCreative$inboundSchema:
  z.ZodMiniType<
    ComCrmRewardOfferDonationsSelfServiceResourceListCreative,
    unknown
  > = z.pipe(
    z.object({
      id: types.optional(types.string()),
      media_group_id: types.optional(types.string()),
      usage_type: types.optional(
        ComCrmRewardOfferDonationsSelfServiceResourceListUsageType$inboundSchema,
      ),
      width: types.optional(types.number()),
      height: types.optional(types.number()),
      format: types.optional(types.string()),
      url: types.optional(types.string()),
      public_id: types.optional(types.string()),
      media_id: types.optional(types.string()),
      caption: types.optional(types.string()),
      sort_order: types.optional(types.number()),
      media: types.optional(z.array(z.lazy(() =>
        ComCrmRewardOfferDonationsSelfServiceResourceListMedia$inboundSchema
      ))),
    }),
    z.transform((v) => {
      return remap$(v, {
        "media_group_id": "mediaGroupId",
        "usage_type": "usageType",
        "public_id": "publicId",
        "media_id": "mediaId",
        "sort_order": "sortOrder",
      });
    }),
  );

export function comCrmRewardOfferDonationsSelfServiceResourceListCreativeFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmRewardOfferDonationsSelfServiceResourceListCreative,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmRewardOfferDonationsSelfServiceResourceListCreative$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmRewardOfferDonationsSelfServiceResourceListCreative' from JSON`,
  );
}

/** @internal */
export const ComCrmRewardOfferDonationsSelfServiceResourceListDonationType$inboundSchema:
  z.ZodMiniType<
    ComCrmRewardOfferDonationsSelfServiceResourceListDonationType,
    unknown
  > = openEnums.inboundSchema(
    ComCrmRewardOfferDonationsSelfServiceResourceListDonationType,
  );

/** @internal */
export const ComCrmRewardOfferDonationsSelfServiceResourceListType$inboundSchema:
  z.ZodMiniType<
    ComCrmRewardOfferDonationsSelfServiceResourceListType,
    unknown
  > = openEnums.inboundSchema(
    ComCrmRewardOfferDonationsSelfServiceResourceListType,
  );

/** @internal */
export const ComCrmRewardOfferDonationsSelfServiceResourceListContent$inboundSchema:
  z.ZodMiniType<
    ComCrmRewardOfferDonationsSelfServiceResourceListContent,
    unknown
  > = z.pipe(
    z.object({
      id: types.optional(types.string()),
      name: types.optional(types.string()),
      creatives: types.optional(z.array(z.lazy(() =>
        ComCrmRewardOfferDonationsSelfServiceResourceListCreative$inboundSchema
      ))),
      donation_type: types.optional(
        ComCrmRewardOfferDonationsSelfServiceResourceListDonationType$inboundSchema,
      ),
      type: types.optional(
        ComCrmRewardOfferDonationsSelfServiceResourceListType$inboundSchema,
      ),
      termed_amount: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "donation_type": "donationType",
        "termed_amount": "termedAmount",
      });
    }),
  );

export function comCrmRewardOfferDonationsSelfServiceResourceListContentFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmRewardOfferDonationsSelfServiceResourceListContent,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmRewardOfferDonationsSelfServiceResourceListContent$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmRewardOfferDonationsSelfServiceResourceListContent' from JSON`,
  );
}

/** @internal */
export const ComCrmRewardOfferDonationsSelfServiceResourceListResponse$inboundSchema:
  z.ZodMiniType<
    ComCrmRewardOfferDonationsSelfServiceResourceListResponse,
    unknown
  > = z.object({
    paging: types.optional(
      z.lazy(() =>
        ComCrmRewardOfferDonationsSelfServiceResourceListPaging$inboundSchema
      ),
    ),
    content: types.optional(
      z.array(z.lazy(() =>
        ComCrmRewardOfferDonationsSelfServiceResourceListContent$inboundSchema
      )),
    ),
  });

export function comCrmRewardOfferDonationsSelfServiceResourceListResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmRewardOfferDonationsSelfServiceResourceListResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmRewardOfferDonationsSelfServiceResourceListResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmRewardOfferDonationsSelfServiceResourceListResponse' from JSON`,
  );
}
