/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ComCrmContactSelfServiceResourceRemoveFileSecurity = {
  secretAPIKey?: string | undefined;
  authorization?: string | undefined;
};

export type ComCrmContactSelfServiceResourceRemoveFileRequest = {
  /**
   * The attachment (identifier) to be deleted
   */
  attachmentId: string;
  /**
   * The contact (identifier) for which attachment will be deleted
   */
  id: string;
};

/** @internal */
export type ComCrmContactSelfServiceResourceRemoveFileSecurity$Outbound = {
  Secret_API_key?: string | undefined;
  authorization?: string | undefined;
};

/** @internal */
export const ComCrmContactSelfServiceResourceRemoveFileSecurity$outboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceRemoveFileSecurity$Outbound,
    ComCrmContactSelfServiceResourceRemoveFileSecurity
  > = z.pipe(
    z.object({
      secretAPIKey: z.optional(z.string()),
      authorization: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        secretAPIKey: "Secret_API_key",
      });
    }),
  );

export function comCrmContactSelfServiceResourceRemoveFileSecurityToJSON(
  comCrmContactSelfServiceResourceRemoveFileSecurity:
    ComCrmContactSelfServiceResourceRemoveFileSecurity,
): string {
  return JSON.stringify(
    ComCrmContactSelfServiceResourceRemoveFileSecurity$outboundSchema.parse(
      comCrmContactSelfServiceResourceRemoveFileSecurity,
    ),
  );
}

/** @internal */
export type ComCrmContactSelfServiceResourceRemoveFileRequest$Outbound = {
  attachment_id: string;
  id: string;
};

/** @internal */
export const ComCrmContactSelfServiceResourceRemoveFileRequest$outboundSchema:
  z.ZodMiniType<
    ComCrmContactSelfServiceResourceRemoveFileRequest$Outbound,
    ComCrmContactSelfServiceResourceRemoveFileRequest
  > = z.pipe(
    z.object({
      attachmentId: z.string(),
      id: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        attachmentId: "attachment_id",
      });
    }),
  );

export function comCrmContactSelfServiceResourceRemoveFileRequestToJSON(
  comCrmContactSelfServiceResourceRemoveFileRequest:
    ComCrmContactSelfServiceResourceRemoveFileRequest,
): string {
  return JSON.stringify(
    ComCrmContactSelfServiceResourceRemoveFileRequest$outboundSchema.parse(
      comCrmContactSelfServiceResourceRemoveFileRequest,
    ),
  );
}
