/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSecurity =
  {
    secretAPIKey?: string | undefined;
    authorization?: string | undefined;
  };

/**
 * Defines how the results will be ordered
 */
export const ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsOrder =
  {
    Asc: "ASC",
    Desc: "DESC",
  } as const;
/**
 * Defines how the results will be ordered
 */
export type ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsOrder =
  ClosedEnum<
    typeof ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsOrder
  >;

export type ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsRequest =
  {
    /**
     * The unique identifier of the contact whose subscription actions will be retrieved
     */
    id: string;
    /**
     * Filter subscription actions based on behaviour code(s)
     */
    behaviourCode?: string | undefined;
    /**
     * Filter subscription actions based on business classification code(s)
     */
    businessClassificationCode?: string | undefined;
    /**
     * Filter based on the cancelled date, which may fall within a given date range. The value can be a string with a date in epoch format. Each option must also include an operator. Use up to two options based on the required search
     */
    cancelledOn?: number | undefined;
    /**
     * Returns results where the cancelled date is greater than this value
     */
    cancelledOnGt?: number | undefined;
    /**
     * Returns results where the cancelled date is greater than or equal to this value
     */
    cancelledOnGte?: number | undefined;
    /**
     * Returns results where the cancelled date is less than this value
     */
    cancelledOnLt?: number | undefined;
    /**
     * Returns results where the cancelled date is less than or equal to this value
     */
    cancelledOnLte?: number | undefined;
    /**
     * Filter based on the scheduled date, which may fall within a given date range. The value can be a string with a date in epoch format. Each option must also include an operator. Use up to two options based on the required search
     */
    scheduledOn?: number | undefined;
    /**
     * Returns results where the scheduled date is greater than this value
     */
    scheduledOnGt?: number | undefined;
    /**
     * Returns results where the scheduled date is greater than or equal to this value
     */
    scheduledOnGte?: number | undefined;
    /**
     * Returns results where the scheduled date is less than this value
     */
    scheduledOnLt?: number | undefined;
    /**
     * Returns results where the scheduled date is less than or equal to this value
     */
    scheduledOnLte?: number | undefined;
    /**
     * Filter subscription actions based on state(s)
     */
    state?: string | undefined;
    /**
     * The unique identifier of the subscription whose subscription actions will be retrieved
     */
    subscriptionId?: string | undefined;
    /**
     * Determine if a "total" will be returned in paging reference. If set to True, then "total" is also returned but it will return up to 10K value. If set to False, then the "total" in paging is null.
     */
    includeTotal?: boolean | undefined;
    /**
     * Defines how the results will be ordered
     */
    order?:
      | ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsOrder
      | undefined;
    /**
     * The page number that should be retrieved
     */
    page?: number | undefined;
    /**
     * The size (total records) of each page
     */
    size?: number | undefined;
    /**
     * Defines on which attribute the results should be sorted
     */
    sort?: string | undefined;
  };

export type ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsPaging =
  {
    /**
     * The page number
     */
    page?: number | undefined;
    /**
     * The number of records per page
     */
    size?: number | undefined;
    /**
     * The total number of records. If "include_total" is not specified, then this total is null. If "include_total" is specified, total has a value but it is accurate up to 10K records.
     */
    total?: number | undefined;
    /**
     * Shows if there are more records available to fetch
     */
    hasMore?: boolean | undefined;
  };

/**
 * State of Subscription action
 */
export const ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsState =
  {
    Scheduled: "SCHEDULED",
    Executed: "EXECUTED",
    Rejected: "REJECTED",
    Cancelled: "CANCELLED",
  } as const;
/**
 * State of Subscription action
 */
export type ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsState =
  OpenEnum<
    typeof ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsState
  >;

/**
 * The action's behaviour code shows how the action affetcs the service for example adds a new service, cancels or changes
 */
export const ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsBehaviourCode =
  {
    BecomeSubscriber: "BECOME_SUBSCRIBER",
    ChangeSubscription: "CHANGE_SUBSCRIPTION",
    Terminate: "TERMINATE",
    Pause: "PAUSE",
    Resume: "RESUME",
    Activate: "ACTIVATE",
    Deactivate: "DEACTIVATE",
    ApplyGracePeriod: "APPLY_GRACE_PERIOD",
    AddDevice: "ADD_DEVICE",
    ChangeDevice: "CHANGE_DEVICE",
    AddService: "ADD_SERVICE",
    RemoveService: "REMOVE_SERVICE",
    ChangeService: "CHANGE_SERVICE",
    PauseService: "PAUSE_SERVICE",
    ResumeService: "RESUME_SERVICE",
    ChangeTerms: "CHANGE_TERMS",
    ActivateService: "ACTIVATE_SERVICE",
    DeactivateService: "DEACTIVATE_SERVICE",
    ChangeServiceDistribution: "CHANGE_SERVICE_DISTRIBUTION",
    ExtendServiceTrial: "EXTEND_SERVICE_TRIAL",
    EndGracePeriod: "END_GRACE_PERIOD",
  } as const;
/**
 * The action's behaviour code shows how the action affetcs the service for example adds a new service, cancels or changes
 */
export type ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsBehaviourCode =
  OpenEnum<
    typeof ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsBehaviourCode
  >;

/**
 * The business classification code shows additional information about the action and its results such as service is added as draft or effective
 */
export const ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsBusinessClassificationCode =
  {
    BecomeSubscriber: "BECOME_SUBSCRIBER",
    ChangeBillingCycle: "CHANGE_BILLING_CYCLE",
    ChangeBillingDay: "CHANGE_BILLING_DAY",
    ChangePaymentMethod: "CHANGE_PAYMENT_METHOD",
    Pause: "PAUSE",
    Resume: "RESUME",
    Cancel: "CANCEL",
    Regret: "REGRET",
    Activate: "ACTIVATE",
    Deactivate: "DEACTIVATE",
    ApplyGracePeriod: "APPLY_GRACE_PERIOD",
    AddDevice: "ADD_DEVICE",
    RemoveDevice: "REMOVE_DEVICE",
    ReplaceDevice: "REPLACE_DEVICE",
    UpdateDevice: "UPDATE_DEVICE",
    AddServiceAsEffective: "ADD_SERVICE_AS_EFFECTIVE",
    AddServiceAsDraft: "ADD_SERVICE_AS_DRAFT",
    CancelService: "CANCEL_SERVICE",
    RegretService: "REGRET_SERVICE",
    UpgradeService: "UPGRADE_SERVICE",
    DowngradeService: "DOWNGRADE_SERVICE",
    PauseService: "PAUSE_SERVICE",
    ResumeService: "RESUME_SERVICE",
    OptInRenewals: "OPT_IN_RENEWALS",
    OptOutRenewals: "OPT_OUT_RENEWALS",
    RenewTerms: "RENEW_TERMS",
    RenewContract: "RENEW_CONTRACT",
    ExtendContract: "EXTEND_CONTRACT",
    ActivateService: "ACTIVATE_SERVICE",
    DeactivateService: "DEACTIVATE_SERVICE",
    ChangeServiceDistribution: "CHANGE_SERVICE_DISTRIBUTION",
    ExtendServiceTrial: "EXTEND_SERVICE_TRIAL",
    EndGracePeriod: "END_GRACE_PERIOD",
  } as const;
/**
 * The business classification code shows additional information about the action and its results such as service is added as draft or effective
 */
export type ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsBusinessClassificationCode =
  OpenEnum<
    typeof ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsBusinessClassificationCode
  >;

/**
 * The action's category
 */
export type ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsCategory =
  {
    /**
     * The subscription category identifier
     */
    id?: string | undefined;
    /**
     * The subscription category name
     */
    name?: string | undefined;
  };

/**
 * The action's related Subscription
 */
export type ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSubscription =
  {
    /**
     * The subscription identifier
     */
    id?: any | undefined;
    /**
     * The subscription code
     */
    code?: any | undefined;
  };

/**
 * Details about who submitted the subscription action
 */
export type ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSubmittedBy =
  {
    /**
     * The user/api key identifier
     */
    id?: any | undefined;
    /**
     * The username
     */
    username?: any | undefined;
    /**
     * The user/api key name
     */
    name?: any | undefined;
  };

/**
 * Details about who cancelled the subscription action
 */
export type ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsCancelledBy =
  {
    /**
     * The user/api key identifier
     */
    id?: any | undefined;
    /**
     * The username
     */
    username?: any | undefined;
    /**
     * The user/api key name
     */
    name?: any | undefined;
  };

export type ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsContent =
  {
    /**
     * The entity identifier
     */
    id?: string | undefined;
    /**
     * A unique 16-digit code for the subscription action
     */
    code?: string | undefined;
    /**
     * State of Subscription action
     */
    state?:
      | ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsState
      | undefined;
    /**
     * The action's behaviour code shows how the action affetcs the service for example adds a new service, cancels or changes
     */
    behaviourCode?:
      | ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsBehaviourCode
      | undefined;
    /**
     * The business classification code shows additional information about the action and its results such as service is added as draft or effective
     */
    businessClassificationCode?:
      | ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsBusinessClassificationCode
      | undefined;
    /**
     * Date of execution. Available only for Executed actions
     */
    executedOn?: number | undefined;
    /**
     * The scheduled date of a pending action. Available for Scheduled actions as well as Cancelled/Rejected ones to indicate there intended scheduled date
     */
    scheduledOn?: number | undefined;
    /**
     * The date on which a Scheduled action was cancelled
     */
    cancelledOn?: number | undefined;
    /**
     * The date on which the action was rejected.
     */
    rejectedOn?: number | undefined;
    /**
     * The action's category
     */
    category?:
      | ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsCategory
      | undefined;
    /**
     * The action's related Subscription
     */
    subscription?:
      | ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSubscription
      | undefined;
    /**
     * Details about who submitted the subscription action
     */
    submittedBy?:
      | ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSubmittedBy
      | undefined;
    /**
     * Details about who cancelled the subscription action
     */
    cancelledBy?:
      | ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsCancelledBy
      | undefined;
    /**
     * Returns the number of grace/pause period days the action applies to the subscription
     */
    numberOfDays?: number | undefined;
  };

/**
 * OK
 */
export type ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsResponse =
  {
    paging?:
      | ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsPaging
      | undefined;
    content?:
      | Array<
        ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsContent
      >
      | undefined;
  };

/** @internal */
export type ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSecurity$Outbound =
  {
    Secret_API_key?: string | undefined;
    authorization?: string | undefined;
  };

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSecurity$outboundSchema:
  z.ZodMiniType<
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSecurity$Outbound,
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSecurity
  > = z.pipe(
    z.object({
      secretAPIKey: z.optional(z.string()),
      authorization: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        secretAPIKey: "Secret_API_key",
      });
    }),
  );

export function comCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSecurityToJSON(
  comCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSecurity:
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSecurity,
): string {
  return JSON.stringify(
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSecurity$outboundSchema
      .parse(
        comCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSecurity,
      ),
  );
}

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsOrder$outboundSchema:
  z.ZodMiniEnum<
    typeof ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsOrder
  > = z.enum(
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsOrder,
  );

/** @internal */
export type ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsRequest$Outbound =
  {
    id: string;
    behaviour_code?: string | undefined;
    business_classification_code?: string | undefined;
    cancelled_on?: number | undefined;
    "cancelled_on[gt]"?: number | undefined;
    "cancelled_on[gte]"?: number | undefined;
    "cancelled_on[lt]"?: number | undefined;
    "cancelled_on[lte]"?: number | undefined;
    scheduled_on?: number | undefined;
    "scheduled_on[gt]"?: number | undefined;
    "scheduled_on[gte]"?: number | undefined;
    "scheduled_on[lt]"?: number | undefined;
    "scheduled_on[lte]"?: number | undefined;
    state?: string | undefined;
    subscription_id?: string | undefined;
    include_total: boolean;
    order: string;
    page: number;
    size: number;
    sort: string;
  };

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsRequest$outboundSchema:
  z.ZodMiniType<
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsRequest$Outbound,
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsRequest
  > = z.pipe(
    z.object({
      id: z.string(),
      behaviourCode: z.optional(z.string()),
      businessClassificationCode: z.optional(z.string()),
      cancelledOn: z.optional(z.int()),
      cancelledOnGt: z.optional(z.int()),
      cancelledOnGte: z.optional(z.int()),
      cancelledOnLt: z.optional(z.int()),
      cancelledOnLte: z.optional(z.int()),
      scheduledOn: z.optional(z.int()),
      scheduledOnGt: z.optional(z.int()),
      scheduledOnGte: z.optional(z.int()),
      scheduledOnLt: z.optional(z.int()),
      scheduledOnLte: z.optional(z.int()),
      state: z.optional(z.string()),
      subscriptionId: z.optional(z.string()),
      includeTotal: z._default(z.boolean(), false),
      order: z._default(
        ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsOrder$outboundSchema,
        "DESC",
      ),
      page: z._default(z.int(), 1),
      size: z._default(z.int(), 10),
      sort: z._default(z.string(), "CREATED_DATE"),
    }),
    z.transform((v) => {
      return remap$(v, {
        behaviourCode: "behaviour_code",
        businessClassificationCode: "business_classification_code",
        cancelledOn: "cancelled_on",
        cancelledOnGt: "cancelled_on[gt]",
        cancelledOnGte: "cancelled_on[gte]",
        cancelledOnLt: "cancelled_on[lt]",
        cancelledOnLte: "cancelled_on[lte]",
        scheduledOn: "scheduled_on",
        scheduledOnGt: "scheduled_on[gt]",
        scheduledOnGte: "scheduled_on[gte]",
        scheduledOnLt: "scheduled_on[lt]",
        scheduledOnLte: "scheduled_on[lte]",
        subscriptionId: "subscription_id",
        includeTotal: "include_total",
      });
    }),
  );

export function comCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsRequestToJSON(
  comCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsRequest:
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsRequest,
): string {
  return JSON.stringify(
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsRequest$outboundSchema
      .parse(
        comCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsRequest,
      ),
  );
}

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsPaging$inboundSchema:
  z.ZodMiniType<
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsPaging,
    unknown
  > = z.pipe(
    z.object({
      page: types.optional(types.number()),
      size: types.optional(types.number()),
      total: types.optional(types.number()),
      has_more: types.optional(types.boolean()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "has_more": "hasMore",
      });
    }),
  );

export function comCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsPagingFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsPaging,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsPaging$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsPaging' from JSON`,
  );
}

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsState$inboundSchema:
  z.ZodMiniType<
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsState,
    unknown
  > = openEnums.inboundSchema(
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsState,
  );

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsBehaviourCode$inboundSchema:
  z.ZodMiniType<
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsBehaviourCode,
    unknown
  > = openEnums.inboundSchema(
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsBehaviourCode,
  );

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsBusinessClassificationCode$inboundSchema:
  z.ZodMiniType<
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsBusinessClassificationCode,
    unknown
  > = openEnums.inboundSchema(
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsBusinessClassificationCode,
  );

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsCategory$inboundSchema:
  z.ZodMiniType<
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsCategory,
    unknown
  > = z.object({
    id: types.optional(types.string()),
    name: types.optional(types.string()),
  });

export function comCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsCategoryFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsCategory,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsCategory$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsCategory' from JSON`,
  );
}

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSubscription$inboundSchema:
  z.ZodMiniType<
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSubscription,
    unknown
  > = z.object({
    id: types.optional(z.any()),
    code: types.optional(z.any()),
  });

export function comCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSubscriptionFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSubscription,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSubscription$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSubscription' from JSON`,
  );
}

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSubmittedBy$inboundSchema:
  z.ZodMiniType<
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSubmittedBy,
    unknown
  > = z.object({
    id: types.optional(z.any()),
    username: types.optional(z.any()),
    name: types.optional(z.any()),
  });

export function comCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSubmittedByFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSubmittedBy,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSubmittedBy$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSubmittedBy' from JSON`,
  );
}

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsCancelledBy$inboundSchema:
  z.ZodMiniType<
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsCancelledBy,
    unknown
  > = z.object({
    id: types.optional(z.any()),
    username: types.optional(z.any()),
    name: types.optional(z.any()),
  });

export function comCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsCancelledByFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsCancelledBy,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsCancelledBy$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsCancelledBy' from JSON`,
  );
}

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsContent$inboundSchema:
  z.ZodMiniType<
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsContent,
    unknown
  > = z.pipe(
    z.object({
      id: types.optional(types.string()),
      code: types.optional(types.string()),
      state: types.optional(
        ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsState$inboundSchema,
      ),
      behaviour_code: types.optional(
        ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsBehaviourCode$inboundSchema,
      ),
      business_classification_code: types.optional(
        ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsBusinessClassificationCode$inboundSchema,
      ),
      executed_on: types.optional(types.number()),
      scheduled_on: types.optional(types.number()),
      cancelled_on: types.optional(types.number()),
      rejected_on: types.optional(types.number()),
      category: types.optional(z.lazy(() =>
        ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsCategory$inboundSchema
      )),
      subscription: types.optional(z.lazy(() =>
        ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSubscription$inboundSchema
      )),
      submitted_by: types.optional(z.lazy(() =>
        ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsSubmittedBy$inboundSchema
      )),
      cancelled_by: types.optional(z.lazy(() =>
        ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsCancelledBy$inboundSchema
      )),
      number_of_days: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "behaviour_code": "behaviourCode",
        "business_classification_code": "businessClassificationCode",
        "executed_on": "executedOn",
        "scheduled_on": "scheduledOn",
        "cancelled_on": "cancelledOn",
        "rejected_on": "rejectedOn",
        "submitted_by": "submittedBy",
        "cancelled_by": "cancelledBy",
        "number_of_days": "numberOfDays",
      });
    }),
  );

export function comCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsContentFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsContent,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsContent$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsContent' from JSON`,
  );
}

/** @internal */
export const ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsResponse$inboundSchema:
  z.ZodMiniType<
    ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsResponse,
    unknown
  > = z.object({
    paging: types.optional(
      z.lazy(() =>
        ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsPaging$inboundSchema
      ),
    ),
    content: types.optional(
      z.array(z.lazy(() =>
        ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsContent$inboundSchema
      )),
    ),
  });

export function comCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ComCrmSubscriptionSelfServiceResourceListContactSubscriptionActionsResponse' from JSON`,
  );
}
