/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7f718ecad8d1
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The entity type
 */
export const CrmComPrintoutSelfServiceResourceOutputType = {
  Invoice: "INVOICE",
  Orders: "ORDERS",
  Payment: "PAYMENT",
  CreditNote: "CREDIT_NOTE",
  Refund: "REFUND",
  Payout: "PAYOUT",
  ServiceRequest: "SERVICE_REQUEST",
  Subscriptions: "SUBSCRIPTIONS",
  RewardOffers: "REWARD_OFFERS",
  TopUp: "TOP_UP",
} as const;
/**
 * The entity type
 */
export type CrmComPrintoutSelfServiceResourceOutputType = ClosedEnum<
  typeof CrmComPrintoutSelfServiceResourceOutputType
>;

/**
 * Defines the entity based on which the printout will be created
 */
export type CrmComPrintoutSelfServiceResourceOutputEntity = {
  /**
   * The entity type
   */
  type: CrmComPrintoutSelfServiceResourceOutputType;
  /**
   * The entity identifier (e.g. invoice id)
   */
  id?: string | undefined;
};

/**
 * Defines the format on which the printout will be created to
 *
 * @remarks
 *
 *     EMAIL - Printout will be sent to the contact’s email address
 *     PDF - Printout will be generated as pdf
 */
export const CrmComPrintoutSelfServiceResourceOutputFormat = {
  Email: "EMAIL",
  WebView: "WEB_VIEW",
  Pdf: "PDF",
} as const;
/**
 * Defines the format on which the printout will be created to
 *
 * @remarks
 *
 *     EMAIL - Printout will be sent to the contact’s email address
 *     PDF - Printout will be generated as pdf
 */
export type CrmComPrintoutSelfServiceResourceOutputFormat = ClosedEnum<
  typeof CrmComPrintoutSelfServiceResourceOutputFormat
>;

export type CrmComPrintoutSelfServiceResourceOutputRequest = {
  /**
   * Defines the entity based on which the printout will be created
   */
  entity: CrmComPrintoutSelfServiceResourceOutputEntity;
  /**
   * Defines the format on which the printout will be created to
   *
   * @remarks
   *
   *     EMAIL - Printout will be sent to the contact’s email address
   *     PDF - Printout will be generated as pdf
   */
  format: CrmComPrintoutSelfServiceResourceOutputFormat;
};

/** @internal */
export const CrmComPrintoutSelfServiceResourceOutputType$outboundSchema:
  z.ZodMiniEnum<typeof CrmComPrintoutSelfServiceResourceOutputType> = z.enum(
    CrmComPrintoutSelfServiceResourceOutputType,
  );

/** @internal */
export type CrmComPrintoutSelfServiceResourceOutputEntity$Outbound = {
  type: string;
  id?: string | undefined;
};

/** @internal */
export const CrmComPrintoutSelfServiceResourceOutputEntity$outboundSchema:
  z.ZodMiniType<
    CrmComPrintoutSelfServiceResourceOutputEntity$Outbound,
    CrmComPrintoutSelfServiceResourceOutputEntity
  > = z.object({
    type: CrmComPrintoutSelfServiceResourceOutputType$outboundSchema,
    id: z.optional(z.string()),
  });

export function crmComPrintoutSelfServiceResourceOutputEntityToJSON(
  crmComPrintoutSelfServiceResourceOutputEntity:
    CrmComPrintoutSelfServiceResourceOutputEntity,
): string {
  return JSON.stringify(
    CrmComPrintoutSelfServiceResourceOutputEntity$outboundSchema.parse(
      crmComPrintoutSelfServiceResourceOutputEntity,
    ),
  );
}

/** @internal */
export const CrmComPrintoutSelfServiceResourceOutputFormat$outboundSchema:
  z.ZodMiniEnum<typeof CrmComPrintoutSelfServiceResourceOutputFormat> = z.enum(
    CrmComPrintoutSelfServiceResourceOutputFormat,
  );

/** @internal */
export type CrmComPrintoutSelfServiceResourceOutputRequest$Outbound = {
  entity: CrmComPrintoutSelfServiceResourceOutputEntity$Outbound;
  format: string;
};

/** @internal */
export const CrmComPrintoutSelfServiceResourceOutputRequest$outboundSchema:
  z.ZodMiniType<
    CrmComPrintoutSelfServiceResourceOutputRequest$Outbound,
    CrmComPrintoutSelfServiceResourceOutputRequest
  > = z.object({
    entity: z.lazy(() =>
      CrmComPrintoutSelfServiceResourceOutputEntity$outboundSchema
    ),
    format: CrmComPrintoutSelfServiceResourceOutputFormat$outboundSchema,
  });

export function crmComPrintoutSelfServiceResourceOutputRequestToJSON(
  crmComPrintoutSelfServiceResourceOutputRequest:
    CrmComPrintoutSelfServiceResourceOutputRequest,
): string {
  return JSON.stringify(
    CrmComPrintoutSelfServiceResourceOutputRequest$outboundSchema.parse(
      crmComPrintoutSelfServiceResourceOutputRequest,
    ),
  );
}
